/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: Alarm
  Dimensions:  16 * 16
  NumColors:   4
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsAlarm[] = {
     0x000000,0x1221F7,0x0000FF,0x091081
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalAlarm = {
  4,	/* number of entries */
  0, 	/* No transparency */
  &ColorsAlarm[0]
};

static GUI_CONST_STORAGE unsigned char acAlarm[] = {
  0x00, 0x05, 0x50, 0x00,
  0x00, 0xAA, 0x96, 0x00,
  0x0A, 0xAA, 0x96, 0xA0,
  0x0A, 0xAA, 0x96, 0xA0,
  0x2A, 0xAC, 0x16, 0xA8,
  0x2A, 0xAC, 0x16, 0xA8,
  0xAA, 0xAC, 0x16, 0xAA,
  0xAA, 0xAC, 0x16, 0xAA,
  0xAA, 0xAC, 0x16, 0xAA,
  0xAA, 0xAC, 0x26, 0xAA,
  0xAA, 0xAA, 0xAA, 0xAB,
  0x2A, 0xAC, 0x2A, 0xAB,
  0x3A, 0xAF, 0xEA, 0xAC,
  0x3A, 0xAF, 0xEA, 0xAC,
  0x0F, 0xAA, 0xAA, 0xF0,
  0x00, 0xFA, 0xAF, 0x00
};

GUI_CONST_STORAGE GUI_BITMAP bmAlarm = {
 16, /* XSize */
 16, /* YSize */
 4, /* BytesPerLine */
 2, /* BitsPerPixel */
 acAlarm,  /* Pointer to picture data (indices) */
 &PalAlarm  /* Pointer to palette */
};

/* *** End of file *** */
