/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: ArrowRight
  Dimensions:  5 * 9
  NumColors:   3
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsArrowRight[] = {
     0xFFFFFF,0x000000,0x777777
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalArrowRight = {
  3,	/* number of entries */
  0, 	/* No transparency */
  &ColorsArrowRight[0]
};

static GUI_CONST_STORAGE unsigned char acArrowRight[] = {
  0x15, 0x40,
  0x05, 0x40,
  0x01, 0x40,
  0x00, 0x40,
  0x00, 0x00,
  0x02, 0x40,
  0x09, 0x40,
  0x25, 0x40,
  0x95, 0x40
};

GUI_CONST_STORAGE GUI_BITMAP bmArrowRight = {
 5, /* XSize */
 9, /* YSize */
 2, /* BytesPerLine */
 2, /* BitsPerPixel */
 acArrowRight,  /* Pointer to picture data (indices) */
 &PalArrowRight  /* Pointer to palette */
};

/* *** End of file *** */
