/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: Check
  Dimensions:  9 * 9
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsCheck[] = {
     0x000000,0xFFFFFF
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalCheck = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsCheck[0]
};

static GUI_CONST_STORAGE unsigned char acCheck[] = {
  ________, ________,
  _______X, X_______,
  ______XX, ________,
  _____XX_, ________,
  X___XX__, ________,
  XXX_XX__, ________,
  _XXXX___, ________,
  __XXX___, ________,
  ___X____, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmCheck = {
 9, /* XSize */
 9, /* YSize */
 2, /* BytesPerLine */
 1, /* BitsPerPixel */
 acCheck,  /* Pointer to picture data (indices) */
 &PalCheck  /* Pointer to palette */
};

/* *** End of file *** */
