/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: Cursor
  Dimensions:  21 * 18
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsCursor[] = {
     0x000000,0xFFFFFF
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalCursor = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsCursor[0]
};

static GUI_CONST_STORAGE unsigned char acCursor[] = {
  ________, __X_____, ________,
  ________, __X_____, ________,
  ________, _XXX____, ________,
  ________, _XXX____, ________,
  ________, XXXXX___, ________,
  ________, XXXXX___, ________,
  _______X, XXXXXX__, ________,
  _______X, XXXXXX__, ________,
  ______XX, XXXXXXX_, ________,
  ______XX, XXXXXXX_, ________,
  _____XXX, XXXXXXXX, ________,
  _____XXX, XXXXXXXX, ________,
  ____XXXX, XXXXXXXX, X_______,
  ____XXXX, XXXXXXXX, X_______,
  ___XXXXX, XXXXXXXX, XX______,
  ___XXXXX, XXXXXXXX, XX______,
  __XXXXXX, XXXXXXXX, XXX_____,
  __XXXXXX, XXXXXXXX, XXX_____
};

GUI_CONST_STORAGE GUI_BITMAP bmCursor = {
 21, /* XSize */
 18, /* YSize */
 3, /* BytesPerLine */
 1, /* BitsPerPixel */
 acCursor,  /* Pointer to picture data (indices) */
 &PalCursor  /* Pointer to palette */
};

/* *** End of file *** */
