/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: FloatSwitchOn
  Dimensions:  13 * 13
  NumColors:   3
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsFloatSwitchOn[] = {
     0xDC00FF,0x777777,0xFFFFFF
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalFloatSwitchOn = {
  3,	/* number of entries */
  1, 	/* Has transparency */
  &ColorsFloatSwitchOn[0]
};

static GUI_CONST_STORAGE unsigned char acFloatSwitchOn[] = {
  0x05, 0x00, 0x00, 0x00,
  0x05, 0x00, 0x00, 0x00,
  0x05, 0x00, 0x00, 0x00,
  0x05, 0x00, 0xAA, 0x00,
  0x05, 0x0A, 0xAA, 0x80,
  0x05, 0x6A, 0xAA, 0x80,
  0x05, 0x6A, 0xAA, 0x80,
  0x00, 0x0A, 0xAA, 0x80,
  0x00, 0x00, 0xAA, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_BITMAP bmFloatSwitchOn = {
 13, /* XSize */
 13, /* YSize */
 4, /* BytesPerLine */
 2, /* BitsPerPixel */
 acFloatSwitchOn,  /* Pointer to picture data (indices) */
 &PalFloatSwitchOn  /* Pointer to palette */
};

/* *** End of file *** */
