/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: Info
  Dimensions:  14 * 13
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsInfo[] = {
     0x000000,0xFFFFFF
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalInfo = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsInfo[0]
};

static GUI_CONST_STORAGE unsigned char acInfo[] = {
  _____XXX, X_______,
  ___XX___, _XX_____,
  __XX__XX, __XX____,
  _XX___X_, ___XX___,
  _X______, ____X___,
  XX____XX, ____XX__,
  X_____XX, _____X__,
  XX____XX, ____XX__,
  _X____XX, ____X___,
  _XX___XX, ___XX___,
  __XX__XX, __XX____,
  ___XX___, _XX_____,
  _____XXX, X_______
};

GUI_CONST_STORAGE GUI_BITMAP bmInfo = {
 14, /* XSize */
 13, /* YSize */
 2, /* BytesPerLine */
 1, /* BitsPerPixel */
 acInfo,  /* Pointer to picture data (indices) */
 &PalInfo  /* Pointer to palette */
};

/* *** End of file *** */
