/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: OpenSwitch
  Dimensions:  33 * 12
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsOpenSwitch[] = {
     0x000000,0x777777
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalOpenSwitch = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsOpenSwitch[0]
};

static GUI_CONST_STORAGE unsigned char acOpenSwitch[] = {
  ________, ________, __X_____, ________, ________,
  ________, ________, _X______, ________, ________,
  ________, ________, X_______, ________, ________,
  ________, _______X, ________, ________, ________,
  ________, ______X_, ________, ________, ________,
  ________, __XX_X__, _______X, X_______, ________,
  ________, _XXXX___, ______XX, XX______, ________,
  ___XXXXX, XXXXX___, ______XX, XXXXXXXX, ________,
  ________, _XXXX___, ______XX, XX______, ________,
  ________, __XX____, _______X, X_______, ________,
  ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmOpenSwitch = {
 33, /* XSize */
 12, /* YSize */
 5, /* BytesPerLine */
 1, /* BitsPerPixel */
 acOpenSwitch,  /* Pointer to picture data (indices) */
 &PalOpenSwitch  /* Pointer to palette */
};

/* *** End of file *** */
