/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: PitBottom
  Dimensions:  139 * 2
  NumColors:   1
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsPitBottom[] = {
     0x777777
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalPitBottom = {
  1,	/* number of entries */
  0, 	/* No transparency */
  &ColorsPitBottom[0]
};

static GUI_CONST_STORAGE unsigned char acPitBottom[] = {
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmPitBottom = {
 139, /* XSize */
 2, /* YSize */
 18, /* BytesPerLine */
 1, /* BitsPerPixel */
 acPitBottom,  /* Pointer to picture data (indices) */
 &PalPitBottom  /* Pointer to palette */
};

/* *** End of file *** */
