/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: PitLevel2
  Dimensions:  160 * 1
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsPitLevel2[] = {
     0xDC00FF,0xFFFFFF
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalPitLevel2 = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &ColorsPitLevel2[0]
};

static GUI_CONST_STORAGE unsigned char acPitLevel2[] = {
  XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__
};

GUI_CONST_STORAGE GUI_BITMAP bmPitLevel2 = {
 160, /* XSize */
 1, /* YSize */
 20, /* BytesPerLine */
 1, /* BitsPerPixel */
 acPitLevel2,  /* Pointer to picture data (indices) */
 &PalPitLevel2  /* Pointer to palette */
};

/* *** End of file *** */
