/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: PitPumpDisabled
  Dimensions:  17 * 22
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsPitPumpDisabled[] = {
     0x000000,0xFFFFFF
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalPitPumpDisabled = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &ColorsPitPumpDisabled[0]
};

static GUI_CONST_STORAGE unsigned char acPitPumpDisabled[] = {
  _XX_____, _______X, ________,
  XXXX____, ______XX, X_______,
  _XXXX___, _____XXX, X_______,
  __XXX___, _____XXX, ________,
  ___XXX__, ____XXX_, ________,
  ___XXXX_, ___XXXX_, ________,
  ____XXXX, __XXXX__, ________,
  _____XXX, __XXX___, ________,
  ______XX, XXXX____, ________,
  ______XX, XXXX____, ________,
  _______X, XXX_____, ________,
  _______X, XXX_____, ________,
  ______XX, XXXX____, ________,
  _____XXX, XXXXX___, ________,
  _____XXX, __XXXX__, ________,
  ____XXX_, ___XXX__, ________,
  ___XXXX_, ____XXX_, ________,
  ___XXX__, ____XXXX, ________,
  __XXX___, _____XXX, X_______,
  _XXXX___, ______XX, X_______,
  XXXX____, _______X, ________,
  _XX_____, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmPitPumpDisabled = {
 17, /* XSize */
 22, /* YSize */
 3, /* BytesPerLine */
 1, /* BitsPerPixel */
 acPitPumpDisabled,  /* Pointer to picture data (indices) */
 &PalPitPumpDisabled  /* Pointer to palette */
};

/* *** End of file *** */
