/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __CU351VIEWER_JAR_H__
#define __CU351VIEWER_JAR_H__

#define CU351VIEWER_JAR_SIZE 159843
extern unsigned char CU351VIEWER_JAR_DATA[];

#endif
