/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: ArrowLeft
  Dimensions:  5 * 9
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsArrowLeft[] = {
     0xFFFFFF,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalArrowLeft = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsArrowLeft[0]
};

static GUI_CONST_STORAGE unsigned char acArrowLeft[] = {
  ____X___,
  ___XX___,
  __XXX___,
  _XXXX___,
  XXXXX___,
  _XXXX___,
  __XXX___,
  ___XX___,
  ____X___
};

GUI_CONST_STORAGE GUI_BITMAP bmArrowLeft = {
 5, /* XSize */
 9, /* YSize */
 1, /* BytesPerLine */
 1, /* BitsPerPixel */
 acArrowLeft,  /* Pointer to picture data (indices) */
 &PalArrowLeft  /* Pointer to palette */
};

/* *** End of file *** */
