/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: Contrast_icon
  Dimensions:  21 * 21
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsContrast_icon[] = {
     0xFDFDFF,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalContrast_icon = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsContrast_icon[0]
};

static GUI_CONST_STORAGE unsigned char acContrast_icon[] = {
  ________, XXXXX___, ________,
  _____XXX, __XXXXXX, ________,
  ____X___, __XXXXXX, X_______,
  ___X____, __XXXXXX, XX______,
  __X_____, __XXXXXX, XXX_____,
  _X______, __XXXXXX, XXXX____,
  _X______, __XXXXXX, XXXX____,
  _X______, __XXXXXX, XXXX____,
  X_______, __XXXXXX, XXXXX___,
  X_______, __XXXXXX, XXXXX___,
  X_______, __XXXXXX, XXXXX___,
  X_______, __XXXXXX, XXXXX___,
  X_______, __XXXXXX, XXXXX___,
  _X______, __XXXXXX, XXXX____,
  _X______, __XXXXXX, XXXX____,
  _X______, __XXXXXX, XXXX____,
  __X_____, __XXXXXX, XXX_____,
  ___X____, __XXXXXX, XX______,
  ____X___, __XXXXXX, X_______,
  _____XXX, __XXXXXX, ________,
  ________, XXXXX___, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmContrast_icon = {
 21, /* XSize */
 21, /* YSize */
 3, /* BytesPerLine */
 1, /* BitsPerPixel */
 acContrast_icon,  /* Pointer to picture data (indices) */
 &PalContrast_icon  /* Pointer to palette */
};

/* *** End of file *** */
