/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: GoOn
  Dimensions:  80 * 15
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsGoOn[] = {
     0xFFFFFF,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalGoOn = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsGoOn[0]
};

static GUI_CONST_STORAGE unsigned char acGoOn[] = {
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, _______X, X_______, ________, ________, ________, ________,
  ________, ________, ________, ________, _______X, _XX_____, ________, ________, ________, ________,
  ________, ________, ________, ________, _______X, ___XX___, ________, ________, ________, ________,
  ________, ________, ________, _XXXXXXX, XXXXXXXX, _____XX_, ________, ________, ________, ________,
  ________, ________, ________, _X______, ________, ______XX, X_______, ________, ________, ________,
  ________, ________, ________, _XXXXXXX, XXXXXXXX, _____XX_, ________, ________, ________, ________,
  ________, ________, ________, ________, _______X, ___XX___, ________, ________, ________, ________,
  ________, ________, ________, ________, _______X, _XX_____, ________, ________, ________, ________,
  ________, ________, ________, ________, _______X, X_______, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmGoOn = {
 80, /* XSize */
 15, /* YSize */
 10, /* BytesPerLine */
 1, /* BitsPerPixel */
 acGoOn,  /* Pointer to picture data (indices) */
 &PalGoOn  /* Pointer to palette */
};

/* *** End of file *** */
