/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: HorisontalFlowAnimation
  Dimensions:  13 * 20
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsHorisontalFlowAnimation[] = {
     0x000000,0xFFFFFF
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalHorisontalFlowAnimation = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsHorisontalFlowAnimation[0]
};

static GUI_CONST_STORAGE unsigned char acHorisontalFlowAnimation[] = {
  __X__XX_, _XX_____,
  __X__XX_, _XX_____,
  __X__XX_, _XX_____,
  __X__XX_, _XX_____,
  __XX__XX, __XX____,
  __XX__XX, __XX____,
  __XX__XX, __XX____,
  __XX__XX, __XX____,
  ___XX__X, X__XX___,
  ___XX__X, X__XX___,
  ___XX__X, X__XX___,
  ___XX__X, X__XX___,
  ____XX__, XX__X___,
  ____XX__, XX__X___,
  ____XX__, XX__X___,
  ____XX__, XX__X___,
  ________, ________,
  ________, ________,
  ________, ________,
  ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmHorisontalFlowAnimation = {
 13, /* XSize */
 20, /* YSize */
 2, /* BytesPerLine */
 1, /* BitsPerPixel */
 acHorisontalFlowAnimation,  /* Pointer to picture data (indices) */
 &PalHorisontalFlowAnimation  /* Pointer to palette */
};

/* *** End of file *** */
