/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: Info
  Dimensions:  14 * 13
  NumColors:   3
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsInfo[] = {
     0x404040,0x000000,0xFFFFFF
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalInfo = {
  3,	/* number of entries */
  0, 	/* No transparency */
  &ColorsInfo[0]
};

static GUI_CONST_STORAGE unsigned char acInfo[] = {
  0x00, 0x15, 0x40, 0x00,
  0x01, 0x6A, 0x94, 0x00,
  0x06, 0xA5, 0xA9, 0x00,
  0x1A, 0xA5, 0xAA, 0x40,
  0x1A, 0xAA, 0xAA, 0x40,
  0x6A, 0xA5, 0xAA, 0x90,
  0x6A, 0xA5, 0xAA, 0x90,
  0x6A, 0xA5, 0xAA, 0x90,
  0x1A, 0xA5, 0xAA, 0x40,
  0x1A, 0xA5, 0xAA, 0x40,
  0x06, 0xA5, 0xA9, 0x00,
  0x01, 0x6A, 0x94, 0x00,
  0x00, 0x15, 0x40, 0x00
};

GUI_CONST_STORAGE GUI_BITMAP bmInfo = {
 14, /* XSize */
 13, /* YSize */
 4, /* BytesPerLine */
 2, /* BitsPerPixel */
 acInfo,  /* Pointer to picture data (indices) */
 &PalInfo  /* Pointer to palette */
};

/* *** End of file *** */
