/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: OverflowBlevelSensorInChannel
  Dimensions:  25 * 22
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsOverflowBlevelSensorInChannel[] = {
     0xFFFFFF,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalOverflowBlevelSensorInChannel = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsOverflowBlevelSensorInChannel[0]
};

static GUI_CONST_STORAGE unsigned char acOverflowBlevelSensorInChannel[] = {
  ________, ___X____, ________, ________,
  ________, ____X___, ________, ________,
  ________, ___X____, ________, ________,
  ________, ___X____, ________, ________,
  ________, ____X___, ________, ________,
  ________, ___X____, ________, ________,
  ________, __XXX___, ________, ________,
  ________, _XXXXX__, ________, ________,
  ________, XXXXXXX_, ________, ________,
  _______X, XXXXXXXX, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXX_____, ________, ________, ________,
  XX______, ________, ________, ________,
  XX______, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmOverflowBlevelSensorInChannel = {
 25, /* XSize */
 22, /* YSize */
 4, /* BytesPerLine */
 1, /* BitsPerPixel */
 acOverflowBlevelSensorInChannel,  /* Pointer to picture data (indices) */
 &PalOverflowBlevelSensorInChannel  /* Pointer to palette */
};

/* *** End of file *** */
