/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: Pit2Pumps
  Dimensions:  64 * 29
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsPit2Pumps[] = {
     0xFFFFFF,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalPit2Pumps = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsPit2Pumps[0]
};

static GUI_CONST_STORAGE unsigned char acPit2Pumps[] = {
  _____XXX, XXXXXX__, ________, XXXXXXXX, X_______, ________, ________, ________,
  _____XXX, XXXXXX__, ________, XXXXXXXX, X_______, ________, ________, ________,
  ____XXXX, XXXXXXX_, _______X, XXXXXXXX, XX______, ________, ________, ________,
  ____XXX_, ______X_, _______X, XX______, _X______, ________, ________, ________,
  ___XXX__, ______XX, ______XX, X_______, _XX_____, ________, ________, ________,
  ___XXX__, _______X, ______XX, X_______, __X_____, ________, ________, ________,
  ___XXX__, _______X, ______XX, X_______, __X_____, ________, ________, ________,
  __XXX___, _______X, X____XXX, ________, __XX____, ________, ________, ________,
  __XXX___, ________, X____XXX, ________, ___X____, ________, ________, ________,
  __XXX___, _XX_____, X____XXX, ____XXX_, ___X____, ________, ________, ________,
  __XXX___, __X_____, X____XXX, ___X___X, ___X____, ________, ________, ________,
  _XXX____, __X_____, X___XXX_, _______X, ___X____, ________, ________, ________,
  _XXX____, __X_____, X___XXX_, ______X_, ___X____, ________, ________, ________,
  _XXX____, __X_____, XX__XXX_, _____X__, ___XX___, ________, ________, ________,
  _XXX____, __X_____, _X__XXX_, ____X___, ____X___, ________, ________, ________,
  _XXX____, __X_____, _X__XXX_, ___X____, ____X___, ________, ________, ________,
  _XXX____, __X_____, _X__XXX_, ___XXXXX, ____X___, ________, ________, ________,
  _XXX____, ________, _X__XXX_, ________, ____X_XX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  _XXX____, ________, _X__XXX_, ________, ____X__X, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  _XXX____, ________, _X__XXX_, ________, ____X___, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  _XXX____, ________, _X__XXX_, ________, ____X__X, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  _XXX____, ________, _X__XXX_, ________, ____X_XX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  _XXX____, ________, _X__XXX_, ________, ____X___, ________, ________, ________,
  _XXX____, ________, _X__XXX_, ________, ____X___, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bmPit2Pumps = {
 64, /* XSize */
 29, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 acPit2Pumps,  /* Pointer to picture data (indices) */
 &PalPit2Pumps  /* Pointer to palette */
};

/* *** End of file *** */
