/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: Pit4Pumps
  Dimensions:  102 * 29
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsPit4Pumps[] = {
     0xFFFFFF,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalPit4Pumps = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsPit4Pumps[0]
};

static GUI_CONST_STORAGE unsigned char acPit4Pumps[] = {
  _____XXX, XXXXXX__, ________, XXXXXXXX, X_______, ___XXXXX, XXXX____, ______XX, XXXXXXX_, ________, ________, ________, ________,
  _____XXX, XXXXXX__, ________, XXXXXXXX, X_______, ___XXXXX, XXXX____, ______XX, XXXXXXX_, ________, ________, ________, ________,
  ____XXXX, XXXXXXX_, _______X, XXXXXXXX, XX______, __XXXXXX, XXXXX___, _____XXX, XXXXXXXX, ________, ________, ________, ________,
  ____XXX_, ______X_, _______X, XX______, _X______, __XXX___, ____X___, _____XXX, _______X, ________, ________, ________, ________,
  ___XXX__, ______XX, ______XX, X_______, _XX_____, _XXX____, ____XX__, ____XXX_, _______X, X_______, ________, ________, ________,
  ___XXX__, _______X, ______XX, X_______, __X_____, _XXX____, _____X__, ____XXX_, ________, X_______, ________, ________, ________,
  ___XXX__, _______X, ______XX, X_______, __X_____, _XXX____, _____X__, ____XXX_, ________, X_______, ________, ________, ________,
  __XXX___, _______X, X____XXX, ________, __XX____, XXX_____, _____XX_, ___XXX__, ________, XX______, ________, ________, ________,
  __XXX___, ________, X____XXX, ________, ___X____, XXX_____, ______X_, ___XXX__, ________, _X______, ________, ________, ________,
  __XXX___, _XX_____, X____XXX, ____XXX_, ___X____, XXX____X, XX____X_, ___XXX__, ____X___, _X______, ________, ________, ________,
  __XXX___, __X_____, X____XXX, ___X___X, ___X____, XXX___X_, __X___X_, ___XXX__, ___XX___, _X______, ________, ________, ________,
  _XXX____, __X_____, X___XXX_, _______X, ___X___X, XX______, __X___X_, __XXX___, __X_X___, _X______, ________, ________, ________,
  _XXX____, __X_____, X___XXX_, ______X_, ___X___X, XX______, XX____X_, __XXX___, _X__X___, _X______, ________, ________, ________,
  _XXX____, __X_____, XX__XXX_, _____X__, ___XX__X, XX______, __X___XX, __XXX___, X___X___, _XX_____, ________, ________, ________,
  _XXX____, __X_____, _X__XXX_, ____X___, ____X__X, XX______, __X____X, __XXX___, XXXXXX__, __X_____, ________, ________, ________,
  _XXX____, __X_____, _X__XXX_, ___X____, ____X__X, XX____X_, __X____X, __XXX___, ____X___, __X_____, ________, ________, ________,
  _XXX____, __X_____, _X__XXX_, ___XXXXX, ____X__X, XX_____X, XX_____X, __XXX___, ____X___, __X_____, ________, ________, ________,
  _XXX____, ________, _X__XXX_, ________, ____X__X, XX______, _______X, __XXX___, ________, __X_XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  _XXX____, ________, _X__XXX_, ________, ____X__X, XX______, _______X, __XXX___, ________, __X__XXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  _XXX____, ________, _X__XXX_, ________, ____X__X, XX______, _______X, __XXX___, ________, __X___XX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  _XXX____, ________, _X__XXX_, ________, ____X__X, XX______, _______X, __XXX___, ________, __X__XXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  _XXX____, ________, _X__XXX_, ________, ____X__X, XX______, _______X, __XXX___, ________, __X_XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  _XXX____, ________, _X__XXX_, ________, ____X__X, XX______, _______X, __XXX___, ________, __X_____, ________, ________, ________,
  _XXX____, ________, _X__XXX_, ________, ____X__X, XX______, _______X, __XXX___, ________, __X_____, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__
};

GUI_CONST_STORAGE GUI_BITMAP bmPit4Pumps = {
 102, /* XSize */
 29, /* YSize */
 13, /* BytesPerLine */
 1, /* BitsPerPixel */
 acPit4Pumps,  /* Pointer to picture data (indices) */
 &PalPit4Pumps  /* Pointer to palette */
};

/* *** End of file *** */
