/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: PitInlet
  Dimensions:  28 * 7
  NumColors:   3
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsPitInlet[] = {
     0xFFFFFF,0x5C5C5C,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalPitInlet = {
  3,	/* number of entries */
  0, 	/* No transparency */
  &ColorsPitInlet[0]
};

static GUI_CONST_STORAGE unsigned char acPitInlet[] = {
  0x00, 0x00, 0x10, 0x01, 0x00, 0xA0, 0x00,
  0xAA, 0xAA, 0x94, 0x05, 0xAA, 0xAA, 0xAA,
  0x2A, 0xAA, 0x95, 0x15, 0xAA, 0xAA, 0xAA,
  0x0A, 0xAA, 0x95, 0x55, 0xAA, 0xAA, 0xAA,
  0x2A, 0xAA, 0x95, 0x15, 0xAA, 0xAA, 0xAA,
  0xAA, 0xAA, 0x94, 0x05, 0xAA, 0xAA, 0xAA,
  0x00, 0x00, 0x10, 0x01, 0x00, 0xA0, 0x00
};

GUI_CONST_STORAGE GUI_BITMAP bmPitInlet = {
 28, /* XSize */
 7, /* YSize */
 7, /* BytesPerLine */
 2, /* BitsPerPixel */
 acPitInlet,  /* Pointer to picture data (indices) */
 &PalPitInlet  /* Pointer to palette */
};

/* *** End of file *** */
