/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: PitLevelSensor
  Dimensions:  6 * 35
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsPitLevelSensor[] = {
     0xFFFFFF,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalPitLevelSensor = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &ColorsPitLevelSensor[0]
};

static GUI_CONST_STORAGE unsigned char acPitLevelSensor[] = {
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _XX_____,
  XX______,
  X_______,
  X_______,
  X_______,
  XX______,
  _XX_____,
  __XX____,
  ___X____,
  ___X____,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__
};

GUI_CONST_STORAGE GUI_BITMAP bmPitLevelSensor = {
 6, /* XSize */
 35, /* YSize */
 1, /* BytesPerLine */
 1, /* BitsPerPixel */
 acPitLevelSensor,  /* Pointer to picture data (indices) */
 &PalPitLevelSensor  /* Pointer to palette */
};

/* *** End of file *** */
