/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: PitLevel
  Dimensions:  160 * 1
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsPitLevel[] = {
     0xFFFFFF,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalPitLevel = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &ColorsPitLevel[0]
};

static GUI_CONST_STORAGE unsigned char acPitLevel[] = {
  XXX_XXX_, _XXX_XXX, __XXX_XX, X__XXX_X, XX__XXX_, XXX__XXX, _XXX__XX, X_XXX__X, XX_XXX__, XXX_XXX_, _XXX_XXX, __XXX_XX, X__XXX_X, XX__XXX_, XXX__XXX, _XXX__XX, X_XXX__X, XX_XXX__, XXX_XXX_, _XXX_XXX
};

GUI_CONST_STORAGE GUI_BITMAP bmPitLevel = {
 160, /* XSize */
 1, /* YSize */
 20, /* BytesPerLine */
 1, /* BitsPerPixel */
 acPitLevel,  /* Pointer to picture data (indices) */
 &PalPitLevel  /* Pointer to palette */
};

/* *** End of file *** */
