/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: PitRight
  Dimensions:  13 * 117
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsPitRight[] = {
     0xFFFFFF,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalPitRight = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &ColorsPitRight[0]
};

static GUI_CONST_STORAGE unsigned char acPitRight[] = {
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXXX___, ___XX___,
  XXXX____, ___XX___,
  XXXX____, ___XX___,
  XXXX____, ___XX___,
  XXX_____, ___XX___,
  X_______, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, ___XX___,
  ________, __XXX___,
  XXXXXXXX, XXXX____,
  XXXXXXXX, XXX_____
};

GUI_CONST_STORAGE GUI_BITMAP bmPitRight = {
 13, /* XSize */
 117, /* YSize */
 2, /* BytesPerLine */
 1, /* BitsPerPixel */
 acPitRight,  /* Pointer to picture data (indices) */
 &PalPitRight  /* Pointer to palette */
};

/* *** End of file *** */
