/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: PitSonicSensor
  Dimensions:  22 * 18
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsPitSonicSensor[] = {
     0xFFFFFF,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalPitSonicSensor = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsPitSonicSensor[0]
};

static GUI_CONST_STORAGE unsigned char acPitSonicSensor[] = {
  ________, _XXXX___, ________,
  ________, _X_XX___, ________,
  ________, _X_XX___, ________,
  ________, _X_XX___, ________,
  ________, XX_XXX__, ________,
  ________, _X_XX___, ________,
  ________, _XXXX___, ________,
  ________, ________, ________,
  _______X, X____XX_, ________,
  ________, _XXXX___, ________,
  ________, ________, ________,
  _____X__, ________, X_______,
  ______XX, ______XX, ________,
  ________, XXXXXX__, ________,
  ________, ________, ________,
  ___X____, ________, __X_____,
  ____XXX_, _______X, XX______,
  _______X, XXXXXXX_, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmPitSonicSensor = {
 22, /* XSize */
 18, /* YSize */
 3, /* BytesPerLine */
 1, /* BitsPerPixel */
 acPitSonicSensor,  /* Pointer to picture data (indices) */
 &PalPitSonicSensor  /* Pointer to palette */
};

/* *** End of file *** */
