/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: PitSurface
  Dimensions:  151 * 4
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsPitSurface[] = {
     0xFFFFFF,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalPitSurface = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsPitSurface[0]
};

static GUI_CONST_STORAGE unsigned char acPitSurface[] = {
  ___X____, ____X___, _____X__, ______X_, _______X, ________, X_______, _X______, __X_____, ___X____, ____X___, _____X__, ______X_, _______X, ________, X_______, _X______, __X_____, ___X____,
  _XXX____, __XXX___, ___XXX__, ____XXX_, _____XXX, ______XX, X______X, XX______, XXX_____, _XXX____, __XXX___, ___XXX__, ____XXX_, _____XXX, ______XX, X______X, XX______, XXX_____, _XXX____,
  XX_XX___, XXX_XX__, _XXX_XX_, __XXX_XX, ___XXX_X, X___XXX_, XX___XXX, _XX___XX, X_XX___X, XX_XX___, XXX_XX__, _XXX_XX_, __XXX_XX, ___XXX_X, X___XXX_, XX___XXX, _XX___XX, X_XX___X, XX_XX___,
  ____XXXX, X____XXX, XX____XX, XXX____X, XXXX____, XXXXX___, _XXXXX__, __XXXXX_, ___XXXXX, ____XXXX, X____XXX, XX____XX, XXX____X, XXXX____, XXXXX___, _XXXXX__, __XXXXX_, ___XXXXX, ____XXX_
};

GUI_CONST_STORAGE GUI_BITMAP bmPitSurface = {
 151, /* XSize */
 4, /* YSize */
 19, /* BytesPerLine */
 1, /* BitsPerPixel */
 acPitSurface,  /* Pointer to picture data (indices) */
 &PalPitSurface  /* Pointer to palette */
};

/* *** End of file *** */
