/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: PumpAlarm
  Dimensions:  23 * 15
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsPumpAlarm[] = {
     0xFFFFFF,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalPumpAlarm = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsPumpAlarm[0]
};

static GUI_CONST_STORAGE unsigned char acPumpAlarm[] = {
  ________, ________, ________,
  ________, ____XX__, ________,
  ________, ___XXXXX, ________,
  ________, __XXXXXX, X_______,
  ________, _XXXXXXX, XX______,
  ________, XXXXXXXX, XX______,
  XXX__XXX, XXXXXXXX, X___XXX_,
  XXX__X__, XXXXXXXX, X___XXX_,
  XXX__XX_, _XXXXXXX, ____XXX_,
  ______X_, _X__XXXX, ________,
  _______X, ______XX, ________,
  ________, XX_____X, X_______,
  ________, __XXX___, X_______,
  ________, _____XXX, ________,
  ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmPumpAlarm = {
 23, /* XSize */
 15, /* YSize */
 3, /* BytesPerLine */
 1, /* BitsPerPixel */
 acPumpAlarm,  /* Pointer to picture data (indices) */
 &PalPumpAlarm  /* Pointer to palette */
};

/* *** End of file *** */
