/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: StatusWarning
  Dimensions:  13 * 13
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsStatusWarning[] = {
     0xFFFFFF,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalStatusWarning = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsStatusWarning[0]
};

static GUI_CONST_STORAGE unsigned char acStatusWarning[] = {
  _______X, X_______,
  ______XX, XXX_____,
  _____XXX, XXXX____,
  ____XXXX, XXXXX___,
  ___XXXXX, XXXXX___,
  XXXXXXXX, XXXX____,
  X__XXXXX, XXXX____,
  XX__XXXX, XXX_____,
  _X__X__X, XXX_____,
  __X_____, _XX_____,
  ___XX___, __XX____,
  _____XXX, ___X____,
  ________, XXX_____
};

GUI_CONST_STORAGE GUI_BITMAP bmStatusWarning = {
 13, /* XSize */
 13, /* YSize */
 2, /* BytesPerLine */
 1, /* BitsPerPixel */
 acStatusWarning,  /* Pointer to picture data (indices) */
 &PalStatusWarning  /* Pointer to palette */
};

/* *** End of file *** */
