/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: TrendDown
  Dimensions:  13 * 13
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsTrendDown[] = {
     0xFFFFFF,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalTrendDown = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsTrendDown[0]
};

static GUI_CONST_STORAGE unsigned char acTrendDown[] = {
  ________, ________,
  ________, ________,
  ________, ________,
  ________, ________,
  ________, ________,
  ________, ________,
  __XXXXXX, XXX_____,
  ___XXXXX, XX______,
  ____XXXX, X_______,
  _____XXX, ________,
  ______X_, ________,
  ________, ________,
  ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmTrendDown = {
 13, /* XSize */
 13, /* YSize */
 2, /* BytesPerLine */
 1, /* BitsPerPixel */
 acTrendDown,  /* Pointer to picture data (indices) */
 &PalTrendDown  /* Pointer to palette */
};

/* *** End of file *** */
