/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: VerticalFlowAnimation
  Dimensions:  35 * 20
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsVerticalFlowAnimation[] = {
     0x000000,0xFFFFFF
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalVerticalFlowAnimation = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsVerticalFlowAnimation[0]
};

static GUI_CONST_STORAGE unsigned char acVerticalFlowAnimation[] = {
  ________, __XXXXXX, XXXXXXXX, X_______, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________,
  XXXXXXXX, XXXXXXX_, ________, ________, ________,
  XXXXXXXX, XX______, ________, _XXXXX__, ________,
  XXXXX___, ________, ____XXXX, XXXXXX__, ________,
  ________, _______X, XXXXXXXX, XXXXXX__, ________,
  ________, __XXXXXX, XXXXXXXX, X_______, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________,
  XXXXXXXX, XXXXXXX_, ________, ________, ________,
  XXXXXXXX, XX______, ________, _XXXXX__, ________,
  XXXXX___, ________, ____XXXX, XXXXXX__, ________,
  ________, _______X, XXXXXXXX, XXXXXX__, ________,
  ________, __XXXXXX, XXXXXXXX, X_______, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________,
  XXXXXXXX, XXXXXXX_, ________, ________, ________,
  XXXXXXXX, XX______, ________, _XXXXX__, ________,
  XXXXX___, ________, ____XXXX, XXXXXX__, ________,
  ________, _______X, XXXXXXXX, XXXXXX__, ________,
  ________, __XXXXXX, XXXXXXXX, X_______, ________,
  _____XXX, XXXXXXXX, XXXX____, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmVerticalFlowAnimation = {
 35, /* XSize */
 20, /* YSize */
 5, /* BytesPerLine */
 1, /* BitsPerPixel */
 acVerticalFlowAnimation,  /* Pointer to picture data (indices) */
 &PalVerticalFlowAnimation  /* Pointer to palette */
};

/* *** End of file *** */
