/*
  C-file generated by Bitmap converter for emWin GSC V3.74, compiled Dec 19 2003, 12:45:08

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: Warning
  Dimensions:  16 * 16
  NumColors:   3
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsWarning[] = {
     0xFFFFFF,0x808080,0x000000
};

GUI_CONST_STORAGE GUI_LOGPALETTE PalWarning = {
  3,	/* number of entries */
  0, 	/* No transparency */
  &ColorsWarning[0]
};

static GUI_CONST_STORAGE unsigned char acWarning[] = {
  0x00, 0x06, 0x90, 0x00,
  0x00, 0x08, 0x20, 0x00,
  0x00, 0x20, 0x08, 0x00,
  0x00, 0x20, 0x08, 0x00,
  0x00, 0x82, 0x82, 0x00,
  0x00, 0x82, 0x82, 0x00,
  0x02, 0x02, 0x80, 0x80,
  0x02, 0x02, 0x80, 0x80,
  0x08, 0x02, 0x40, 0x20,
  0x08, 0x02, 0x00, 0x20,
  0x20, 0x00, 0x00, 0x08,
  0x60, 0x02, 0x80, 0x08,
  0x90, 0x02, 0x80, 0x06,
  0x60, 0x00, 0x00, 0x09,
  0x1A, 0xAA, 0xAA, 0xA4,
  0x05, 0x55, 0x55, 0x50
};

GUI_CONST_STORAGE GUI_BITMAP bmWarning = {
 16, /* XSize */
 16, /* YSize */
 4, /* BytesPerLine */
 2, /* BitsPerPixel */
 acWarning,  /* Pointer to picture data (indices) */
 &PalWarning  /* Pointer to palette */
};

/* *** End of file *** */
