/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __AJAX_JS_H__
#define __AJAX_JS_H__

#define AJAX_JS_SIZE 3653
extern unsigned char AJAX_JS_DATA[];

#endif
