/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __BACKGROUND_JPG_H__
#define __BACKGROUND_JPG_H__

#define BACKGROUND_JPG_SIZE 687
extern unsigned char BACKGROUND_JPG_DATA[];

#endif
