/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __BOTTOM_BANNER_JPG_H__
#define __BOTTOM_BANNER_JPG_H__

#define BOTTOM_BANNER_JPG_SIZE 24579
extern unsigned char BOTTOM_BANNER_JPG_DATA[];

#endif
