/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __FAVICON_ICO_H__
#define __FAVICON_ICO_H__

#define FAVICON_ICO_SIZE 4710
extern unsigned char FAVICON_ICO_DATA[];

#endif
