/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __FIRMWARE_UPDATE_HTML_H__
#define __FIRMWARE_UPDATE_HTML_H__

#define FIRMWARE_UPDATE_HTML_SIZE 2013
extern unsigned char FIRMWARE_UPDATE_HTML_DATA[];

#endif
