/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __INDEX_HTML_H__
#define __INDEX_HTML_H__

#define INDEX_HTML_SIZE 1650
extern unsigned char INDEX_HTML_DATA[];

#endif
