/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __IOSTATUS_HTML_H__
#define __IOSTATUS_HTML_H__

#define IOSTATUS_HTML_SIZE 2489
extern unsigned char IOSTATUS_HTML_DATA[];

#endif
