/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __IPCONFIG_HTML_H__
#define __IPCONFIG_HTML_H__

#define IPCONFIG_HTML_SIZE 5277
extern unsigned char IPCONFIG_HTML_DATA[];

#endif
