/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __MENU_TITLE_PNG_H__
#define __MENU_TITLE_PNG_H__

#define MENU_TITLE_PNG_SIZE 292
extern unsigned char MENU_TITLE_PNG_DATA[];

#endif
