/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __MENU_SELECTED_JPG_H__
#define __MENU_SELECTED_JPG_H__

#define MENU_SELECTED_JPG_SIZE 4201
extern unsigned char MENU_SELECTED_JPG_DATA[];

#endif
