/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __PWCONFIG_HTML_H__
#define __PWCONFIG_HTML_H__

#define PWCONFIG_HTML_SIZE 3124
extern unsigned char PWCONFIG_HTML_DATA[];

#endif
