/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __SCRIPT_JS_H__
#define __SCRIPT_JS_H__

#define SCRIPT_JS_SIZE 2553
extern unsigned char SCRIPT_JS_DATA[];

#endif
