/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __STYLE_CSS_H__
#define __STYLE_CSS_H__

#define STYLE_CSS_SIZE 3711
extern unsigned char STYLE_CSS_DATA[];

#endif
