/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
#ifndef __TOP_BANNER_JPG_H__
#define __TOP_BANNER_JPG_H__

#define TOP_BANNER_JPG_SIZE 44885
extern unsigned char TOP_BANNER_JPG_DATA[];

#endif
