/**************************************************************************
 This file is generated by WebPageGenerator
**************************************************************************/
/**************************************************************************
 SYSTEM INCLUDES
**************************************************************************/
#include "sock.h"
#include "rtip.h"
#include "mfapi.h"
#include "webapi.h"
/**************************************************************************
 LOCAL INCLUDES
**************************************************************************/
#include "ajax_js.h"
#include "background_jpg.h"
#include "bottom_banner_jpg.h"
#include "cu351viewer_jar.h"
#include "favicon_ico.h"
#include "firmware_update_html.h"
#include "index_html.h"
#include "iostatus_html.h"
#include "ipconfig_html.h"
#include "menu_selected_jpg.h"
#include "menu_title_png.h"
#include "pwconfig_html.h"
#include "script_js.h"
#include "style_css.h"
#include "top_banner_jpg.h"
/**************************************************************************
 EXTERNS
**************************************************************************/
const char* WEBPAGES_PROTECTED_FILES[] = {
  "get.cgi"
  ,"post.cgi"
  ,"firmware_update.html"
  ,"index.html"
  ,"iostatus.html"
  ,"ipconfig.html"
  ,"pwconfig.html"
};
/**************************************************************************
 LOCAL VARIABLES
**************************************************************************/
static MFBLOCK ajax_js;
static MFBLOCK background_jpg;
static MFBLOCK bottom_banner_jpg;
static MFBLOCK cu351viewer_jar;
static MFBLOCK favicon_ico;
static MFBLOCK firmware_update_html;
static MFBLOCK index_html;
static MFBLOCK iostatus_html;
static MFBLOCK ipconfig_html;
static MFBLOCK menu_selected_jpg;
static MFBLOCK menu_title_png;
static MFBLOCK pwconfig_html;
static MFBLOCK script_js;
static MFBLOCK style_css;
static MFBLOCK top_banner_jpg;
/**************************************************************************
 PUBLIC FUNCTIONS
**************************************************************************/
int http_file_init(void)
{
  int fd;

  vf_init();

  ajax_js.blsize = AJAX_JS_SIZE;
  ajax_js.data = AJAX_JS_DATA;
  fd = mf_open("ajax.js", VO_CREAT, VS_IREAD);
  mf_build(fd, &ajax_js, AJAX_JS_SIZE);
  mf_close(fd);

  background_jpg.blsize = BACKGROUND_JPG_SIZE;
  background_jpg.data = BACKGROUND_JPG_DATA;
  fd = mf_open("background.jpg", VO_CREAT, VS_IREAD);
  mf_build(fd, &background_jpg, BACKGROUND_JPG_SIZE);
  mf_close(fd);

  bottom_banner_jpg.blsize = BOTTOM_BANNER_JPG_SIZE;
  bottom_banner_jpg.data = BOTTOM_BANNER_JPG_DATA;
  fd = mf_open("bottom_banner.jpg", VO_CREAT, VS_IREAD);
  mf_build(fd, &bottom_banner_jpg, BOTTOM_BANNER_JPG_SIZE);
  mf_close(fd);

  cu351viewer_jar.blsize = CU351VIEWER_JAR_SIZE;
  cu351viewer_jar.data = CU351VIEWER_JAR_DATA;
  fd = mf_open("cu351viewer.jar", VO_CREAT, VS_IREAD);
  mf_build(fd, &cu351viewer_jar, CU351VIEWER_JAR_SIZE);
  mf_close(fd);

  favicon_ico.blsize = FAVICON_ICO_SIZE;
  favicon_ico.data = FAVICON_ICO_DATA;
  fd = mf_open("favicon.ico", VO_CREAT, VS_IREAD);
  mf_build(fd, &favicon_ico, FAVICON_ICO_SIZE);
  mf_close(fd);

  firmware_update_html.blsize = FIRMWARE_UPDATE_HTML_SIZE;
  firmware_update_html.data = FIRMWARE_UPDATE_HTML_DATA;
  fd = mf_open("firmware_update.html", VO_CREAT, VS_IREAD);
  mf_build(fd, &firmware_update_html, FIRMWARE_UPDATE_HTML_SIZE);
  mf_close(fd);

  index_html.blsize = INDEX_HTML_SIZE;
  index_html.data = INDEX_HTML_DATA;
  fd = mf_open("index.html", VO_CREAT, VS_IREAD);
  mf_build(fd, &index_html, INDEX_HTML_SIZE);
  mf_close(fd);

  iostatus_html.blsize = IOSTATUS_HTML_SIZE;
  iostatus_html.data = IOSTATUS_HTML_DATA;
  fd = mf_open("iostatus.html", VO_CREAT, VS_IREAD);
  mf_build(fd, &iostatus_html, IOSTATUS_HTML_SIZE);
  mf_close(fd);

  ipconfig_html.blsize = IPCONFIG_HTML_SIZE;
  ipconfig_html.data = IPCONFIG_HTML_DATA;
  fd = mf_open("ipconfig.html", VO_CREAT, VS_IREAD);
  mf_build(fd, &ipconfig_html, IPCONFIG_HTML_SIZE);
  mf_close(fd);

  menu_selected_jpg.blsize = MENU_SELECTED_JPG_SIZE;
  menu_selected_jpg.data = MENU_SELECTED_JPG_DATA;
  fd = mf_open("menu_selected.jpg", VO_CREAT, VS_IREAD);
  mf_build(fd, &menu_selected_jpg, MENU_SELECTED_JPG_SIZE);
  mf_close(fd);

  menu_title_png.blsize = MENU_TITLE_PNG_SIZE;
  menu_title_png.data = MENU_TITLE_PNG_DATA;
  fd = mf_open("menu_title.png", VO_CREAT, VS_IREAD);
  mf_build(fd, &menu_title_png, MENU_TITLE_PNG_SIZE);
  mf_close(fd);

  pwconfig_html.blsize = PWCONFIG_HTML_SIZE;
  pwconfig_html.data = PWCONFIG_HTML_DATA;
  fd = mf_open("pwconfig.html", VO_CREAT, VS_IREAD);
  mf_build(fd, &pwconfig_html, PWCONFIG_HTML_SIZE);
  mf_close(fd);

  script_js.blsize = SCRIPT_JS_SIZE;
  script_js.data = SCRIPT_JS_DATA;
  fd = mf_open("script.js", VO_CREAT, VS_IREAD);
  mf_build(fd, &script_js, SCRIPT_JS_SIZE);
  mf_close(fd);

  style_css.blsize = STYLE_CSS_SIZE;
  style_css.data = STYLE_CSS_DATA;
  fd = mf_open("style.css", VO_CREAT, VS_IREAD);
  mf_build(fd, &style_css, STYLE_CSS_SIZE);
  mf_close(fd);

  top_banner_jpg.blsize = TOP_BANNER_JPG_SIZE;
  top_banner_jpg.data = TOP_BANNER_JPG_DATA;
  fd = mf_open("top_banner.jpg", VO_CREAT, VS_IREAD);
  mf_build(fd, &top_banner_jpg, TOP_BANNER_JPG_SIZE);
  mf_close(fd);
  return 1;
}
