/**************************************************************************
 This file is auto-generated by FactoryGenerator, do not modify it manually
**************************************************************************/

#ifndef __GENI_APP_IF_DATA_H__
#define __GENI_APP_IF_DATA_H__

/**************************************************************************
 SYSTEM INCLUDES
**************************************************************************/

/**************************************************************************
 PROJECT INCLUDES
**************************************************************************/
#include <cu351_cpu_types.h>

/**************************************************************************
 LOCAL INCLUDES
**************************************************************************/

/**************************************************************************
 TYPE DEFINES
**************************************************************************/
typedef enum
{
  GAI_CMD_RESET = 1,  // 1 Reset (reboot)
  GAI_CMD_ALARM_RESET = 2,  // 2 alarm_reset
  GAI_CMD_INTERLOCK_PIT = 5,  // 5 interlock_pit (stop all pumping)
  GAI_CMD_AUTO_PIT = 6,  // 6 Pit controlled by automation
  GAI_CMD_DISABLE_TEST_MODE = 19,  // 19 disable_test_mode
  GAI_CMD_ENABLE_TEST_MODE = 20,  // 20 enable_test_mode
  GAI_CMD_FILL_SIMULATED_LOG_DATA = 21,  // 21 For test of datalog. Not in profile
  GAI_CMD_RESET_HIST = 36,  // 36 Resetter hele log blokken i Flash
  GAI_CMD_RESET_EVENT_LOG = 51,  // 51 reset_event_log and reset alarm_log
  GAI_CMD_STOP_P1 = 60,  // 60 STOP_P1
  GAI_CMD_START_P1 = 61,  // 61 START_P1
  GAI_CMD_AUTO_P1 = 62,  // 62 AUTO_P1
  GAI_CMD_STOP_P2 = 63,  // 63 STOP_P2
  GAI_CMD_START_P2 = 64,  // 64 START_P2
  GAI_CMD_AUTO_P2 = 65,  // 65 AUTO_P2
  GAI_CMD_STOP_P3 = 66,  // 66 STOP_P3
  GAI_CMD_START_P3 = 67,  // 67 START_P3
  GAI_CMD_AUTO_P3 = 68,  // 68 AUTO_P3
  GAI_CMD_STOP_P4 = 69,  // 69 STOP_P4
  GAI_CMD_START_P4 = 70,  // 70 START_P4
  GAI_CMD_AUTO_P4 = 71,  // 71 AUTO_P4
  GAI_CMD_STOP_P5 = 72,  // 72 STOP_P5
  GAI_CMD_START_P5 = 73,  // 73 START_P5
  GAI_CMD_AUTO_P5 = 74,  // 74 AUTO_P5
  GAI_CMD_STOP_P6 = 75,  // 75 STOP_P6
  GAI_CMD_START_P6 = 76,  // 76 START_P6
  GAI_CMD_AUTO_P6 = 77,  // 77 AUTO_P6
  GAI_CMD_CUSTOM_RELAY_ON = 78,  // 78 Activate cutsom relay
  GAI_CMD_CUSTOM_RELAY_OFF = 79,  // 79 Deactivate custom relay
  GAI_CMD_CUSTOM_RELAY_PULSE = 80,  // 80 Generates a 1s pulse
  GAI_CMD_RESET_USER_DEF_CNT_1 = 81,  // 81 reset user defined counter 1
  GAI_CMD_RESET_USER_DEF_CNT_2 = 82,  // 82 reset user defined counter 2
  GAI_CMD_RESET_USER_DEF_CNT_3 = 83,  // 83 reset user defined counter 3
  GAI_CMD_RTC_USE_NEW_TIME_EVENT = 102,  // 102 Set real time clock the MPC way
  GAI_CMD_SCADA_CALL_BACK_ACK = 104,  // 104 Acknowledge by command
  GAI_CMD_CALL_BACK_TEST = 105,  // 105 Scada callback test
  GAI_CMD_SPECIFIC_ENERGY_TEST_RUN_P1 = 118,  // 118 Start energy test for pump 1
  GAI_CMD_SPECIFIC_ENERGY_TEST_RUN_P2 = 119,  // 119 Start energy test for pump 2
  GAI_CMD_SPECIFIC_ENERGY_TEST_RUN_P3 = 120,  // 120 Start energy test for pump 3
  GAI_CMD_SPECIFIC_ENERGY_TEST_RUN_P4 = 121,  // 121 Start energy test for pump 4
  GAI_CMD_SPECIFIC_ENERGY_TEST_RUN_P5 = 122,  // 122 Start energy test for pump 5
  GAI_CMD_SPECIFIC_ENERGY_TEST_RUN_P6 = 123,  // 123 Start energy test for pump 6
  GAI_CMD_ACTIVATE_ADVANCED_FLOW_CALC_LEARNING = 124,  // 124 Start advanced flow learning for all pumps
  GAI_CMD_ACTIVATE_ANTIBLOCK_PARAMETER_LEARNING = 125  // 125 Start learning of antiblock 'normal parameters'
} GAI_CMD_TYPE;

typedef enum
{
  GAI_VAR_NO_OF_FLOAT_SWITCHES = 0x0200,  // 2,0 no_of_float_switches
  GAI_VAR_FLOAT_SWITCH_STATUS = 0x0201,  // 2,1 Bit 0-4 eq. float switch 1-5 ; Bit 5 eq. over flow switch
  GAI_VAR_FLOAT_SWITCH_1_FUNC = 0x0202,  // 2,2 float_switch_1_func
  GAI_VAR_FLOAT_SWITCH_2_FUNC = 0x0203,  // 2,3 float_switch_2_func
  GAI_VAR_FLOAT_SWITCH_3_FUNC = 0x0204,  // 2,4 float_switch_3_func
  GAI_VAR_FLOAT_SWITCH_4_FUNC = 0x0205,  // 2,5 float_switch_4_func
  GAI_VAR_FLOAT_SWITCH_5_FUNC = 0x0206,  // 2,6 float_switch_5_func
  GAI_VAR_PIT_SENSORS = 0x0207,  // 2,7 pit_sensors
  GAI_VAR_DAY_CNT_ZERO_TIME = 0x0208,  // 2,8 day_cnt_zero_time
  GAI_VAR_SCADA_PIN_CODE_HI = 0x0209,  // 2,9 scada_pin_code
  GAI_VAR_SCADA_PIN_CODE_LO = 0x020A,  // 2,10 scada_pin_code
  GAI_VAR_SCADA_PIN_CODE_ENABLED = 0x020B,  // 2,11 scada_pin_code_enabled
  GAI_VAR_FIRST_GROUP_2_PUMP = 0x020C,  // 2,12 
  GAI_VAR_SIGNAL_LEVEL_ACT = 0x0219,  // 2,25 
  GAI_VAR_SIGNAL_LEVEL_AVG = 0x021A,  // 2,26 
  GAI_VAR_PIT_OPR_MODE = 0x0247,  // 2,71 pit_opr_mode
  GAI_VAR_PIT_MAIN_STATUS = 0x0248,  // 2,72 pit_main_status, bits
  GAI_VAR_LED_STATUS = 0x0249,  // 2,73 bit10=0: green OFF, bit10=1: green ON; bit10=2: green flashing; bit32=0: red OFF, bit32=1: red ON; bit32=2: red flashing
  GAI_VAR_ALARM_CODE = 0x024A,  // 2,74 alarm_code
  GAI_VAR_WARNING_CODE = 0x024B,  // 2,75 warning_code
  GAI_VAR_BATTERY_VOLTAGE = 0x024C,  // 2,76 
  GAI_VAR_IO_LOGIC_OUTPUTS = 0x024D,  // 2,77 
  GAI_VAR_RTC_YEAR = 0x028C,  // 2,140 rtc_year (since 1900)
  GAI_VAR_RTC_MONTH_OF_YEAR = 0x028D,  // 2,141 rtc_month_of_year
  GAI_VAR_RTC_DAY_OF_MONTH = 0x028E,  // 2,142 rtc_day_of_month
  GAI_VAR_RTC_HOUR = 0x028F,  // 2,143 rtc_hour
  GAI_VAR_RTC_MINUTE = 0x0290,  // 2,144 rtc_minute
  GAI_VAR_RTC_SECOND = 0x0291,  // 2,145 rtc_second
  GAI_VAR_RTC_DAY_OF_WEEK = 0x0292,  // 2,146 rtc_day_of_week
  GAI_VAR_UNIT_FAMILY = 0x0294,  // 2,148 unit_family
  GAI_VAR_UNIT_TYPE = 0x0295,  // 2,149 unit_family
  GAI_VAR_UNIT_VERSION = 0x0296,  // 2,150 unit_version
  GAI_VAR_GSM_CTR = 0x02ED,  // 2,237 gsm_ctr
  GAI_VAR_GSM_SETUP = 0x02EE,  // 2,238 gsm_setup
  GAI_VAR_SMS_OUT_SEQ_NO = 0x02EF,  // 2,239 sms_out_seq_no
  GAI_VAR_VFD_MIN_VELOCITY_FEATURE_ENABLED = 0x02F0,  // 2,240 added for test during development
  GAI_VAR_PRODUCTION_CODE_1 = 0x0400,  // 4,0 production_type_code
  GAI_VAR_PRODUCTION_CODE_2 = 0x0401,  // 4,1 production_type_code
  GAI_VAR_PRODUCTION_CODE_3 = 0x0402,  // 4,2 production_type_code
  GAI_VAR_PRODUCTION_CODE_4 = 0x0403,  // 4,3 production_type_code
  GAI_VAR_PRODUCTION_CODE_5 = 0x0404,  // 4,4 production_rev_date_code
  GAI_VAR_PRODUCTION_CODE_6 = 0x0405,  // 4,5 production_rev_date_code
  GAI_VAR_PRODUCTION_CODE_7 = 0x0406,  // 4,6 production_rev_date_code
  GAI_VAR_PRODUCTION_CODE_8 = 0x0407,  // 4,7 production_serial_no
  GAI_VAR_PRODUCTION_CODE_9 = 0x0408,  // 4,8 production_serial_no
  GAI_VAR_PRODUCTION_CODE_10 = 0x0409,  // 4,9 production_serial_no
  GAI_VAR_MAC_ADDR_0 = 0x0415,  // 4,21 MAC address byte 0 - least significant
  GAI_VAR_MAC_ADDR_1 = 0x0416,  // 4,22 MAC address byte 1
  GAI_VAR_MAC_ADDR_2 = 0x0417,  // 4,23 MAC address byte 2
  GAI_VAR_MAC_ADDR_3 = 0x0418,  // 4,24 MAC address byte 3
  GAI_VAR_MAC_ADDR_4 = 0x0419,  // 4,25 MAC address byte 4
  GAI_VAR_MAC_ADDR_5 = 0x041A,  // 4,26 MAC address byte 5 - most significant
  GAI_VAR_SLAVE_UNIT_ADDRESS = 0x042E,  // 4,46 slave_unit_address
  GAI_VAR_SLAVE_GROUP_ADDRESS = 0x042F,  // 4,47 slave_group_address
  GAI_VAR_BAUD_RATE_DEFAULT = 0x044F,  // 4,79 baud_rate_default
  GAI_VAR_MIN_REPLY_DELAY_DEFAULT = 0x0450,  // 4,80 min_reply_delay_default
  GAI_VAR_GENI_SETUP = 0x0451,  // 4,81 
  GAI_VAR_DEMO_SUITCASE_MODE_ENABLED = 0x0455,  // 4,85 demo_suitcase_mode_enabled
  GAI_VAR_DISPLAY_WIZARD_ENABLE = 0x0456,  // 4,86 Wizard is active if true
  GAI_VAR_PIT_LEVEL_SIM_ENABLED = 0x0457,  // 4,87 pit_level_sim_enabled
  GAI_VAR_ANA_OUT_1_CONF_FUNC = 0x046E,  // 4,110 Analog output 1 config
  GAI_VAR_ANA_OUT_2_CONF_FUNC = 0x046F,  // 4,111 Analog output 2 config
  GAI_VAR_ANA_OUT_3_CONF_FUNC = 0x0470,  // 4,112 Analog output 3 config
  GAI_VAR_ANA_OUT_4_CONF_FUNC = 0x0471,  // 4,113 Analog output 4 config
  GAI_VAR_ANA_OUT_5_CONF_FUNC = 0x0472,  // 4,114 Analog output 5 config
  GAI_VAR_ANA_OUT_6_CONF_FUNC = 0x0473,  // 4,115 Analog output 6 config
  GAI_VAR_CONTROL_MODE_PUMP1 = 0x047A,  // 4,122 pump1 control mode
  GAI_VAR_CONTROL_MODE_PUMP2 = 0x047B,  // 4,123 pump2 control mode
  GAI_VAR_CONTROL_MODE_PUMP3 = 0x047C,  // 4,124 pump3 control mode
  GAI_VAR_CONTROL_MODE_PUMP4 = 0x047D,  // 4,125 pump4 control mode
  GAI_VAR_CONTROL_MODE_PUMP5 = 0x047E,  // 4,126 pump5 control mode
  GAI_VAR_CONTROL_MODE_PUMP6 = 0x047F,  // 4,127 pump6 control mode
  GAI_VAR_PID_FEEDBACK_PUMP1 = 0x0480,  // 4,128 pump1 pid feedback signal
  GAI_VAR_PID_FEEDBACK_PUMP2 = 0x0481,  // 4,129 pump2 pid feedback signal
  GAI_VAR_PID_FEEDBACK_PUMP3 = 0x0482,  // 4,130 pump3 pidfeedback signal
  GAI_VAR_PID_FEEDBACK_PUMP4 = 0x0483,  // 4,131 pump4 pidfeedback signal
  GAI_VAR_PID_FEEDBACK_PUMP5 = 0x0484,  // 4,132 pump5 pidfeedback signal
  GAI_VAR_PID_FEEDBACK_PUMP6 = 0x0485,  // 4,133 pump6 pidfeedback signal
  GAI_VAR_SET_POINT_TYPE_PUMP1 = 0x0486,  // 4,134 pump1 setpoint type
  GAI_VAR_SET_POINT_TYPE_PUMP2 = 0x0487,  // 4,135 pump2 setpoint type
  GAI_VAR_SET_POINT_TYPE_PUMP3 = 0x0488,  // 4,136 pump3 setpoint type
  GAI_VAR_SET_POINT_TYPE_PUMP4 = 0x0489,  // 4,137 pump4 setpoint type
  GAI_VAR_SET_POINT_TYPE_PUMP5 = 0x048A,  // 4,138 pump5 setpoint type
  GAI_VAR_SET_POINT_TYPE_PUMP6 = 0x048B,  // 4,139 pump6 setpoint type
  GAI_VAR_AI_SETPOINT_PUMP1 = 0x048C,  // 4,140 pump1 setpoint(ai)
  GAI_VAR_AI_SETPOINT_PUMP2 = 0x048D,  // 4,141 pump2 setpoint(ai)
  GAI_VAR_AI_SETPOINT_PUMP3 = 0x048E,  // 4,142 pump3 setpoint(ai)
  GAI_VAR_AI_SETPOINT_PUMP4 = 0x048F,  // 4,143 pump4 setpoint(ai)
  GAI_VAR_AI_SETPOINT_PUMP5 = 0x0490,  // 4,144 pump5 setpoint(ai)
  GAI_VAR_AI_SETPOINT_PUMP6 = 0x0491,  // 4,145 pump6 setpoint(ai)
  GAI_VAR_FIXED_SETPOINT_PUMP1 = 0x0492,  // 4,146 pump1 setpoint(fixed)
  GAI_VAR_FIXED_SETPOINT_PUMP2 = 0x0493,  // 4,147 pump2 setpoint(fixed)
  GAI_VAR_FIXED_SETPOINT_PUMP3 = 0x0494,  // 4,148 pump3 setpoint(fixed)
  GAI_VAR_FIXED_SETPOINT_PUMP4 = 0x0495,  // 4,149 pump4 setpoint(fixed)
  GAI_VAR_FIXED_SETPOINT_PUMP5 = 0x0496,  // 4,150 pump5 setpoint(fixed)
  GAI_VAR_FIXED_SETPOINT_PUMP6 = 0x0497,  // 4,151 pump6 setpoint(fixed)
  GAI_VAR_CUSTOM_RELAY = 0x0509,  // 5,9 custom_relay
  GAI_VAR_RTC_YEAR_SET = 0x050A,  // 5,10 Set real time clock the MPC way
  GAI_VAR_RTC_MONTH_SET = 0x050B,  // 5,11 Set real time clock the MPC way
  GAI_VAR_RTC_DAY_SET = 0x050C,  // 5,12 Set real time clock the MPC way
  GAI_VAR_RTC_HOUR_SET = 0x050D,  // 5,13 Set real time clock the MPC way
  GAI_VAR_RTC_MINUTE_SET = 0x050E,  // 5,14 Set real time clock the MPC way
  GAI_VAR_RTC_SECOND_SET = 0x050F,  // 5,15 Set real time clock the MPC way
  GAI_VAR_EVENT_CODE_SIM = 0x0520,  // 5,32 event_code_sim
  GAI_VAR_DEVICE_TYPE_CODE_SIM_ID = 0x0521,  // 5,33 device_type_code_sim_id
  GAI_VAR_DEVICE_NO_SIM_ID = 0x0522,  // 5,34 device_no_sim_id
  GAI_VAR_EVENT_SIM_ACTIVATE = 0x0523,  // 5,35 event_sim_activate
  GAI_VAR_EVENT_SOURCE_SIM = 0x0524,  // 5,36 event_source_sim
  GAI_VAR_EVENT_TYPE_AND_COND_SIM = 0x0525,  // 5,37 event_type_and_cond_sim
  GAI_VAR_SET_MIN_REPLY_DELAY = 0x0526,  // 5,38 set_min_reply_delay
  GAI_VAR_SET_BAUD_RATE = 0x0527,  // 5,39 set_baud_rate
  GAI_VAR_SMS_OUT_SEQ_NO_ACK = 0x052D,  // 5,45 sms_out_seq_no_ack
  GAI_VAR_SIM_CARD_STATUS = 0x0531,  // 5,49 sim_card_status
  GAI_VAR_GSM_STATE = 0x0537,  // 5,55 gsm_state
  GAI_VAR_CIM_HEARTBEAT = 0x0538,  // 5,56 Heartbeat from ciu module, telling that communication is ok
  GAI_VAR_CIM_TYPE = 0x0539,  // 5,57 Type of CIM/CIU connected. A CIM/CIU master writes the value
  GAI_VAR_PIT_WATER_LEVEL = 0x0B00,  // 11,0 Actual pit level
  GAI_VAR_PIT_SWITCH_WATER_LEVEL = 0x0B01,  // 11,1 float_switch_water_level (number)
  GAI_VAR_PIT_DEPTH = 0x0B02,  // 11,2 Pit depth (config)
  GAI_VAR_PIT_ACT_FLOW_IN = 0x0B03,  // 11,3 Flow (TBD)
  GAI_VAR_PIT_AVG_FLOW_IN = 0x0B04,  // 11,4 Flow (TBD)
  GAI_VAR_PIT_ACT_FLOW_OUT = 0x0B05,  // 11,5 Flow (TBD)
  GAI_VAR_PIT_AVG_FLOW_OUT = 0x0B06,  // 11,6 Flow (TBD)
  GAI_VAR_PIT_ENERGY_YESTERDAY = 0x0B07,  // 11,7 pit_energy_yesterday
  GAI_VAR_PIT_ENERGY_TODAY = 0x0B08,  // 11,8 pit_energy_today
  GAI_VAR_PIT_SPECIFIC_ENERGY = 0x0B09,  // 11,9 Efficiency
  GAI_VAR_PIT_PUMPED_VOLUME_YESTERDAY = 0x0B0A,  // 11,10 pit_pumped_volume_yesterday
  GAI_VAR_PIT_PUMPED_VOLUME_TODAY = 0x0B0B,  // 11,11 pit_pumped_volume_today
  GAI_VAR_PIT_2_PUMPS_OPR_TIME_YESTERDAY = 0x0B0C,  // 11,12 pit_2_pumps_opr_time_yesterday
  GAI_VAR_PIT_3_PUMPS_OPR_TIME_YESTERDAY = 0x0B0D,  // 11,13 pit_3_pumps_opr_time_yesterday
  GAI_VAR_PIT_4_PUMPS_OPR_TIME_YESTERDAY = 0x0B0E,  // 11,14 pit_4_pumps_opr_time_yesterday
  GAI_VAR_PIT_5_PUMPS_OPR_TIME_YESTERDAY = 0x0B0F,  // 11,15 pit_5_pumps_opr_time_yesterday
  GAI_VAR_PIT_6_PUMPS_OPR_TIME_YESTERDAY = 0x0B10,  // 11,16 pit_6_pumps_opr_time_yesterday
  GAI_VAR_PIT_2_PUMPS_OPR_TIME_TODAY = 0x0B11,  // 11,17 pit_2_pumps_opr_time_today
  GAI_VAR_PIT_3_PUMPS_OPR_TIME_TODAY = 0x0B12,  // 11,18 pit_3_pumps_opr_time_today
  GAI_VAR_PIT_4_PUMPS_OPR_TIME_TODAY = 0x0B13,  // 11,19 pit_4_pumps_opr_time_today
  GAI_VAR_PIT_5_PUMPS_OPR_TIME_TODAY = 0x0B14,  // 11,20 pit_5_pumps_opr_time_today
  GAI_VAR_PIT_6_PUMPS_OPR_TIME_TODAY = 0x0B15,  // 11,21 pit_6_pumps_opr_time_today
  GAI_VAR_PIT_MIXER_STARTS_PER_H = 0x0B16,  // 11,22 mixer_starts_pr_hour
  GAI_VAR_PIT_OVERFLOW_VOLUME = 0x0B17,  // 11,23 overflow volume
  GAI_VAR_PIT_OVERFLOW_VOLUME_YESTERDAY = 0x0B18,  // 11,24 pit_overflow_volume_yesterday
  GAI_VAR_PIT_OVERFLOW_VOLUME_TODAY = 0x0B19,  // 11,25 pit_overflow_volume_today
  GAI_VAR_PIT_OVERFLOW_TIME = 0x0B1A,  // 11,26 overflow time
  GAI_VAR_PIT_OVERFLOW_TIME_YESTERDAY = 0x0B1B,  // 11,27 pit_overflow_time_yesterday
  GAI_VAR_PIT_OVERFLOW_TIME_TODAY = 0x0B1C,  // 11,28 pit_overflow_time_today
  GAI_VAR_PIT_OVERFLOW_COUNT = 0x0B1D,  // 11,29 overflow_count
  GAI_VAR_PIT_OVERFLOW_CNT_YESTERDAY = 0x0B1E,  // 11,30 pit_overflow_cnt_yesterday
  GAI_VAR_PIT_OVERFLOW_CNT_TODAY = 0x0B1F,  // 11,31 pit_overflow_cnt_today
  GAI_VAR_PIT_PUMP_MODE = 0x0B20,  // 11,32 pit_pump_mode
  GAI_VAR_PIT_PUMP_FAULT = 0x0B21,  // 11,33 pit_pump_fault
  GAI_VAR_PIT_PUMP_MON_FAULT = 0x0B22,  // 11,34 pit_pump_mon_fault
  GAI_VAR_PIT_PUMP_CONN_TYPE = 0x0B23,  // 11,35 pit_pump_conn_type
  GAI_VAR_PIT_PUMP_CTR_SOURCE = 0x0B24,  // 11,36 pit_pump_ctr_source
  GAI_VAR_PIT_ALARMS1 = 0x0B25,  // 11,37 pit_alarms1
  GAI_VAR_PIT_ALARMS2 = 0x0B26,  // 11,38 pit_alarms2
  GAI_VAR_PIT_ALARMS3 = 0x0B27,  // 11,39 pit_alarms3
  GAI_VAR_PIT_WARN1 = 0x0B28,  // 11,40 pit_warn1
  GAI_VAR_PIT_WARN2 = 0x0B29,  // 11,41 pit_warn2
  GAI_VAR_PIT_WARN3 = 0x0B2A,  // 11,42 pit_warn3
  GAI_VAR_EVENT_LOG_LATEST_ID = 0x0B2B,  // 11,43 event_log_latest_id
  GAI_VAR_USER_ANA_IN_1 = 0x0B2D,  // 11,45 user_ana_in_1
  GAI_VAR_USER_ANA_IN_2 = 0x0B2E,  // 11,46 user_ana_in_2
  GAI_VAR_USER_ANA_IN_3 = 0x0B2F,  // 11,47 user_ana_in_3
  GAI_VAR_PIT_RAND_START_LEVEL_BAND = 0x0B30,  // 11,48 
  GAI_VAR_PIT_0_PUMPS_OPR_TIME_YESTERDAY = 0x0B31,  // 11,49 pit_0_pumps_opr_time_yesterday
  GAI_VAR_PIT_1_PUMPS_OPR_TIME_YESTERDAY = 0x0B32,  // 11,50 pit_1_pumps_opr_time_yesterday
  GAI_VAR_PIT_0_PUMPS_OPR_TIME_TODAY = 0x0B33,  // 11,51 pit_0_pumps_opr_time_today
  GAI_VAR_PIT_1_PUMPS_OPR_TIME_TODAY = 0x0B34,  // 11,52 pit_1_pumps_opr_time_today
  GAI_VAR_DISCHARGE_PRESSURE = 0x0B35,  // 11,53 Discharge pressure
  GAI_VAR_PIT_ALARMS4 = 0x0B37,  // 11,55 
  GAI_VAR_PIT_WARN4 = 0x0B38,  // 11,56 
  GAI_VAR_POWER_ON_COUNTER = 0x0B3B,  // 11,59 power_on_counter (not in profile)
  GAI_VAR_P1_OPR_TIME_YESTERDAY = 0x0B3C,  // 11,60 p1_opr_time_yesterday
  GAI_VAR_P1_OPR_TIME_TODAY = 0x0B3D,  // 11,61 p1_opr_time_today
  GAI_VAR_P1_LATEST_RUNTIME = 0x0B3E,  // 11,62 pump_1_latest_runtime
  GAI_VAR_P1_START_CNT_YESTERDAY = 0x0B3F,  // 11,63 p1_start_cnt_yesterday
  GAI_VAR_P1_START_CNT_TODAY = 0x0B40,  // 11,64 p1_start_cnt_today
  GAI_VAR_P1_STARTS_PR_HOUR = 0x0B41,  // 11,65 pump_1_starts_pr_hour
  GAI_VAR_P1_FLOW = 0x0B42,  // 11,66 pump_1_calculated_flow_filtered
  GAI_VAR_P1_LATEST_FLOW = 0x0B43,  // 11,67 pump_1_calculated_flow_raw
  GAI_VAR_P1_CURRENT = 0x0B44,  // 11,68 
  GAI_VAR_P1_LATEST_CURRENT = 0x0B45,  // 11,69 p1_latest_current
  GAI_VAR_P1_INSULATION = 0x0B46,  // 11,70 
  GAI_VAR_P1_WATER_IN_OIL = 0x0B47,  // 11,71 pump_1_water_in_oil
  GAI_VAR_P1_MOTOR_TEMP1 = 0x0B48,  // 11,72 pump_1_temperature
  GAI_VAR_P1_COSINE_PHI = 0x0B4A,  // 11,74 
  GAI_VAR_P1_FREQ = 0x0B4B,  // 11,75 
  GAI_VAR_P1_MODE_AND_CONNECT = 0x0B4C,  // 11,76 p1_mode_and_connect
  GAI_VAR_P1_ALARMS1 = 0x0B4D,  // 11,77 p1_alarms1
  GAI_VAR_P1_ALARMS2 = 0x0B4E,  // 11,78 p1_alarms2
  GAI_VAR_P1_ALARMS3 = 0x0B4F,  // 11,79 p1_alarms3
  GAI_VAR_P1_WARN1 = 0x0B50,  // 11,80 p1_warn1
  GAI_VAR_P1_WARN2 = 0x0B51,  // 11,81 p1_warn2
  GAI_VAR_P1_WARN3 = 0x0B52,  // 11,82 p1_warn3
  GAI_VAR_P1_VOLTAGE = 0x0B53,  // 11,83 
  GAI_VAR_P1_VFD_MODE = 0x0B55,  // 11,85 
  GAI_VAR_P1_TORQUE = 0x0B56,  // 11,86 
  GAI_VAR_P1_I_ASYM = 0x0B57,  // 11,87 
  GAI_VAR_P1_ALARMS4 = 0x0B58,  // 11,88 p1_alarms4
  GAI_VAR_P1_WARN4 = 0x0B59,  // 11,89 p1_warn4
  GAI_VAR_P2_OPR_TIME_YESTERDAY = 0x0B5A,  // 11,90 p2_opr_time_yesterday
  GAI_VAR_P2_OPR_TIME_TODAY = 0x0B5B,  // 11,91 p2_opr_time_today
  GAI_VAR_P2_LATEST_RUNTIME = 0x0B5C,  // 11,92 pump_2_latest_runtime
  GAI_VAR_P2_START_CNT_YESTERDAY = 0x0B5D,  // 11,93 p2_start_cnt_yesterday
  GAI_VAR_P2_START_CNT_TODAY = 0x0B5E,  // 11,94 p2_start_cnt_today
  GAI_VAR_P2_STARTS_PR_HOUR = 0x0B5F,  // 11,95 pump_2_starts_pr_hour
  GAI_VAR_P2_FLOW = 0x0B60,  // 11,96 pump_2_calculated_flow_filtered
  GAI_VAR_P2_LATEST_FLOW = 0x0B61,  // 11,97 pump_2_calculated_flow_raw
  GAI_VAR_P2_CURRENT = 0x0B62,  // 11,98 
  GAI_VAR_P2_LATEST_CURRENT = 0x0B63,  // 11,99 p2_latest_current
  GAI_VAR_P2_INSULATION = 0x0B64,  // 11,100 
  GAI_VAR_P2_WATER_IN_OIL = 0x0B65,  // 11,101 pump_2_water_in_oil
  GAI_VAR_P2_MOTOR_TEMP = 0x0B66,  // 11,102 pump_2_temperature
  GAI_VAR_P2_COSINE_PHI = 0x0B68,  // 11,104 
  GAI_VAR_P2_FREQ = 0x0B69,  // 11,105 
  GAI_VAR_P2_MODE_AND_CONNECT = 0x0B6A,  // 11,106 p2_mode_and_connect
  GAI_VAR_P2_ALARMS1 = 0x0B6B,  // 11,107 p2_alarms1
  GAI_VAR_P2_ALARMS2 = 0x0B6C,  // 11,108 p2_alarms2
  GAI_VAR_P2_ALARMS3 = 0x0B6D,  // 11,109 p2_alarms3
  GAI_VAR_P2_WARN1 = 0x0B6E,  // 11,110 p2_warn1
  GAI_VAR_P2_WARN2 = 0x0B6F,  // 11,111 p2_warn2
  GAI_VAR_P2_WARN3 = 0x0B70,  // 11,112 p2_warn3
  GAI_VAR_P2_VOLTAGE = 0x0B71,  // 11,113 
  GAI_VAR_P2_VFD_MODE = 0x0B73,  // 11,115 
  GAI_VAR_P2_TORQUE = 0x0B74,  // 11,116 
  GAI_VAR_P2_I_ASYM = 0x0B75,  // 11,117 
  GAI_VAR_P2_ALARMS4 = 0x0B76,  // 11,118 p2_alarms4
  GAI_VAR_P2_WARN4 = 0x0B77,  // 11,119 p2_warn4
  GAI_VAR_P3_OPR_TIME_YESTERDAY = 0x0B78,  // 11,120 p3_opr_time_yesterday
  GAI_VAR_P3_OPR_TIME_TODAY = 0x0B79,  // 11,121 p3_opr_time_today
  GAI_VAR_P3_LATEST_RUNTIME = 0x0B7A,  // 11,122 pump_3_latest_runtime
  GAI_VAR_P3_START_CNT_YESTERDAY = 0x0B7B,  // 11,123 p3_start_cnt_yesterday
  GAI_VAR_P3_START_CNT_TODAY = 0x0B7C,  // 11,124 p3_start_cnt_today
  GAI_VAR_P3_STARTS_PR_HOUR = 0x0B7D,  // 11,125 pump_3_starts_pr_hour
  GAI_VAR_P3_FLOW = 0x0B7E,  // 11,126 pump_3_calculated_flow_filtered
  GAI_VAR_P3_LATEST_FLOW = 0x0B7F,  // 11,127 pump_3_calculated_flow_raw
  GAI_VAR_P3_CURRENT = 0x0B80,  // 11,128 
  GAI_VAR_P3_LATEST_CURRENT = 0x0B81,  // 11,129 p3_latest_current
  GAI_VAR_P3_INSULATION = 0x0B82,  // 11,130 
  GAI_VAR_P3_WATER_IN_OIL = 0x0B83,  // 11,131 pump_3_water_in_oil
  GAI_VAR_P3_MOTOR_TEMP = 0x0B84,  // 11,132 pump_3_temperature
  GAI_VAR_P3_COSINE_PHI = 0x0B86,  // 11,134 
  GAI_VAR_P3_FREQ = 0x0B87,  // 11,135 
  GAI_VAR_P3_MODE_AND_CONNECT = 0x0B88,  // 11,136 p3_mode_and_connect
  GAI_VAR_P3_ALARMS1 = 0x0B89,  // 11,137 p3_alarms1
  GAI_VAR_P3_ALARMS2 = 0x0B8A,  // 11,138 p3_alarms2
  GAI_VAR_P3_ALARMS3 = 0x0B8B,  // 11,139 p3_alarms3
  GAI_VAR_P3_WARN1 = 0x0B8C,  // 11,140 p3_warn1
  GAI_VAR_P3_WARN2 = 0x0B8D,  // 11,141 p3_warn2
  GAI_VAR_P3_WARN3 = 0x0B8E,  // 11,142 p3_warn3
  GAI_VAR_P3_VOLTAGE = 0x0B8F,  // 11,143 
  GAI_VAR_P3_VFD_MODE = 0x0B91,  // 11,145 
  GAI_VAR_P3_TORQUE = 0x0B92,  // 11,146 
  GAI_VAR_P3_I_ASYM = 0x0B93,  // 11,147 
  GAI_VAR_P3_ALARMS4 = 0x0B94,  // 11,148 p3_alarms4
  GAI_VAR_P3_WARN4 = 0x0B95,  // 11,149 p3_warn4
  GAI_VAR_P4_OPR_TIME_YESTERDAY = 0x0B96,  // 11,150 p4_opr_time_yesterday
  GAI_VAR_P4_OPR_TIME_TODAY = 0x0B97,  // 11,151 p4_opr_time_today
  GAI_VAR_P4_LATEST_RUNTIME = 0x0B98,  // 11,152 pump_4_latest_runtime
  GAI_VAR_P4_START_CNT_YESTERDAY = 0x0B99,  // 11,153 p4_start_cnt_yesterday
  GAI_VAR_P4_START_CNT_TODAY = 0x0B9A,  // 11,154 p4_start_cnt_today
  GAI_VAR_P4_STARTS_PR_HOUR = 0x0B9B,  // 11,155 pump_4_starts_pr_hour
  GAI_VAR_P4_FLOW = 0x0B9C,  // 11,156 pump_4_calculated_flow_filtered
  GAI_VAR_P4_LATEST_FLOW = 0x0B9D,  // 11,157 pump_4_calculated_flow_raw
  GAI_VAR_P4_CURRENT = 0x0B9E,  // 11,158 
  GAI_VAR_P4_LATEST_CURRENT = 0x0B9F,  // 11,159 p4_latest_current
  GAI_VAR_P4_INSULATION = 0x0BA0,  // 11,160 
  GAI_VAR_P4_WATER_IN_OIL = 0x0BA1,  // 11,161 pump_4_water_in_oil
  GAI_VAR_P4_MOTOR_TEMP = 0x0BA2,  // 11,162 pump_4_temperature
  GAI_VAR_P4_COSINE_PHI = 0x0BA4,  // 11,164 
  GAI_VAR_P4_FREQ = 0x0BA5,  // 11,165 
  GAI_VAR_P4_MODE_AND_CONNECT = 0x0BA6,  // 11,166 p4_mode_and_connect
  GAI_VAR_P4_ALARMS1 = 0x0BA7,  // 11,167 p4_alarms1
  GAI_VAR_P4_ALARMS2 = 0x0BA8,  // 11,168 p4_alarms2
  GAI_VAR_P4_ALARMS3 = 0x0BA9,  // 11,169 p4_alarms3
  GAI_VAR_P4_WARN1 = 0x0BAA,  // 11,170 p4_warn1
  GAI_VAR_P4_WARN2 = 0x0BAB,  // 11,171 p4_warn2
  GAI_VAR_P4_WARN3 = 0x0BAC,  // 11,172 p4_warn3
  GAI_VAR_P4_VOLTAGE = 0x0BAD,  // 11,173 
  GAI_VAR_P4_VFD_MODE = 0x0BAF,  // 11,175 
  GAI_VAR_P4_TORQUE = 0x0BB0,  // 11,176 
  GAI_VAR_P4_I_ASYM = 0x0BB1,  // 11,177 
  GAI_VAR_P4_ALARMS4 = 0x0BB2,  // 11,178 p4_alarms4
  GAI_VAR_P4_WARN4 = 0x0BB3,  // 11,179 p4_warn4
  GAI_VAR_P5_OPR_TIME_YESTERDAY = 0x0BB4,  // 11,180 p5_opr_time_yesterday
  GAI_VAR_P5_OPR_TIME_TODAY = 0x0BB5,  // 11,181 p5_opr_time_today
  GAI_VAR_P5_LATEST_RUNTIME = 0x0BB6,  // 11,182 pump_5_latest_runtime
  GAI_VAR_P5_START_CNT_YESTERDAY = 0x0BB7,  // 11,183 p5_start_cnt_yesterday
  GAI_VAR_P5_START_CNT_TODAY = 0x0BB8,  // 11,184 p5_start_cnt_today
  GAI_VAR_P5_STARTS_PR_HOUR = 0x0BB9,  // 11,185 pump_5_starts_pr_hour
  GAI_VAR_P5_FLOW = 0x0BBA,  // 11,186 pump_5_calculated_flow_filtered
  GAI_VAR_P5_LATEST_FLOW = 0x0BBB,  // 11,187 pump_5_calculated_flow_raw
  GAI_VAR_P5_CURRENT = 0x0BBC,  // 11,188 
  GAI_VAR_P5_LATEST_CURRENT = 0x0BBD,  // 11,189 p5_latest_current
  GAI_VAR_P5_INSULATION = 0x0BBE,  // 11,190 
  GAI_VAR_P5_WATER_IN_OIL = 0x0BBF,  // 11,191 pump_5_water_in_oil
  GAI_VAR_P5_MOTOR_TEMP = 0x0BC0,  // 11,192 pump_5_temperature
  GAI_VAR_P5_COSINE_PHI = 0x0BC2,  // 11,194 
  GAI_VAR_P5_FREQ = 0x0BC3,  // 11,195 
  GAI_VAR_P5_MODE_AND_CONNECT = 0x0BC4,  // 11,196 p5_mode_and_connect
  GAI_VAR_P5_ALARMS1 = 0x0BC5,  // 11,197 p5_alarms1
  GAI_VAR_P5_ALARMS2 = 0x0BC6,  // 11,198 p5_alarms2
  GAI_VAR_P5_ALARMS3 = 0x0BC7,  // 11,199 p5_alarms3
  GAI_VAR_P5_WARN1 = 0x0BC8,  // 11,200 p5_warn1
  GAI_VAR_P5_WARN2 = 0x0BC9,  // 11,201 p5_warn2
  GAI_VAR_P5_WARN3 = 0x0BCA,  // 11,202 p5_warn3
  GAI_VAR_P5_VOLTAGE = 0x0BCB,  // 11,203 
  GAI_VAR_P5_VFD_MODE = 0x0BCD,  // 11,205 
  GAI_VAR_P5_TORQUE = 0x0BCE,  // 11,206 
  GAI_VAR_P5_I_ASYM = 0x0BCF,  // 11,207 
  GAI_VAR_P5_ALARMS4 = 0x0BD0,  // 11,208 p5_alarms4
  GAI_VAR_P5_WARN4 = 0x0BD1,  // 11,209 p5_warn4
  GAI_VAR_P6_OPR_TIME_YESTERDAY = 0x0BD2,  // 11,210 p6_opr_time_yesterday
  GAI_VAR_P6_OPR_TIME_TODAY = 0x0BD3,  // 11,211 p6_opr_time_today
  GAI_VAR_P6_LATEST_RUNTIME = 0x0BD4,  // 11,212 pump_6_latest_runtime
  GAI_VAR_P6_START_CNT_YESTERDAY = 0x0BD5,  // 11,213 p6_start_cnt_yesterday
  GAI_VAR_P6_START_CNT_TODAY = 0x0BD6,  // 11,214 p6_start_cnt_today
  GAI_VAR_P6_STARTS_PR_HOUR = 0x0BD7,  // 11,215 pump_6_starts_pr_hour
  GAI_VAR_P6_FLOW = 0x0BD8,  // 11,216 pump_6_calculated_flow_filtered
  GAI_VAR_P6_LATEST_FLOW = 0x0BD9,  // 11,217 pump_6_calculated_flow_raw
  GAI_VAR_P6_CURRENT = 0x0BDA,  // 11,218 
  GAI_VAR_P6_LATEST_CURRENT = 0x0BDB,  // 11,219 p6_latest_current
  GAI_VAR_P6_INSULATION = 0x0BDC,  // 11,220 
  GAI_VAR_P6_WATER_IN_OIL = 0x0BDD,  // 11,221 pump_6_water_in_oil
  GAI_VAR_P6_MOTOR_TEMP = 0x0BDE,  // 11,222 pump_6_temperature
  GAI_VAR_P6_COSINE_PHI = 0x0BE0,  // 11,224 
  GAI_VAR_P6_FREQ = 0x0BE1,  // 11,225 
  GAI_VAR_P6_MODE_AND_CONNECT = 0x0BE2,  // 11,226 p6_mode_and_connect
  GAI_VAR_P6_ALARMS1 = 0x0BE3,  // 11,227 p6_alarms1
  GAI_VAR_P6_ALARMS2 = 0x0BE4,  // 11,228 p6_alarms2
  GAI_VAR_P6_ALARMS3 = 0x0BE5,  // 11,229 p6_alarms3
  GAI_VAR_P6_WARN1 = 0x0BE6,  // 11,230 p6_warn1
  GAI_VAR_P6_WARN2 = 0x0BE7,  // 11,231 p6_warn2
  GAI_VAR_P6_WARN3 = 0x0BE8,  // 11,232 p6_warn3
  GAI_VAR_P6_VOLTAGE = 0x0BE9,  // 11,233 
  GAI_VAR_P6_VFD_MODE = 0x0BEB,  // 11,235 
  GAI_VAR_P6_TORQUE = 0x0BEC,  // 11,236 
  GAI_VAR_P6_I_ASYM = 0x0BED,  // 11,237 
  GAI_VAR_P6_ALARMS4 = 0x0BEE,  // 11,238 p6_alarms4
  GAI_VAR_P6_WARN4 = 0x0BEF,  // 11,239 p6_warn4
  GAI_VAR_CLASS_11_DUMMY_1 = 0x0BFB,  // 11,251 Dummy par, used for debug
  GAI_VAR_CLASS_11_DUMMY_2 = 0x0BFC,  // 11,252 Dummy par, used for debug
  GAI_VAR_CLASS_11_DUMMY_3 = 0x0BFD,  // 11,253 Dummy par, used for debug
  GAI_VAR_OVERFLOW_LEVEL = 0x0C00,  // 12,0 overflow_alarm_level
  GAI_VAR_HIGH_LEVEL = 0x0C01,  // 12,1 high_level_alarm_level
  GAI_VAR_ALARM_LEVEL = 0x0C02,  // 12,2 level_alarm_alarm_level
  GAI_VAR_DRY_RUNNING_LEVEL = 0x0C03,  // 12,3 dry_running_alarm_level
  GAI_VAR_FOAM_DRAIN_LEVEL = 0x0C04,  // 12,4 foam_drain_level
  GAI_VAR_START_LEVEL_P1 = 0x0C05,  // 12,5 start_level_pump_1
  GAI_VAR_START_LEVEL_P2 = 0x0C06,  // 12,6 start_level_pump_2
  GAI_VAR_START_LEVEL_P3 = 0x0C07,  // 12,7 start_level_pump_3
  GAI_VAR_START_LEVEL_P4 = 0x0C08,  // 12,8 start_level_pump_4
  GAI_VAR_START_LEVEL_P5 = 0x0C09,  // 12,9 start_level_pump_5
  GAI_VAR_START_LEVEL_P6 = 0x0C0A,  // 12,10 start_level_pump_6
  GAI_VAR_STOP_LEVEL_P1 = 0x0C0B,  // 12,11 stop_level_pump_1
  GAI_VAR_STOP_LEVEL_P2 = 0x0C0C,  // 12,12 stop_level_pump_2
  GAI_VAR_STOP_LEVEL_P3 = 0x0C0D,  // 12,13 stop_level_pump_3
  GAI_VAR_STOP_LEVEL_P4 = 0x0C0E,  // 12,14 stop_level_pump_4
  GAI_VAR_STOP_LEVEL_P5 = 0x0C0F,  // 12,15 stop_level_pump_5
  GAI_VAR_STOP_LEVEL_P6 = 0x0C10,  // 12,16 stop_level_pump_6
  GAI_VAR_INTERLOCK_TIMEOUT_SLAVE = 0x0C14,  // 12,20 interlock timeout value (for return to auto)
  GAI_VAR_CURRENT_MAX_ALARM_GROUP1 = 0x0C15,  // 12,21 pump group 1 over load alarm limit
  GAI_VAR_CURRENT_MIN_ALARM_GROUP1 = 0x0C16,  // 12,22 pump group 1 under load alarm limit
  GAI_VAR_CURRENT_MAX_WARN_GROUP1 = 0x0C17,  // 12,23 pump group 1 over load warning limit
  GAI_VAR_CURRENT_MIN_WARN_GROUP1 = 0x0C18,  // 12,24 pump group 1 under load warning limit
  GAI_VAR_CURRENT_MAX_ALARM_GROUP2 = 0x0C19,  // 12,25 pump group 2 over load alarm limit
  GAI_VAR_CURRENT_MIN_ALARM_GROUP2 = 0x0C1A,  // 12,26 pump group 2 under load alarm limit
  GAI_VAR_CURRENT_MAX_WARN_GROUP2 = 0x0C1B,  // 12,27 pump group 2 over load warning limit
  GAI_VAR_CURRENT_MIN_WARN_GROUP2 = 0x0C1C,  // 12,28 pump group 2 under load warning limit
  GAI_VAR_FIXED_FREQ_PUMP1 = 0x0C1E,  // 12,30 pump1 fixed frequency
  GAI_VAR_FIXED_FREQ_PUMP2 = 0x0C1F,  // 12,31 pump2 fixed frequency
  GAI_VAR_FIXED_FREQ_PUMP3 = 0x0C20,  // 12,32 pump3 fixed frequency
  GAI_VAR_FIXED_FREQ_PUMP4 = 0x0C21,  // 12,33 pump4 fixed frequency
  GAI_VAR_FIXED_FREQ_PUMP5 = 0x0C22,  // 12,34 pump5 fixed frequency
  GAI_VAR_FIXED_FREQ_PUMP6 = 0x0C23,  // 12,35 pump6 fixed frequency
  GAI_VAR_EVENT_LOG_CLEAR_ID = 0x0D00,  // 13,0 event_log_clear_id
  GAI_VAR_ANA_OUT_USER_1 = 0x0D01,  // 13,1 
  GAI_VAR_ANA_OUT_USER_2 = 0x0D02,  // 13,2 
  GAI_VAR_ANA_OUT_USER_3 = 0x0D03,  // 13,3 
  GAI_VAR_SET_H2S_LEVEL = 0x0D04,  // 13,4 
  GAI_VAR_SET_H2S_FAULT = 0x0D05,  // 13,5 
  GAI_VAR_SET_DOSING_REF = 0x0D06,  // 13,6 
  GAI_VAR_PIT_POWER = 0x0E00,  // 14,0 pit_power
  GAI_VAR_PIT_ENERGY = 0x0E01,  // 14,1 pit_energy
  GAI_VAR_PIT_PUMPED_VOLUME = 0x0E02,  // 14,2 pit_pumped_volume
  GAI_VAR_PIT_OPR_TIME = 0x0E03,  // 14,3 pit_operation_time
  GAI_VAR_PIT_2_PUMPS_OPR_TIME = 0x0E04,  // 14,4 parallel_operation_time
  GAI_VAR_PIT_3_PUMPS_OPR_TIME = 0x0E05,  // 14,5 Total simultaneous 3 pump operating time
  GAI_VAR_PIT_4_PUMPS_OPR_TIME = 0x0E06,  // 14,6 Total simultaneous 4 pump operating time
  GAI_VAR_PIT_5_PUMPS_OPR_TIME = 0x0E07,  // 14,7 Total simultaneous 5 pump operating time
  GAI_VAR_PIT_6_PUMPS_OPR_TIME = 0x0E08,  // 14,8 Total simultaneous 6 pump operating time
  GAI_VAR_PIT_0_PUMPS_OPR_TIME = 0x0E09,  // 14,9 Total simultaneous 0 pump operating time
  GAI_VAR_PIT_1_PUMPS_OPR_TIME = 0x0E0A,  // 14,10 Total simultaneous 1 pump operating time
  GAI_VAR_PIT_MIXER_OPR_TIME = 0x0E1E,  // 14,30 
  GAI_VAR_PIT_MIXER_START_CNT = 0x0E1F,  // 14,31 
  GAI_VAR_P1_OPR_TIME = 0x0E28,  // 14,40 p1_opr_time
  GAI_VAR_P1_TIME_TO_SERVICE = 0x0E29,  // 14,41 p1_time_to_service
  GAI_VAR_P1_START_CNT = 0x0E2A,  // 14,42 p1_start_cnt
  GAI_VAR_P1_POWER = 0x0E2B,  // 14,43 
  GAI_VAR_P1_ENERGY = 0x0E2C,  // 14,44 
  GAI_VAR_P1_ANTI_BLOCKING_CNT = 0x0E2D,  // 14,45 anti-blocking count for pump1
  GAI_VAR_P2_OPR_TIME = 0x0E3C,  // 14,60 p2_opr_time
  GAI_VAR_P2_TIME_TO_SERVICE = 0x0E3D,  // 14,61 p2_time_to_service
  GAI_VAR_P2_START_CNT = 0x0E3E,  // 14,62 p2_start_cnt
  GAI_VAR_P2_POWER = 0x0E3F,  // 14,63 
  GAI_VAR_P2_ENERGY = 0x0E40,  // 14,64 
  GAI_VAR_P2_ANTI_BLOCKING_CNT = 0x0E41,  // 14,65 anti-blocking count for pump2
  GAI_VAR_P3_OPR_TIME = 0x0E50,  // 14,80 p3_opr_time
  GAI_VAR_P3_TIME_TO_SERVICE = 0x0E51,  // 14,81 p3_time_to_service
  GAI_VAR_P3_START_CNT = 0x0E52,  // 14,82 p3_start_cnt
  GAI_VAR_P3_POWER = 0x0E53,  // 14,83 p3 power
  GAI_VAR_P3_ENERGY = 0x0E54,  // 14,84 
  GAI_VAR_P3_ANTI_BLOCKING_CNT = 0x0E55,  // 14,85 anti-blocking count for pump3
  GAI_VAR_P4_OPR_TIME = 0x0E64,  // 14,100 p4_opr_time
  GAI_VAR_P4_TIME_TO_SERVICE = 0x0E65,  // 14,101 p4_time_to_service
  GAI_VAR_P4_START_CNT = 0x0E66,  // 14,102 p4_start_cnt
  GAI_VAR_P4_POWER = 0x0E67,  // 14,103 p4 power
  GAI_VAR_P4_ENERGY = 0x0E68,  // 14,104 
  GAI_VAR_P4_ANTI_BLOCKING_CNT = 0x0E69,  // 14,105 anti-blocking count for pump4
  GAI_VAR_P5_OPR_TIME = 0x0E78,  // 14,120 p5_opr_time
  GAI_VAR_P5_TIME_TO_SERVICE = 0x0E79,  // 14,121 p5_time_to_service
  GAI_VAR_P5_START_CNT = 0x0E7A,  // 14,122 p5_start_cnt
  GAI_VAR_P5_POWER = 0x0E7B,  // 14,123 p5 power
  GAI_VAR_P5_ENERGY = 0x0E7C,  // 14,124 
  GAI_VAR_P5_ANTI_BLOCKING_CNT = 0x0E7D,  // 14,125 anti-blocking count for pump5
  GAI_VAR_P6_OPR_TIME = 0x0E8C,  // 14,140 p6_opr_time
  GAI_VAR_P6_TIME_TO_SERVICE = 0x0E8D,  // 14,141 p6_time_to_service
  GAI_VAR_P6_START_CNT = 0x0E8E,  // 14,142 p6_start_cnt
  GAI_VAR_P6_POWER = 0x0E8F,  // 14,143 p6 power
  GAI_VAR_P6_ENERGY = 0x0E90,  // 14,144 
  GAI_VAR_P6_ANTI_BLOCKING_CNT = 0x0E91,  // 14,145 anti-blocking count for pump6
  GAI_VAR_REAL_TIME_CLOCK = 0x0EA0,  // 14,160 real_time_clock
  GAI_VAR_IP_ADDRESS = 0x0EA1,  // 14,161 IP address of GPRS connection
  GAI_VAR_USER_DEFINED_CNT_1 = 0x0EAA,  // 14,170 user defined counter 1
  GAI_VAR_USER_DEFINED_CNT_2 = 0x0EAB,  // 14,171 user defined counter 2
  GAI_VAR_USER_DEFINED_CNT_3 = 0x0EAC,  // 14,172 user defined counter 3
  GAI_VAR_TODAY_UDC_COUNTER1 = 0x0EAD,  // 14,173 
  GAI_VAR_TODAY_UDC_COUNTER2 = 0x0EAE,  // 14,174 
  GAI_VAR_TODAY_UDC_COUNTER3 = 0x0EAF,  // 14,175 
  GAI_VAR_YESTERDAY_UDC_COUNTER1 = 0x0EB0,  // 14,176 
  GAI_VAR_YESTERDAY_UDC_COUNTER2 = 0x0EB1,  // 14,177 
  GAI_VAR_YESTERDAY_UDC_COUNTER3 = 0x0EB2,  // 14,178 
  GAI_VAR_OVERFLOW_VOLUME = 0x0EB3,  // 14,179 overflow volume
  GAI_VAR_OVERFLOW_TIME = 0x0EB4,  // 14,180 overflow time
  GAI_VAR_H2S_LEVEL = 0x0EBE,  // 14,190 
  GAI_VAR_H2S_LEVEL_TODAY_LOG = 0x0EBF,  // 14,191 
  GAI_VAR_H2S_LEVEL_YESTERDAY_LOG = 0x0EC0,  // 14,192 
  GAI_VAR_DOSING_FEED_TANK_LEVEL = 0x0EC1,  // 14,193 
  GAI_VAR_DOSING_VOLUME_TOTAL_LOG = 0x0EC2,  // 14,194 
  GAI_VAR_DOSING_VOLUME_TODAY_LOG = 0x0EC3,  // 14,195 
  GAI_VAR_DOSING_VOLUME_YESTERDAY_LOG = 0x0EC4,  // 14,196 
  GAI_VAR_DOSING_REF_ACT = 0x0EC5,  // 14,197 
  GAI_VAR_DUMMY15 = 0x0F01,  // 15,1 Dummy: Last id must be > 0
  GAI_VAR_SET_REAL_TIME_CLOCK = 0x1000,  // 16,0 set_real_time_clock
  GAI_VAR_DUMMY16 = 0x1001  // 16,1 Dummy: Last id must be > 0
} GAI_VAR_TYPE;

/**************************************************************************
 GLOBAL VARIABLES (shared with GENIPRO bu_tab files and GeniAppIf)
**************************************************************************/
EXTERN U8 gai_2_0_no_of_float_switches;  // 2,0 no_of_float_switches
EXTERN U8 gai_2_1_float_switch_status;  // 2,1 Bit 0-4 eq. float switch 1-5 ; Bit 5 eq. over flow switch
EXTERN U8 gai_2_2_float_switch_1_func;  // 2,2 float_switch_1_func
EXTERN U8 gai_2_3_float_switch_2_func;  // 2,3 float_switch_2_func
EXTERN U8 gai_2_4_float_switch_3_func;  // 2,4 float_switch_3_func
EXTERN U8 gai_2_5_float_switch_4_func;  // 2,5 float_switch_4_func
EXTERN U8 gai_2_6_float_switch_5_func;  // 2,6 float_switch_5_func
EXTERN U8 gai_2_7_pit_sensors;  // 2,7 pit_sensors
EXTERN U8 gai_2_8_day_cnt_zero_time;  // 2,8 day_cnt_zero_time
EXTERN U8 gai_2_9_scada_pin_code_hi;  // 2,9 scada_pin_code
EXTERN U8 gai_2_10_scada_pin_code_lo;  // 2,10 scada_pin_code
EXTERN U8 gai_2_11_scada_pin_code_enabled;  // 2,11 scada_pin_code_enabled
EXTERN U8 gai_2_12_first_group_2_pump;  // 2,12 
EXTERN U8 gai_2_25_signal_level_act;  // 2,25 
EXTERN U8 gai_2_26_signal_level_avg;  // 2,26 
EXTERN U8 gai_2_71_pit_opr_mode;  // 2,71 pit_opr_mode
EXTERN U8 gai_2_72_pit_main_status;  // 2,72 pit_main_status, bits
EXTERN U8 gai_2_73_led_status;  // 2,73 bit10=0: green OFF, bit10=1: green ON; bit10=2: green flashing; bit32=0: red OFF, bit32=1: red ON; bit32=2: red flashing
EXTERN U8 gai_2_74_alarm_code;  // 2,74 alarm_code
EXTERN U8 gai_2_75_warning_code;  // 2,75 warning_code
EXTERN U8 gai_2_76_battery_voltage;  // 2,76 
EXTERN U8 gai_2_77_io_logic_outputs;  // 2,77 
EXTERN U8 gai_2_140_rtc_year;  // 2,140 rtc_year (since 1900)
EXTERN U8 gai_2_141_rtc_month_of_year;  // 2,141 rtc_month_of_year
EXTERN U8 gai_2_142_rtc_day_of_month;  // 2,142 rtc_day_of_month
EXTERN U8 gai_2_143_rtc_hour;  // 2,143 rtc_hour
EXTERN U8 gai_2_144_rtc_minute;  // 2,144 rtc_minute
EXTERN U8 gai_2_145_rtc_second;  // 2,145 rtc_second
EXTERN U8 gai_2_146_rtc_day_of_week;  // 2,146 rtc_day_of_week
EXTERN U8 gai_2_148_unit_family;  // 2,148 unit_family
EXTERN U8 gai_2_149_unit_type;  // 2,149 unit_family
EXTERN U8 gai_2_150_unit_version;  // 2,150 unit_version
EXTERN U8 gai_2_237_gsm_ctr;  // 2,237 gsm_ctr
EXTERN U8 gai_2_238_gsm_setup;  // 2,238 gsm_setup
EXTERN U8 gai_2_239_sms_out_seq_no;  // 2,239 sms_out_seq_no
EXTERN U8 gai_2_240_vfd_min_velocity_feature_enabled;  // 2,240 added for test during development
EXTERN U8 gai_4_0_production_code_1;  // 4,0 production_type_code
EXTERN U8 gai_4_1_production_code_2;  // 4,1 production_type_code
EXTERN U8 gai_4_2_production_code_3;  // 4,2 production_type_code
EXTERN U8 gai_4_3_production_code_4;  // 4,3 production_type_code
EXTERN U8 gai_4_4_production_code_5;  // 4,4 production_rev_date_code
EXTERN U8 gai_4_5_production_code_6;  // 4,5 production_rev_date_code
EXTERN U8 gai_4_6_production_code_7;  // 4,6 production_rev_date_code
EXTERN U8 gai_4_7_production_code_8;  // 4,7 production_serial_no
EXTERN U8 gai_4_8_production_code_9;  // 4,8 production_serial_no
EXTERN U8 gai_4_9_production_code_10;  // 4,9 production_serial_no
EXTERN U8 gai_4_21_mac_addr_0;  // 4,21 MAC address byte 0 - least significant
EXTERN U8 gai_4_22_mac_addr_1;  // 4,22 MAC address byte 1
EXTERN U8 gai_4_23_mac_addr_2;  // 4,23 MAC address byte 2
EXTERN U8 gai_4_24_mac_addr_3;  // 4,24 MAC address byte 3
EXTERN U8 gai_4_25_mac_addr_4;  // 4,25 MAC address byte 4
EXTERN U8 gai_4_26_mac_addr_5;  // 4,26 MAC address byte 5 - most significant
EXTERN U8 gai_4_46_slave_unit_address;  // 4,46 slave_unit_address
EXTERN U8 gai_4_47_slave_group_address;  // 4,47 slave_group_address
EXTERN U8 gai_4_79_baud_rate_default;  // 4,79 baud_rate_default
EXTERN U8 gai_4_80_min_reply_delay_default;  // 4,80 min_reply_delay_default
EXTERN U8 gai_4_81_geni_setup;  // 4,81 
EXTERN U8 gai_4_85_demo_suitcase_mode_enabled;  // 4,85 demo_suitcase_mode_enabled
EXTERN U8 gai_4_86_display_wizard_enable;  // 4,86 Wizard is active if true
EXTERN U8 gai_4_87_pit_level_sim_enabled;  // 4,87 pit_level_sim_enabled
EXTERN U8 gai_4_110_ana_out_1_conf_func;  // 4,110 Analog output 1 config
EXTERN U8 gai_4_111_ana_out_2_conf_func;  // 4,111 Analog output 2 config
EXTERN U8 gai_4_112_ana_out_3_conf_func;  // 4,112 Analog output 3 config
EXTERN U8 gai_4_113_ana_out_4_conf_func;  // 4,113 Analog output 4 config
EXTERN U8 gai_4_114_ana_out_5_conf_func;  // 4,114 Analog output 5 config
EXTERN U8 gai_4_115_ana_out_6_conf_func;  // 4,115 Analog output 6 config
EXTERN U8 gai_4_122_control_mode_pump1;  // 4,122 pump1 control mode
EXTERN U8 gai_4_123_control_mode_pump2;  // 4,123 pump2 control mode
EXTERN U8 gai_4_124_control_mode_pump3;  // 4,124 pump3 control mode
EXTERN U8 gai_4_125_control_mode_pump4;  // 4,125 pump4 control mode
EXTERN U8 gai_4_126_control_mode_pump5;  // 4,126 pump5 control mode
EXTERN U8 gai_4_127_control_mode_pump6;  // 4,127 pump6 control mode
EXTERN U8 gai_4_128_pid_feedback_pump1;  // 4,128 pump1 pid feedback signal
EXTERN U8 gai_4_129_pid_feedback_pump2;  // 4,129 pump2 pid feedback signal
EXTERN U8 gai_4_130_pid_feedback_pump3;  // 4,130 pump3 pidfeedback signal
EXTERN U8 gai_4_131_pid_feedback_pump4;  // 4,131 pump4 pidfeedback signal
EXTERN U8 gai_4_132_pid_feedback_pump5;  // 4,132 pump5 pidfeedback signal
EXTERN U8 gai_4_133_pid_feedback_pump6;  // 4,133 pump6 pidfeedback signal
EXTERN U8 gai_4_134_set_point_type_pump1;  // 4,134 pump1 setpoint type
EXTERN U8 gai_4_135_set_point_type_pump2;  // 4,135 pump2 setpoint type
EXTERN U8 gai_4_136_set_point_type_pump3;  // 4,136 pump3 setpoint type
EXTERN U8 gai_4_137_set_point_type_pump4;  // 4,137 pump4 setpoint type
EXTERN U8 gai_4_138_set_point_type_pump5;  // 4,138 pump5 setpoint type
EXTERN U8 gai_4_139_set_point_type_pump6;  // 4,139 pump6 setpoint type
EXTERN U8 gai_4_140_ai_setpoint_pump1;  // 4,140 pump1 setpoint(ai)
EXTERN U8 gai_4_141_ai_setpoint_pump2;  // 4,141 pump2 setpoint(ai)
EXTERN U8 gai_4_142_ai_setpoint_pump3;  // 4,142 pump3 setpoint(ai)
EXTERN U8 gai_4_143_ai_setpoint_pump4;  // 4,143 pump4 setpoint(ai)
EXTERN U8 gai_4_144_ai_setpoint_pump5;  // 4,144 pump5 setpoint(ai)
EXTERN U8 gai_4_145_ai_setpoint_pump6;  // 4,145 pump6 setpoint(ai)
EXTERN U8 gai_4_146_fixed_setpoint_pump1;  // 4,146 pump1 setpoint(fixed)
EXTERN U8 gai_4_147_fixed_setpoint_pump2;  // 4,147 pump2 setpoint(fixed)
EXTERN U8 gai_4_148_fixed_setpoint_pump3;  // 4,148 pump3 setpoint(fixed)
EXTERN U8 gai_4_149_fixed_setpoint_pump4;  // 4,149 pump4 setpoint(fixed)
EXTERN U8 gai_4_150_fixed_setpoint_pump5;  // 4,150 pump5 setpoint(fixed)
EXTERN U8 gai_4_151_fixed_setpoint_pump6;  // 4,151 pump6 setpoint(fixed)
EXTERN U8 gai_5_9_custom_relay;  // 5,9 custom_relay
EXTERN U8 gai_5_10_rtc_year_set;  // 5,10 Set real time clock the MPC way
EXTERN U8 gai_5_11_rtc_month_set;  // 5,11 Set real time clock the MPC way
EXTERN U8 gai_5_12_rtc_day_set;  // 5,12 Set real time clock the MPC way
EXTERN U8 gai_5_13_rtc_hour_set;  // 5,13 Set real time clock the MPC way
EXTERN U8 gai_5_14_rtc_minute_set;  // 5,14 Set real time clock the MPC way
EXTERN U8 gai_5_15_rtc_second_set;  // 5,15 Set real time clock the MPC way
EXTERN U8 gai_5_32_event_code_sim;  // 5,32 event_code_sim
EXTERN U8 gai_5_33_device_type_code_sim_id;  // 5,33 device_type_code_sim_id
EXTERN U8 gai_5_34_device_no_sim_id;  // 5,34 device_no_sim_id
EXTERN U8 gai_5_35_event_sim_activate;  // 5,35 event_sim_activate
EXTERN U8 gai_5_36_event_source_sim;  // 5,36 event_source_sim
EXTERN U8 gai_5_37_event_type_and_cond_sim;  // 5,37 event_type_and_cond_sim
EXTERN U8 gai_5_38_set_min_reply_delay;  // 5,38 set_min_reply_delay
EXTERN U8 gai_5_39_set_baud_rate;  // 5,39 set_baud_rate
EXTERN U8 gai_5_45_sms_out_seq_no_ack;  // 5,45 sms_out_seq_no_ack
EXTERN U8 gai_5_49_sim_card_status;  // 5,49 sim_card_status
EXTERN U8 gai_5_55_gsm_state;  // 5,55 gsm_state
EXTERN U8 gai_5_56_cim_heartbeat;  // 5,56 Heartbeat from ciu module, telling that communication is ok
EXTERN U8 gai_5_57_cim_type;  // 5,57 Type of CIM/CIU connected. A CIM/CIU master writes the value
EXTERN U16 gai_11_0_pit_water_level;  // 11,0 Actual pit level
EXTERN U16 gai_11_1_pit_switch_water_level;  // 11,1 float_switch_water_level (number)
EXTERN U16 gai_11_2_pit_depth;  // 11,2 Pit depth (config)
EXTERN U16 gai_11_3_pit_act_flow_in;  // 11,3 Flow (TBD)
EXTERN U16 gai_11_4_pit_avg_flow_in;  // 11,4 Flow (TBD)
EXTERN U16 gai_11_5_pit_act_flow_out;  // 11,5 Flow (TBD)
EXTERN U16 gai_11_6_pit_avg_flow_out;  // 11,6 Flow (TBD)
EXTERN U16 gai_11_7_pit_energy_yesterday;  // 11,7 pit_energy_yesterday
EXTERN U16 gai_11_8_pit_energy_today;  // 11,8 pit_energy_today
EXTERN U16 gai_11_9_pit_specific_energy;  // 11,9 Efficiency
EXTERN U16 gai_11_10_pit_pumped_volume_yesterday;  // 11,10 pit_pumped_volume_yesterday
EXTERN U16 gai_11_11_pit_pumped_volume_today;  // 11,11 pit_pumped_volume_today
EXTERN U16 gai_11_12_pit_2_pumps_opr_time_yesterday;  // 11,12 pit_2_pumps_opr_time_yesterday
EXTERN U16 gai_11_13_pit_3_pumps_opr_time_yesterday;  // 11,13 pit_3_pumps_opr_time_yesterday
EXTERN U16 gai_11_14_pit_4_pumps_opr_time_yesterday;  // 11,14 pit_4_pumps_opr_time_yesterday
EXTERN U16 gai_11_15_pit_5_pumps_opr_time_yesterday;  // 11,15 pit_5_pumps_opr_time_yesterday
EXTERN U16 gai_11_16_pit_6_pumps_opr_time_yesterday;  // 11,16 pit_6_pumps_opr_time_yesterday
EXTERN U16 gai_11_17_pit_2_pumps_opr_time_today;  // 11,17 pit_2_pumps_opr_time_today
EXTERN U16 gai_11_18_pit_3_pumps_opr_time_today;  // 11,18 pit_3_pumps_opr_time_today
EXTERN U16 gai_11_19_pit_4_pumps_opr_time_today;  // 11,19 pit_4_pumps_opr_time_today
EXTERN U16 gai_11_20_pit_5_pumps_opr_time_today;  // 11,20 pit_5_pumps_opr_time_today
EXTERN U16 gai_11_21_pit_6_pumps_opr_time_today;  // 11,21 pit_6_pumps_opr_time_today
EXTERN U16 gai_11_22_pit_mixer_starts_per_h;  // 11,22 mixer_starts_pr_hour
EXTERN U16 gai_11_23_pit_overflow_volume;  // 11,23 overflow volume
EXTERN U16 gai_11_24_pit_overflow_volume_yesterday;  // 11,24 pit_overflow_volume_yesterday
EXTERN U16 gai_11_25_pit_overflow_volume_today;  // 11,25 pit_overflow_volume_today
EXTERN U16 gai_11_26_pit_overflow_time;  // 11,26 overflow time
EXTERN U16 gai_11_27_pit_overflow_time_yesterday;  // 11,27 pit_overflow_time_yesterday
EXTERN U16 gai_11_28_pit_overflow_time_today;  // 11,28 pit_overflow_time_today
EXTERN U16 gai_11_29_pit_overflow_count;  // 11,29 overflow_count
EXTERN U16 gai_11_30_pit_overflow_cnt_yesterday;  // 11,30 pit_overflow_cnt_yesterday
EXTERN U16 gai_11_31_pit_overflow_cnt_today;  // 11,31 pit_overflow_cnt_today
EXTERN U16 gai_11_32_pit_pump_mode;  // 11,32 pit_pump_mode
EXTERN U16 gai_11_33_pit_pump_fault;  // 11,33 pit_pump_fault
EXTERN U16 gai_11_34_pit_pump_mon_fault;  // 11,34 pit_pump_mon_fault
EXTERN U16 gai_11_35_pit_pump_conn_type;  // 11,35 pit_pump_conn_type
EXTERN U16 gai_11_36_pit_pump_ctr_source;  // 11,36 pit_pump_ctr_source
EXTERN U16 gai_11_37_pit_alarms1;  // 11,37 pit_alarms1
EXTERN U16 gai_11_38_pit_alarms2;  // 11,38 pit_alarms2
EXTERN U16 gai_11_39_pit_alarms3;  // 11,39 pit_alarms3
EXTERN U16 gai_11_40_pit_warn1;  // 11,40 pit_warn1
EXTERN U16 gai_11_41_pit_warn2;  // 11,41 pit_warn2
EXTERN U16 gai_11_42_pit_warn3;  // 11,42 pit_warn3
EXTERN U16 gai_11_43_event_log_latest_id;  // 11,43 event_log_latest_id
EXTERN U16 gai_11_45_user_ana_in_1;  // 11,45 user_ana_in_1
EXTERN U16 gai_11_46_user_ana_in_2;  // 11,46 user_ana_in_2
EXTERN U16 gai_11_47_user_ana_in_3;  // 11,47 user_ana_in_3
EXTERN U16 gai_11_48_pit_rand_start_level_band;  // 11,48 
EXTERN U16 gai_11_49_pit_0_pumps_opr_time_yesterday;  // 11,49 pit_0_pumps_opr_time_yesterday
EXTERN U16 gai_11_50_pit_1_pumps_opr_time_yesterday;  // 11,50 pit_1_pumps_opr_time_yesterday
EXTERN U16 gai_11_51_pit_0_pumps_opr_time_today;  // 11,51 pit_0_pumps_opr_time_today
EXTERN U16 gai_11_52_pit_1_pumps_opr_time_today;  // 11,52 pit_1_pumps_opr_time_today
EXTERN U16 gai_11_53_discharge_pressure;  // 11,53 Discharge pressure
EXTERN U16 gai_11_55_pit_alarms4;  // 11,55 
EXTERN U16 gai_11_56_pit_warn4;  // 11,56 
EXTERN U16 gai_11_59_power_on_counter;  // 11,59 power_on_counter (not in profile)
EXTERN U16 gai_11_60_p1_opr_time_yesterday;  // 11,60 p1_opr_time_yesterday
EXTERN U16 gai_11_61_p1_opr_time_today;  // 11,61 p1_opr_time_today
EXTERN U16 gai_11_62_p1_latest_runtime;  // 11,62 pump_1_latest_runtime
EXTERN U16 gai_11_63_p1_start_cnt_yesterday;  // 11,63 p1_start_cnt_yesterday
EXTERN U16 gai_11_64_p1_start_cnt_today;  // 11,64 p1_start_cnt_today
EXTERN U16 gai_11_65_p1_starts_pr_hour;  // 11,65 pump_1_starts_pr_hour
EXTERN U16 gai_11_66_p1_flow;  // 11,66 pump_1_calculated_flow_filtered
EXTERN U16 gai_11_67_p1_latest_flow;  // 11,67 pump_1_calculated_flow_raw
EXTERN U16 gai_11_68_p1_current;  // 11,68 
EXTERN U16 gai_11_69_p1_latest_current;  // 11,69 p1_latest_current
EXTERN U16 gai_11_70_p1_insulation;  // 11,70 
EXTERN U16 gai_11_71_p1_water_in_oil;  // 11,71 pump_1_water_in_oil
EXTERN U16 gai_11_72_p1_motor_temp1;  // 11,72 pump_1_temperature
EXTERN U16 gai_11_74_p1_cosine_phi;  // 11,74 
EXTERN U16 gai_11_75_p1_freq;  // 11,75 
EXTERN U16 gai_11_76_p1_mode_and_connect;  // 11,76 p1_mode_and_connect
EXTERN U16 gai_11_77_p1_alarms1;  // 11,77 p1_alarms1
EXTERN U16 gai_11_78_p1_alarms2;  // 11,78 p1_alarms2
EXTERN U16 gai_11_79_p1_alarms3;  // 11,79 p1_alarms3
EXTERN U16 gai_11_80_p1_warn1;  // 11,80 p1_warn1
EXTERN U16 gai_11_81_p1_warn2;  // 11,81 p1_warn2
EXTERN U16 gai_11_82_p1_warn3;  // 11,82 p1_warn3
EXTERN U16 gai_11_83_p1_voltage;  // 11,83 
EXTERN U16 gai_11_85_p1_vfd_mode;  // 11,85 
EXTERN U16 gai_11_86_p1_torque;  // 11,86 
EXTERN U16 gai_11_87_p1_i_asym;  // 11,87 
EXTERN U16 gai_11_88_p1_alarms4;  // 11,88 p1_alarms4
EXTERN U16 gai_11_89_p1_warn4;  // 11,89 p1_warn4
EXTERN U16 gai_11_90_p2_opr_time_yesterday;  // 11,90 p2_opr_time_yesterday
EXTERN U16 gai_11_91_p2_opr_time_today;  // 11,91 p2_opr_time_today
EXTERN U16 gai_11_92_p2_latest_runtime;  // 11,92 pump_2_latest_runtime
EXTERN U16 gai_11_93_p2_start_cnt_yesterday;  // 11,93 p2_start_cnt_yesterday
EXTERN U16 gai_11_94_p2_start_cnt_today;  // 11,94 p2_start_cnt_today
EXTERN U16 gai_11_95_p2_starts_pr_hour;  // 11,95 pump_2_starts_pr_hour
EXTERN U16 gai_11_96_p2_flow;  // 11,96 pump_2_calculated_flow_filtered
EXTERN U16 gai_11_97_p2_latest_flow;  // 11,97 pump_2_calculated_flow_raw
EXTERN U16 gai_11_98_p2_current;  // 11,98 
EXTERN U16 gai_11_99_p2_latest_current;  // 11,99 p2_latest_current
EXTERN U16 gai_11_100_p2_insulation;  // 11,100 
EXTERN U16 gai_11_101_p2_water_in_oil;  // 11,101 pump_2_water_in_oil
EXTERN U16 gai_11_102_p2_motor_temp;  // 11,102 pump_2_temperature
EXTERN U16 gai_11_104_p2_cosine_phi;  // 11,104 
EXTERN U16 gai_11_105_p2_freq;  // 11,105 
EXTERN U16 gai_11_106_p2_mode_and_connect;  // 11,106 p2_mode_and_connect
EXTERN U16 gai_11_107_p2_alarms1;  // 11,107 p2_alarms1
EXTERN U16 gai_11_108_p2_alarms2;  // 11,108 p2_alarms2
EXTERN U16 gai_11_109_p2_alarms3;  // 11,109 p2_alarms3
EXTERN U16 gai_11_110_p2_warn1;  // 11,110 p2_warn1
EXTERN U16 gai_11_111_p2_warn2;  // 11,111 p2_warn2
EXTERN U16 gai_11_112_p2_warn3;  // 11,112 p2_warn3
EXTERN U16 gai_11_113_p2_voltage;  // 11,113 
EXTERN U16 gai_11_115_p2_vfd_mode;  // 11,115 
EXTERN U16 gai_11_116_p2_torque;  // 11,116 
EXTERN U16 gai_11_117_p2_i_asym;  // 11,117 
EXTERN U16 gai_11_118_p2_alarms4;  // 11,118 p2_alarms4
EXTERN U16 gai_11_119_p2_warn4;  // 11,119 p2_warn4
EXTERN U16 gai_11_120_p3_opr_time_yesterday;  // 11,120 p3_opr_time_yesterday
EXTERN U16 gai_11_121_p3_opr_time_today;  // 11,121 p3_opr_time_today
EXTERN U16 gai_11_122_p3_latest_runtime;  // 11,122 pump_3_latest_runtime
EXTERN U16 gai_11_123_p3_start_cnt_yesterday;  // 11,123 p3_start_cnt_yesterday
EXTERN U16 gai_11_124_p3_start_cnt_today;  // 11,124 p3_start_cnt_today
EXTERN U16 gai_11_125_p3_starts_pr_hour;  // 11,125 pump_3_starts_pr_hour
EXTERN U16 gai_11_126_p3_flow;  // 11,126 pump_3_calculated_flow_filtered
EXTERN U16 gai_11_127_p3_latest_flow;  // 11,127 pump_3_calculated_flow_raw
EXTERN U16 gai_11_128_p3_current;  // 11,128 
EXTERN U16 gai_11_129_p3_latest_current;  // 11,129 p3_latest_current
EXTERN U16 gai_11_130_p3_insulation;  // 11,130 
EXTERN U16 gai_11_131_p3_water_in_oil;  // 11,131 pump_3_water_in_oil
EXTERN U16 gai_11_132_p3_motor_temp;  // 11,132 pump_3_temperature
EXTERN U16 gai_11_134_p3_cosine_phi;  // 11,134 
EXTERN U16 gai_11_135_p3_freq;  // 11,135 
EXTERN U16 gai_11_136_p3_mode_and_connect;  // 11,136 p3_mode_and_connect
EXTERN U16 gai_11_137_p3_alarms1;  // 11,137 p3_alarms1
EXTERN U16 gai_11_138_p3_alarms2;  // 11,138 p3_alarms2
EXTERN U16 gai_11_139_p3_alarms3;  // 11,139 p3_alarms3
EXTERN U16 gai_11_140_p3_warn1;  // 11,140 p3_warn1
EXTERN U16 gai_11_141_p3_warn2;  // 11,141 p3_warn2
EXTERN U16 gai_11_142_p3_warn3;  // 11,142 p3_warn3
EXTERN U16 gai_11_143_p3_voltage;  // 11,143 
EXTERN U16 gai_11_145_p3_vfd_mode;  // 11,145 
EXTERN U16 gai_11_146_p3_torque;  // 11,146 
EXTERN U16 gai_11_147_p3_i_asym;  // 11,147 
EXTERN U16 gai_11_148_p3_alarms4;  // 11,148 p3_alarms4
EXTERN U16 gai_11_149_p3_warn4;  // 11,149 p3_warn4
EXTERN U16 gai_11_150_p4_opr_time_yesterday;  // 11,150 p4_opr_time_yesterday
EXTERN U16 gai_11_151_p4_opr_time_today;  // 11,151 p4_opr_time_today
EXTERN U16 gai_11_152_p4_latest_runtime;  // 11,152 pump_4_latest_runtime
EXTERN U16 gai_11_153_p4_start_cnt_yesterday;  // 11,153 p4_start_cnt_yesterday
EXTERN U16 gai_11_154_p4_start_cnt_today;  // 11,154 p4_start_cnt_today
EXTERN U16 gai_11_155_p4_starts_pr_hour;  // 11,155 pump_4_starts_pr_hour
EXTERN U16 gai_11_156_p4_flow;  // 11,156 pump_4_calculated_flow_filtered
EXTERN U16 gai_11_157_p4_latest_flow;  // 11,157 pump_4_calculated_flow_raw
EXTERN U16 gai_11_158_p4_current;  // 11,158 
EXTERN U16 gai_11_159_p4_latest_current;  // 11,159 p4_latest_current
EXTERN U16 gai_11_160_p4_insulation;  // 11,160 
EXTERN U16 gai_11_161_p4_water_in_oil;  // 11,161 pump_4_water_in_oil
EXTERN U16 gai_11_162_p4_motor_temp;  // 11,162 pump_4_temperature
EXTERN U16 gai_11_164_p4_cosine_phi;  // 11,164 
EXTERN U16 gai_11_165_p4_freq;  // 11,165 
EXTERN U16 gai_11_166_p4_mode_and_connect;  // 11,166 p4_mode_and_connect
EXTERN U16 gai_11_167_p4_alarms1;  // 11,167 p4_alarms1
EXTERN U16 gai_11_168_p4_alarms2;  // 11,168 p4_alarms2
EXTERN U16 gai_11_169_p4_alarms3;  // 11,169 p4_alarms3
EXTERN U16 gai_11_170_p4_warn1;  // 11,170 p4_warn1
EXTERN U16 gai_11_171_p4_warn2;  // 11,171 p4_warn2
EXTERN U16 gai_11_172_p4_warn3;  // 11,172 p4_warn3
EXTERN U16 gai_11_173_p4_voltage;  // 11,173 
EXTERN U16 gai_11_175_p4_vfd_mode;  // 11,175 
EXTERN U16 gai_11_176_p4_torque;  // 11,176 
EXTERN U16 gai_11_177_p4_i_asym;  // 11,177 
EXTERN U16 gai_11_178_p4_alarms4;  // 11,178 p4_alarms4
EXTERN U16 gai_11_179_p4_warn4;  // 11,179 p4_warn4
EXTERN U16 gai_11_180_p5_opr_time_yesterday;  // 11,180 p5_opr_time_yesterday
EXTERN U16 gai_11_181_p5_opr_time_today;  // 11,181 p5_opr_time_today
EXTERN U16 gai_11_182_p5_latest_runtime;  // 11,182 pump_5_latest_runtime
EXTERN U16 gai_11_183_p5_start_cnt_yesterday;  // 11,183 p5_start_cnt_yesterday
EXTERN U16 gai_11_184_p5_start_cnt_today;  // 11,184 p5_start_cnt_today
EXTERN U16 gai_11_185_p5_starts_pr_hour;  // 11,185 pump_5_starts_pr_hour
EXTERN U16 gai_11_186_p5_flow;  // 11,186 pump_5_calculated_flow_filtered
EXTERN U16 gai_11_187_p5_latest_flow;  // 11,187 pump_5_calculated_flow_raw
EXTERN U16 gai_11_188_p5_current;  // 11,188 
EXTERN U16 gai_11_189_p5_latest_current;  // 11,189 p5_latest_current
EXTERN U16 gai_11_190_p5_insulation;  // 11,190 
EXTERN U16 gai_11_191_p5_water_in_oil;  // 11,191 pump_5_water_in_oil
EXTERN U16 gai_11_192_p5_motor_temp;  // 11,192 pump_5_temperature
EXTERN U16 gai_11_194_p5_cosine_phi;  // 11,194 
EXTERN U16 gai_11_195_p5_freq;  // 11,195 
EXTERN U16 gai_11_196_p5_mode_and_connect;  // 11,196 p5_mode_and_connect
EXTERN U16 gai_11_197_p5_alarms1;  // 11,197 p5_alarms1
EXTERN U16 gai_11_198_p5_alarms2;  // 11,198 p5_alarms2
EXTERN U16 gai_11_199_p5_alarms3;  // 11,199 p5_alarms3
EXTERN U16 gai_11_200_p5_warn1;  // 11,200 p5_warn1
EXTERN U16 gai_11_201_p5_warn2;  // 11,201 p5_warn2
EXTERN U16 gai_11_202_p5_warn3;  // 11,202 p5_warn3
EXTERN U16 gai_11_203_p5_voltage;  // 11,203 
EXTERN U16 gai_11_205_p5_vfd_mode;  // 11,205 
EXTERN U16 gai_11_206_p5_torque;  // 11,206 
EXTERN U16 gai_11_207_p5_i_asym;  // 11,207 
EXTERN U16 gai_11_208_p5_alarms4;  // 11,208 p5_alarms4
EXTERN U16 gai_11_209_p5_warn4;  // 11,209 p5_warn4
EXTERN U16 gai_11_210_p6_opr_time_yesterday;  // 11,210 p6_opr_time_yesterday
EXTERN U16 gai_11_211_p6_opr_time_today;  // 11,211 p6_opr_time_today
EXTERN U16 gai_11_212_p6_latest_runtime;  // 11,212 pump_6_latest_runtime
EXTERN U16 gai_11_213_p6_start_cnt_yesterday;  // 11,213 p6_start_cnt_yesterday
EXTERN U16 gai_11_214_p6_start_cnt_today;  // 11,214 p6_start_cnt_today
EXTERN U16 gai_11_215_p6_starts_pr_hour;  // 11,215 pump_6_starts_pr_hour
EXTERN U16 gai_11_216_p6_flow;  // 11,216 pump_6_calculated_flow_filtered
EXTERN U16 gai_11_217_p6_latest_flow;  // 11,217 pump_6_calculated_flow_raw
EXTERN U16 gai_11_218_p6_current;  // 11,218 
EXTERN U16 gai_11_219_p6_latest_current;  // 11,219 p6_latest_current
EXTERN U16 gai_11_220_p6_insulation;  // 11,220 
EXTERN U16 gai_11_221_p6_water_in_oil;  // 11,221 pump_6_water_in_oil
EXTERN U16 gai_11_222_p6_motor_temp;  // 11,222 pump_6_temperature
EXTERN U16 gai_11_224_p6_cosine_phi;  // 11,224 
EXTERN U16 gai_11_225_p6_freq;  // 11,225 
EXTERN U16 gai_11_226_p6_mode_and_connect;  // 11,226 p6_mode_and_connect
EXTERN U16 gai_11_227_p6_alarms1;  // 11,227 p6_alarms1
EXTERN U16 gai_11_228_p6_alarms2;  // 11,228 p6_alarms2
EXTERN U16 gai_11_229_p6_alarms3;  // 11,229 p6_alarms3
EXTERN U16 gai_11_230_p6_warn1;  // 11,230 p6_warn1
EXTERN U16 gai_11_231_p6_warn2;  // 11,231 p6_warn2
EXTERN U16 gai_11_232_p6_warn3;  // 11,232 p6_warn3
EXTERN U16 gai_11_233_p6_voltage;  // 11,233 
EXTERN U16 gai_11_235_p6_vfd_mode;  // 11,235 
EXTERN U16 gai_11_236_p6_torque;  // 11,236 
EXTERN U16 gai_11_237_p6_i_asym;  // 11,237 
EXTERN U16 gai_11_238_p6_alarms4;  // 11,238 p6_alarms4
EXTERN U16 gai_11_239_p6_warn4;  // 11,239 p6_warn4
EXTERN U16 gai_11_251_class_11_dummy_1;  // 11,251 Dummy par, used for debug
EXTERN U16 gai_11_252_class_11_dummy_2;  // 11,252 Dummy par, used for debug
EXTERN U16 gai_11_253_class_11_dummy_3;  // 11,253 Dummy par, used for debug
EXTERN U16 gai_12_0_overflow_level;  // 12,0 overflow_alarm_level
EXTERN U16 gai_12_1_high_level;  // 12,1 high_level_alarm_level
EXTERN U16 gai_12_2_alarm_level;  // 12,2 level_alarm_alarm_level
EXTERN U16 gai_12_3_dry_running_level;  // 12,3 dry_running_alarm_level
EXTERN U16 gai_12_4_foam_drain_level;  // 12,4 foam_drain_level
EXTERN U16 gai_12_5_start_level_p1;  // 12,5 start_level_pump_1
EXTERN U16 gai_12_6_start_level_p2;  // 12,6 start_level_pump_2
EXTERN U16 gai_12_7_start_level_p3;  // 12,7 start_level_pump_3
EXTERN U16 gai_12_8_start_level_p4;  // 12,8 start_level_pump_4
EXTERN U16 gai_12_9_start_level_p5;  // 12,9 start_level_pump_5
EXTERN U16 gai_12_10_start_level_p6;  // 12,10 start_level_pump_6
EXTERN U16 gai_12_11_stop_level_p1;  // 12,11 stop_level_pump_1
EXTERN U16 gai_12_12_stop_level_p2;  // 12,12 stop_level_pump_2
EXTERN U16 gai_12_13_stop_level_p3;  // 12,13 stop_level_pump_3
EXTERN U16 gai_12_14_stop_level_p4;  // 12,14 stop_level_pump_4
EXTERN U16 gai_12_15_stop_level_p5;  // 12,15 stop_level_pump_5
EXTERN U16 gai_12_16_stop_level_p6;  // 12,16 stop_level_pump_6
EXTERN U16 gai_12_20_interlock_timeout_slave;  // 12,20 interlock timeout value (for return to auto)
EXTERN U16 gai_12_21_current_max_alarm_group1;  // 12,21 pump group 1 over load alarm limit
EXTERN U16 gai_12_22_current_min_alarm_group1;  // 12,22 pump group 1 under load alarm limit
EXTERN U16 gai_12_23_current_max_warn_group1;  // 12,23 pump group 1 over load warning limit
EXTERN U16 gai_12_24_current_min_warn_group1;  // 12,24 pump group 1 under load warning limit
EXTERN U16 gai_12_25_current_max_alarm_group2;  // 12,25 pump group 2 over load alarm limit
EXTERN U16 gai_12_26_current_min_alarm_group2;  // 12,26 pump group 2 under load alarm limit
EXTERN U16 gai_12_27_current_max_warn_group2;  // 12,27 pump group 2 over load warning limit
EXTERN U16 gai_12_28_current_min_warn_group2;  // 12,28 pump group 2 under load warning limit
EXTERN U16 gai_12_30_fixed_freq_pump1;  // 12,30 pump1 fixed frequency
EXTERN U16 gai_12_31_fixed_freq_pump2;  // 12,31 pump2 fixed frequency
EXTERN U16 gai_12_32_fixed_freq_pump3;  // 12,32 pump3 fixed frequency
EXTERN U16 gai_12_33_fixed_freq_pump4;  // 12,33 pump4 fixed frequency
EXTERN U16 gai_12_34_fixed_freq_pump5;  // 12,34 pump5 fixed frequency
EXTERN U16 gai_12_35_fixed_freq_pump6;  // 12,35 pump6 fixed frequency
EXTERN U16 gai_13_0_event_log_clear_id;  // 13,0 event_log_clear_id
EXTERN U16 gai_13_1_ana_out_user_1;  // 13,1 
EXTERN U16 gai_13_2_ana_out_user_2;  // 13,2 
EXTERN U16 gai_13_3_ana_out_user_3;  // 13,3 
EXTERN U16 gai_13_4_set_h2s_level;  // 13,4 
EXTERN U16 gai_13_5_set_h2s_fault;  // 13,5 
EXTERN U16 gai_13_6_set_dosing_ref;  // 13,6 
EXTERN U32 gai_14_0_pit_power;  // 14,0 pit_power
EXTERN U32 gai_14_1_pit_energy;  // 14,1 pit_energy
EXTERN U32 gai_14_2_pit_pumped_volume;  // 14,2 pit_pumped_volume
EXTERN U32 gai_14_3_pit_opr_time;  // 14,3 pit_operation_time
EXTERN U32 gai_14_4_pit_2_pumps_opr_time;  // 14,4 parallel_operation_time
EXTERN U32 gai_14_5_pit_3_pumps_opr_time;  // 14,5 Total simultaneous 3 pump operating time
EXTERN U32 gai_14_6_pit_4_pumps_opr_time;  // 14,6 Total simultaneous 4 pump operating time
EXTERN U32 gai_14_7_pit_5_pumps_opr_time;  // 14,7 Total simultaneous 5 pump operating time
EXTERN U32 gai_14_8_pit_6_pumps_opr_time;  // 14,8 Total simultaneous 6 pump operating time
EXTERN U32 gai_14_9_pit_0_pumps_opr_time;  // 14,9 Total simultaneous 0 pump operating time
EXTERN U32 gai_14_10_pit_1_pumps_opr_time;  // 14,10 Total simultaneous 1 pump operating time
EXTERN U32 gai_14_30_pit_mixer_opr_time;  // 14,30 
EXTERN U32 gai_14_31_pit_mixer_start_cnt;  // 14,31 
EXTERN U32 gai_14_40_p1_opr_time;  // 14,40 p1_opr_time
EXTERN U32 gai_14_41_p1_time_to_service;  // 14,41 p1_time_to_service
EXTERN U32 gai_14_42_p1_start_cnt;  // 14,42 p1_start_cnt
EXTERN U32 gai_14_43_p1_power;  // 14,43 
EXTERN U32 gai_14_44_p1_energy;  // 14,44 
EXTERN U32 gai_14_45_p1_anti_blocking_cnt;  // 14,45 anti-blocking count for pump1
EXTERN U32 gai_14_60_p2_opr_time;  // 14,60 p2_opr_time
EXTERN U32 gai_14_61_p2_time_to_service;  // 14,61 p2_time_to_service
EXTERN U32 gai_14_62_p2_start_cnt;  // 14,62 p2_start_cnt
EXTERN U32 gai_14_63_p2_power;  // 14,63 
EXTERN U32 gai_14_64_p2_energy;  // 14,64 
EXTERN U32 gai_14_65_p2_anti_blocking_cnt;  // 14,65 anti-blocking count for pump2
EXTERN U32 gai_14_80_p3_opr_time;  // 14,80 p3_opr_time
EXTERN U32 gai_14_81_p3_time_to_service;  // 14,81 p3_time_to_service
EXTERN U32 gai_14_82_p3_start_cnt;  // 14,82 p3_start_cnt
EXTERN U32 gai_14_83_p3_power;  // 14,83 p3 power
EXTERN U32 gai_14_84_p3_energy;  // 14,84 
EXTERN U32 gai_14_85_p3_anti_blocking_cnt;  // 14,85 anti-blocking count for pump3
EXTERN U32 gai_14_100_p4_opr_time;  // 14,100 p4_opr_time
EXTERN U32 gai_14_101_p4_time_to_service;  // 14,101 p4_time_to_service
EXTERN U32 gai_14_102_p4_start_cnt;  // 14,102 p4_start_cnt
EXTERN U32 gai_14_103_p4_power;  // 14,103 p4 power
EXTERN U32 gai_14_104_p4_energy;  // 14,104 
EXTERN U32 gai_14_105_p4_anti_blocking_cnt;  // 14,105 anti-blocking count for pump4
EXTERN U32 gai_14_120_p5_opr_time;  // 14,120 p5_opr_time
EXTERN U32 gai_14_121_p5_time_to_service;  // 14,121 p5_time_to_service
EXTERN U32 gai_14_122_p5_start_cnt;  // 14,122 p5_start_cnt
EXTERN U32 gai_14_123_p5_power;  // 14,123 p5 power
EXTERN U32 gai_14_124_p5_energy;  // 14,124 
EXTERN U32 gai_14_125_p5_anti_blocking_cnt;  // 14,125 anti-blocking count for pump5
EXTERN U32 gai_14_140_p6_opr_time;  // 14,140 p6_opr_time
EXTERN U32 gai_14_141_p6_time_to_service;  // 14,141 p6_time_to_service
EXTERN U32 gai_14_142_p6_start_cnt;  // 14,142 p6_start_cnt
EXTERN U32 gai_14_143_p6_power;  // 14,143 p6 power
EXTERN U32 gai_14_144_p6_energy;  // 14,144 
EXTERN U32 gai_14_145_p6_anti_blocking_cnt;  // 14,145 anti-blocking count for pump6
EXTERN U32 gai_14_160_real_time_clock;  // 14,160 real_time_clock
EXTERN U32 gai_14_161_ip_address;  // 14,161 IP address of GPRS connection
EXTERN U32 gai_14_170_user_defined_cnt_1;  // 14,170 user defined counter 1
EXTERN U32 gai_14_171_user_defined_cnt_2;  // 14,171 user defined counter 2
EXTERN U32 gai_14_172_user_defined_cnt_3;  // 14,172 user defined counter 3
EXTERN U32 gai_14_173_today_udc_counter1;  // 14,173 
EXTERN U32 gai_14_174_today_udc_counter2;  // 14,174 
EXTERN U32 gai_14_175_today_udc_counter3;  // 14,175 
EXTERN U32 gai_14_176_yesterday_udc_counter1;  // 14,176 
EXTERN U32 gai_14_177_yesterday_udc_counter2;  // 14,177 
EXTERN U32 gai_14_178_yesterday_udc_counter3;  // 14,178 
EXTERN U32 gai_14_179_overflow_volume;  // 14,179 overflow volume
EXTERN U32 gai_14_180_overflow_time;  // 14,180 overflow time
EXTERN U32 gai_14_190_h2s_level;  // 14,190 
EXTERN U32 gai_14_191_h2s_level_today_log;  // 14,191 
EXTERN U32 gai_14_192_h2s_level_yesterday_log;  // 14,192 
EXTERN U32 gai_14_193_dosing_feed_tank_level;  // 14,193 
EXTERN U32 gai_14_194_dosing_volume_total_log;  // 14,194 
EXTERN U32 gai_14_195_dosing_volume_today_log;  // 14,195 
EXTERN U32 gai_14_196_dosing_volume_yesterday_log;  // 14,196 
EXTERN U32 gai_14_197_dosing_ref_act;  // 14,197 
EXTERN U32 gai_15_1_dummy15;  // 15,1 Dummy: Last id must be > 0
EXTERN U32 gai_16_0_set_real_time_clock;  // 16,0 set_real_time_clock
EXTERN U32 gai_16_1_dummy16;  // 16,1 Dummy: Last id must be > 0

#endif
