/**************************************************************************
 This file is auto-generated by FactoryGenerator, do not modify it manually
**************************************************************************/

/**************************************************************************
 INCLUDES
**************************************************************************/
#include <common.h>
#include <InfoDef.h>
#include <GeniAppIfData.h>

/**************************************************************************
 DEFINES
**************************************************************************/
#define UC_ADDR_0_LI(X) ((UCHAR*)&X)

/**************************************************************************
 TABLE
**************************************************************************/
const ID_PTR meas16_tab[] = 
{
/* ID   0 */ UC_ADDR_0_LI(gai_11_0_pit_water_level), // Actual pit level
/* ID   1 */ UC_ADDR_0_LI(gai_11_1_pit_switch_water_level), // float_switch_water_level (number)
/* ID   2 */ UC_ADDR_0_LI(gai_11_2_pit_depth), // Pit depth (config)
/* ID   3 */ UC_ADDR_0_LI(gai_11_3_pit_act_flow_in), // Flow (TBD)
/* ID   4 */ UC_ADDR_0_LI(gai_11_4_pit_avg_flow_in), // Flow (TBD)
/* ID   5 */ UC_ADDR_0_LI(gai_11_5_pit_act_flow_out), // Flow (TBD)
/* ID   6 */ UC_ADDR_0_LI(gai_11_6_pit_avg_flow_out), // Flow (TBD)
/* ID   7 */ UC_ADDR_0_LI(gai_11_7_pit_energy_yesterday), // pit_energy_yesterday
/* ID   8 */ UC_ADDR_0_LI(gai_11_8_pit_energy_today), // pit_energy_today
/* ID   9 */ UC_ADDR_0_LI(gai_11_9_pit_specific_energy), // Efficiency
/* ID  10 */ UC_ADDR_0_LI(gai_11_10_pit_pumped_volume_yesterday), // pit_pumped_volume_yesterday
/* ID  11 */ UC_ADDR_0_LI(gai_11_11_pit_pumped_volume_today), // pit_pumped_volume_today
/* ID  12 */ UC_ADDR_0_LI(gai_11_12_pit_2_pumps_opr_time_yesterday), // pit_2_pumps_opr_time_yesterday
/* ID  13 */ UC_ADDR_0_LI(gai_11_13_pit_3_pumps_opr_time_yesterday), // pit_3_pumps_opr_time_yesterday
/* ID  14 */ UC_ADDR_0_LI(gai_11_14_pit_4_pumps_opr_time_yesterday), // pit_4_pumps_opr_time_yesterday
/* ID  15 */ UC_ADDR_0_LI(gai_11_15_pit_5_pumps_opr_time_yesterday), // pit_5_pumps_opr_time_yesterday
/* ID  16 */ UC_ADDR_0_LI(gai_11_16_pit_6_pumps_opr_time_yesterday), // pit_6_pumps_opr_time_yesterday
/* ID  17 */ UC_ADDR_0_LI(gai_11_17_pit_2_pumps_opr_time_today), // pit_2_pumps_opr_time_today
/* ID  18 */ UC_ADDR_0_LI(gai_11_18_pit_3_pumps_opr_time_today), // pit_3_pumps_opr_time_today
/* ID  19 */ UC_ADDR_0_LI(gai_11_19_pit_4_pumps_opr_time_today), // pit_4_pumps_opr_time_today
/* ID  20 */ UC_ADDR_0_LI(gai_11_20_pit_5_pumps_opr_time_today), // pit_5_pumps_opr_time_today
/* ID  21 */ UC_ADDR_0_LI(gai_11_21_pit_6_pumps_opr_time_today), // pit_6_pumps_opr_time_today
/* ID  22 */ UC_ADDR_0_LI(gai_11_22_pit_mixer_starts_per_h), // mixer_starts_pr_hour
/* ID  23 */ UC_ADDR_0_LI(gai_11_23_pit_overflow_volume), // overflow volume
/* ID  24 */ UC_ADDR_0_LI(gai_11_24_pit_overflow_volume_yesterday), // pit_overflow_volume_yesterday
/* ID  25 */ UC_ADDR_0_LI(gai_11_25_pit_overflow_volume_today), // pit_overflow_volume_today
/* ID  26 */ UC_ADDR_0_LI(gai_11_26_pit_overflow_time), // overflow time
/* ID  27 */ UC_ADDR_0_LI(gai_11_27_pit_overflow_time_yesterday), // pit_overflow_time_yesterday
/* ID  28 */ UC_ADDR_0_LI(gai_11_28_pit_overflow_time_today), // pit_overflow_time_today
/* ID  29 */ UC_ADDR_0_LI(gai_11_29_pit_overflow_count), // overflow_count
/* ID  30 */ UC_ADDR_0_LI(gai_11_30_pit_overflow_cnt_yesterday), // pit_overflow_cnt_yesterday
/* ID  31 */ UC_ADDR_0_LI(gai_11_31_pit_overflow_cnt_today), // pit_overflow_cnt_today
/* ID  32 */ UC_ADDR_0_LI(gai_11_32_pit_pump_mode), // pit_pump_mode
/* ID  33 */ UC_ADDR_0_LI(gai_11_33_pit_pump_fault), // pit_pump_fault
/* ID  34 */ UC_ADDR_0_LI(gai_11_34_pit_pump_mon_fault), // pit_pump_mon_fault
/* ID  35 */ UC_ADDR_0_LI(gai_11_35_pit_pump_conn_type), // pit_pump_conn_type
/* ID  36 */ UC_ADDR_0_LI(gai_11_36_pit_pump_ctr_source), // pit_pump_ctr_source
/* ID  37 */ UC_ADDR_0_LI(gai_11_37_pit_alarms1), // pit_alarms1
/* ID  38 */ UC_ADDR_0_LI(gai_11_38_pit_alarms2), // pit_alarms2
/* ID  39 */ UC_ADDR_0_LI(gai_11_39_pit_alarms3), // pit_alarms3
/* ID  40 */ UC_ADDR_0_LI(gai_11_40_pit_warn1), // pit_warn1
/* ID  41 */ UC_ADDR_0_LI(gai_11_41_pit_warn2), // pit_warn2
/* ID  42 */ UC_ADDR_0_LI(gai_11_42_pit_warn3), // pit_warn3
/* ID  43 */ UC_ADDR_0_LI(gai_11_43_event_log_latest_id), // event_log_latest_id
/* ID  44 */ UC_ADDR_0_LI(gai_11_44_interlock_remain_time), // 
/* ID  45 */ UC_ADDR_0_LI(gai_11_45_user_ana_in_1), // user_ana_in_1
/* ID  46 */ UC_ADDR_0_LI(gai_11_46_user_ana_in_2), // user_ana_in_2
/* ID  47 */ UC_ADDR_0_LI(gai_11_47_user_ana_in_3), // user_ana_in_3
/* ID  48 */ UC_ADDR_0_LI(gai_11_48_pit_rand_start_level_band), // 
/* ID  49 */ UC_ADDR_0_LI(gai_11_49_pit_0_pumps_opr_time_yesterday), // pit_0_pumps_opr_time_yesterday
/* ID  50 */ UC_ADDR_0_LI(gai_11_50_pit_1_pumps_opr_time_yesterday), // pit_1_pumps_opr_time_yesterday
/* ID  51 */ UC_ADDR_0_LI(gai_11_51_pit_0_pumps_opr_time_today), // pit_0_pumps_opr_time_today
/* ID  52 */ UC_ADDR_0_LI(gai_11_52_pit_1_pumps_opr_time_today), // pit_1_pumps_opr_time_today
/* ID  53 */ UC_ADDR_0_LI(gai_11_53_discharge_pressure), // Discharge pressure
/* ID  54 */ NA,
/* ID  55 */ UC_ADDR_0_LI(gai_11_55_pit_alarms4), // 
/* ID  56 */ UC_ADDR_0_LI(gai_11_56_pit_warn4), // 
/* ID  57 */ NA,
/* ID  58 */ NA,
/* ID  59 */ UC_ADDR_0_LI(gai_11_59_power_on_counter), // power_on_counter (not in profile)
/* ID  60 */ UC_ADDR_0_LI(gai_11_60_p1_opr_time_yesterday), // p1_opr_time_yesterday
/* ID  61 */ UC_ADDR_0_LI(gai_11_61_p1_opr_time_today), // p1_opr_time_today
/* ID  62 */ UC_ADDR_0_LI(gai_11_62_p1_latest_runtime), // pump_1_latest_runtime
/* ID  63 */ UC_ADDR_0_LI(gai_11_63_p1_start_cnt_yesterday), // p1_start_cnt_yesterday
/* ID  64 */ UC_ADDR_0_LI(gai_11_64_p1_start_cnt_today), // p1_start_cnt_today
/* ID  65 */ UC_ADDR_0_LI(gai_11_65_p1_starts_pr_hour), // pump_1_starts_pr_hour
/* ID  66 */ UC_ADDR_0_LI(gai_11_66_p1_flow), // pump_1_calculated_flow_filtered
/* ID  67 */ UC_ADDR_0_LI(gai_11_67_p1_latest_flow), // pump_1_calculated_flow_raw
/* ID  68 */ UC_ADDR_0_LI(gai_11_68_p1_current), // 
/* ID  69 */ UC_ADDR_0_LI(gai_11_69_p1_latest_current), // p1_latest_current
/* ID  70 */ UC_ADDR_0_LI(gai_11_70_p1_insulation), // 
/* ID  71 */ UC_ADDR_0_LI(gai_11_71_p1_water_in_oil), // pump_1_water_in_oil
/* ID  72 */ UC_ADDR_0_LI(gai_11_72_p1_motor_temp1), // pump_1_temperature
/* ID  73 */ NA,
/* ID  74 */ UC_ADDR_0_LI(gai_11_74_p1_cosine_phi), // 
/* ID  75 */ UC_ADDR_0_LI(gai_11_75_p1_freq), // 
/* ID  76 */ UC_ADDR_0_LI(gai_11_76_p1_mode_and_connect), // p1_mode_and_connect
/* ID  77 */ UC_ADDR_0_LI(gai_11_77_p1_alarms1), // p1_alarms1
/* ID  78 */ UC_ADDR_0_LI(gai_11_78_p1_alarms2), // p1_alarms2
/* ID  79 */ UC_ADDR_0_LI(gai_11_79_p1_alarms3), // p1_alarms3
/* ID  80 */ UC_ADDR_0_LI(gai_11_80_p1_warn1), // p1_warn1
/* ID  81 */ UC_ADDR_0_LI(gai_11_81_p1_warn2), // p1_warn2
/* ID  82 */ UC_ADDR_0_LI(gai_11_82_p1_warn3), // p1_warn3
/* ID  83 */ UC_ADDR_0_LI(gai_11_83_p1_voltage), // 
/* ID  84 */ NA,
/* ID  85 */ UC_ADDR_0_LI(gai_11_85_p1_vfd_mode), // 
/* ID  86 */ UC_ADDR_0_LI(gai_11_86_p1_torque), // 
/* ID  87 */ UC_ADDR_0_LI(gai_11_87_p1_i_asym), // 
/* ID  88 */ UC_ADDR_0_LI(gai_11_88_p1_alarms4), // p1_alarms4
/* ID  89 */ UC_ADDR_0_LI(gai_11_89_p1_warn4), // p1_warn4
/* ID  90 */ UC_ADDR_0_LI(gai_11_90_p2_opr_time_yesterday), // p2_opr_time_yesterday
/* ID  91 */ UC_ADDR_0_LI(gai_11_91_p2_opr_time_today), // p2_opr_time_today
/* ID  92 */ UC_ADDR_0_LI(gai_11_92_p2_latest_runtime), // pump_2_latest_runtime
/* ID  93 */ UC_ADDR_0_LI(gai_11_93_p2_start_cnt_yesterday), // p2_start_cnt_yesterday
/* ID  94 */ UC_ADDR_0_LI(gai_11_94_p2_start_cnt_today), // p2_start_cnt_today
/* ID  95 */ UC_ADDR_0_LI(gai_11_95_p2_starts_pr_hour), // pump_2_starts_pr_hour
/* ID  96 */ UC_ADDR_0_LI(gai_11_96_p2_flow), // pump_2_calculated_flow_filtered
/* ID  97 */ UC_ADDR_0_LI(gai_11_97_p2_latest_flow), // pump_2_calculated_flow_raw
/* ID  98 */ UC_ADDR_0_LI(gai_11_98_p2_current), // 
/* ID  99 */ UC_ADDR_0_LI(gai_11_99_p2_latest_current), // p2_latest_current
/* ID 100 */ UC_ADDR_0_LI(gai_11_100_p2_insulation), // 
/* ID 101 */ UC_ADDR_0_LI(gai_11_101_p2_water_in_oil), // pump_2_water_in_oil
/* ID 102 */ UC_ADDR_0_LI(gai_11_102_p2_motor_temp), // pump_2_temperature
/* ID 103 */ NA,
/* ID 104 */ UC_ADDR_0_LI(gai_11_104_p2_cosine_phi), // 
/* ID 105 */ UC_ADDR_0_LI(gai_11_105_p2_freq), // 
/* ID 106 */ UC_ADDR_0_LI(gai_11_106_p2_mode_and_connect), // p2_mode_and_connect
/* ID 107 */ UC_ADDR_0_LI(gai_11_107_p2_alarms1), // p2_alarms1
/* ID 108 */ UC_ADDR_0_LI(gai_11_108_p2_alarms2), // p2_alarms2
/* ID 109 */ UC_ADDR_0_LI(gai_11_109_p2_alarms3), // p2_alarms3
/* ID 110 */ UC_ADDR_0_LI(gai_11_110_p2_warn1), // p2_warn1
/* ID 111 */ UC_ADDR_0_LI(gai_11_111_p2_warn2), // p2_warn2
/* ID 112 */ UC_ADDR_0_LI(gai_11_112_p2_warn3), // p2_warn3
/* ID 113 */ UC_ADDR_0_LI(gai_11_113_p2_voltage), // 
/* ID 114 */ NA,
/* ID 115 */ UC_ADDR_0_LI(gai_11_115_p2_vfd_mode), // 
/* ID 116 */ UC_ADDR_0_LI(gai_11_116_p2_torque), // 
/* ID 117 */ UC_ADDR_0_LI(gai_11_117_p2_i_asym), // 
/* ID 118 */ UC_ADDR_0_LI(gai_11_118_p2_alarms4), // p2_alarms4
/* ID 119 */ UC_ADDR_0_LI(gai_11_119_p2_warn4), // p2_warn4
/* ID 120 */ UC_ADDR_0_LI(gai_11_120_p3_opr_time_yesterday), // p3_opr_time_yesterday
/* ID 121 */ UC_ADDR_0_LI(gai_11_121_p3_opr_time_today), // p3_opr_time_today
/* ID 122 */ UC_ADDR_0_LI(gai_11_122_p3_latest_runtime), // pump_3_latest_runtime
/* ID 123 */ UC_ADDR_0_LI(gai_11_123_p3_start_cnt_yesterday), // p3_start_cnt_yesterday
/* ID 124 */ UC_ADDR_0_LI(gai_11_124_p3_start_cnt_today), // p3_start_cnt_today
/* ID 125 */ UC_ADDR_0_LI(gai_11_125_p3_starts_pr_hour), // pump_3_starts_pr_hour
/* ID 126 */ UC_ADDR_0_LI(gai_11_126_p3_flow), // pump_3_calculated_flow_filtered
/* ID 127 */ UC_ADDR_0_LI(gai_11_127_p3_latest_flow), // pump_3_calculated_flow_raw
/* ID 128 */ UC_ADDR_0_LI(gai_11_128_p3_current), // 
/* ID 129 */ UC_ADDR_0_LI(gai_11_129_p3_latest_current), // p3_latest_current
/* ID 130 */ UC_ADDR_0_LI(gai_11_130_p3_insulation), // 
/* ID 131 */ UC_ADDR_0_LI(gai_11_131_p3_water_in_oil), // pump_3_water_in_oil
/* ID 132 */ UC_ADDR_0_LI(gai_11_132_p3_motor_temp), // pump_3_temperature
/* ID 133 */ NA,
/* ID 134 */ UC_ADDR_0_LI(gai_11_134_p3_cosine_phi), // 
/* ID 135 */ UC_ADDR_0_LI(gai_11_135_p3_freq), // 
/* ID 136 */ UC_ADDR_0_LI(gai_11_136_p3_mode_and_connect), // p3_mode_and_connect
/* ID 137 */ UC_ADDR_0_LI(gai_11_137_p3_alarms1), // p3_alarms1
/* ID 138 */ UC_ADDR_0_LI(gai_11_138_p3_alarms2), // p3_alarms2
/* ID 139 */ UC_ADDR_0_LI(gai_11_139_p3_alarms3), // p3_alarms3
/* ID 140 */ UC_ADDR_0_LI(gai_11_140_p3_warn1), // p3_warn1
/* ID 141 */ UC_ADDR_0_LI(gai_11_141_p3_warn2), // p3_warn2
/* ID 142 */ UC_ADDR_0_LI(gai_11_142_p3_warn3), // p3_warn3
/* ID 143 */ UC_ADDR_0_LI(gai_11_143_p3_voltage), // 
/* ID 144 */ NA,
/* ID 145 */ UC_ADDR_0_LI(gai_11_145_p3_vfd_mode), // 
/* ID 146 */ UC_ADDR_0_LI(gai_11_146_p3_torque), // 
/* ID 147 */ UC_ADDR_0_LI(gai_11_147_p3_i_asym), // 
/* ID 148 */ UC_ADDR_0_LI(gai_11_148_p3_alarms4), // p3_alarms4
/* ID 149 */ UC_ADDR_0_LI(gai_11_149_p3_warn4), // p3_warn4
/* ID 150 */ UC_ADDR_0_LI(gai_11_150_p4_opr_time_yesterday), // p4_opr_time_yesterday
/* ID 151 */ UC_ADDR_0_LI(gai_11_151_p4_opr_time_today), // p4_opr_time_today
/* ID 152 */ UC_ADDR_0_LI(gai_11_152_p4_latest_runtime), // pump_4_latest_runtime
/* ID 153 */ UC_ADDR_0_LI(gai_11_153_p4_start_cnt_yesterday), // p4_start_cnt_yesterday
/* ID 154 */ UC_ADDR_0_LI(gai_11_154_p4_start_cnt_today), // p4_start_cnt_today
/* ID 155 */ UC_ADDR_0_LI(gai_11_155_p4_starts_pr_hour), // pump_4_starts_pr_hour
/* ID 156 */ UC_ADDR_0_LI(gai_11_156_p4_flow), // pump_4_calculated_flow_filtered
/* ID 157 */ UC_ADDR_0_LI(gai_11_157_p4_latest_flow), // pump_4_calculated_flow_raw
/* ID 158 */ UC_ADDR_0_LI(gai_11_158_p4_current), // 
/* ID 159 */ UC_ADDR_0_LI(gai_11_159_p4_latest_current), // p4_latest_current
/* ID 160 */ UC_ADDR_0_LI(gai_11_160_p4_insulation), // 
/* ID 161 */ UC_ADDR_0_LI(gai_11_161_p4_water_in_oil), // pump_4_water_in_oil
/* ID 162 */ UC_ADDR_0_LI(gai_11_162_p4_motor_temp), // pump_4_temperature
/* ID 163 */ NA,
/* ID 164 */ UC_ADDR_0_LI(gai_11_164_p4_cosine_phi), // 
/* ID 165 */ UC_ADDR_0_LI(gai_11_165_p4_freq), // 
/* ID 166 */ UC_ADDR_0_LI(gai_11_166_p4_mode_and_connect), // p4_mode_and_connect
/* ID 167 */ UC_ADDR_0_LI(gai_11_167_p4_alarms1), // p4_alarms1
/* ID 168 */ UC_ADDR_0_LI(gai_11_168_p4_alarms2), // p4_alarms2
/* ID 169 */ UC_ADDR_0_LI(gai_11_169_p4_alarms3), // p4_alarms3
/* ID 170 */ UC_ADDR_0_LI(gai_11_170_p4_warn1), // p4_warn1
/* ID 171 */ UC_ADDR_0_LI(gai_11_171_p4_warn2), // p4_warn2
/* ID 172 */ UC_ADDR_0_LI(gai_11_172_p4_warn3), // p4_warn3
/* ID 173 */ UC_ADDR_0_LI(gai_11_173_p4_voltage), // 
/* ID 174 */ NA,
/* ID 175 */ UC_ADDR_0_LI(gai_11_175_p4_vfd_mode), // 
/* ID 176 */ UC_ADDR_0_LI(gai_11_176_p4_torque), // 
/* ID 177 */ UC_ADDR_0_LI(gai_11_177_p4_i_asym), // 
/* ID 178 */ UC_ADDR_0_LI(gai_11_178_p4_alarms4), // p4_alarms4
/* ID 179 */ UC_ADDR_0_LI(gai_11_179_p4_warn4), // p4_warn4
/* ID 180 */ UC_ADDR_0_LI(gai_11_180_p5_opr_time_yesterday), // p5_opr_time_yesterday
/* ID 181 */ UC_ADDR_0_LI(gai_11_181_p5_opr_time_today), // p5_opr_time_today
/* ID 182 */ UC_ADDR_0_LI(gai_11_182_p5_latest_runtime), // pump_5_latest_runtime
/* ID 183 */ UC_ADDR_0_LI(gai_11_183_p5_start_cnt_yesterday), // p5_start_cnt_yesterday
/* ID 184 */ UC_ADDR_0_LI(gai_11_184_p5_start_cnt_today), // p5_start_cnt_today
/* ID 185 */ UC_ADDR_0_LI(gai_11_185_p5_starts_pr_hour), // pump_5_starts_pr_hour
/* ID 186 */ UC_ADDR_0_LI(gai_11_186_p5_flow), // pump_5_calculated_flow_filtered
/* ID 187 */ UC_ADDR_0_LI(gai_11_187_p5_latest_flow), // pump_5_calculated_flow_raw
/* ID 188 */ UC_ADDR_0_LI(gai_11_188_p5_current), // 
/* ID 189 */ UC_ADDR_0_LI(gai_11_189_p5_latest_current), // p5_latest_current
/* ID 190 */ UC_ADDR_0_LI(gai_11_190_p5_insulation), // 
/* ID 191 */ UC_ADDR_0_LI(gai_11_191_p5_water_in_oil), // pump_5_water_in_oil
/* ID 192 */ UC_ADDR_0_LI(gai_11_192_p5_motor_temp), // pump_5_temperature
/* ID 193 */ NA,
/* ID 194 */ UC_ADDR_0_LI(gai_11_194_p5_cosine_phi), // 
/* ID 195 */ UC_ADDR_0_LI(gai_11_195_p5_freq), // 
/* ID 196 */ UC_ADDR_0_LI(gai_11_196_p5_mode_and_connect), // p5_mode_and_connect
/* ID 197 */ UC_ADDR_0_LI(gai_11_197_p5_alarms1), // p5_alarms1
/* ID 198 */ UC_ADDR_0_LI(gai_11_198_p5_alarms2), // p5_alarms2
/* ID 199 */ UC_ADDR_0_LI(gai_11_199_p5_alarms3), // p5_alarms3
/* ID 200 */ UC_ADDR_0_LI(gai_11_200_p5_warn1), // p5_warn1
/* ID 201 */ UC_ADDR_0_LI(gai_11_201_p5_warn2), // p5_warn2
/* ID 202 */ UC_ADDR_0_LI(gai_11_202_p5_warn3), // p5_warn3
/* ID 203 */ UC_ADDR_0_LI(gai_11_203_p5_voltage), // 
/* ID 204 */ NA,
/* ID 205 */ UC_ADDR_0_LI(gai_11_205_p5_vfd_mode), // 
/* ID 206 */ UC_ADDR_0_LI(gai_11_206_p5_torque), // 
/* ID 207 */ UC_ADDR_0_LI(gai_11_207_p5_i_asym), // 
/* ID 208 */ UC_ADDR_0_LI(gai_11_208_p5_alarms4), // p5_alarms4
/* ID 209 */ UC_ADDR_0_LI(gai_11_209_p5_warn4), // p5_warn4
/* ID 210 */ UC_ADDR_0_LI(gai_11_210_p6_opr_time_yesterday), // p6_opr_time_yesterday
/* ID 211 */ UC_ADDR_0_LI(gai_11_211_p6_opr_time_today), // p6_opr_time_today
/* ID 212 */ UC_ADDR_0_LI(gai_11_212_p6_latest_runtime), // pump_6_latest_runtime
/* ID 213 */ UC_ADDR_0_LI(gai_11_213_p6_start_cnt_yesterday), // p6_start_cnt_yesterday
/* ID 214 */ UC_ADDR_0_LI(gai_11_214_p6_start_cnt_today), // p6_start_cnt_today
/* ID 215 */ UC_ADDR_0_LI(gai_11_215_p6_starts_pr_hour), // pump_6_starts_pr_hour
/* ID 216 */ UC_ADDR_0_LI(gai_11_216_p6_flow), // pump_6_calculated_flow_filtered
/* ID 217 */ UC_ADDR_0_LI(gai_11_217_p6_latest_flow), // pump_6_calculated_flow_raw
/* ID 218 */ UC_ADDR_0_LI(gai_11_218_p6_current), // 
/* ID 219 */ UC_ADDR_0_LI(gai_11_219_p6_latest_current), // p6_latest_current
/* ID 220 */ UC_ADDR_0_LI(gai_11_220_p6_insulation), // 
/* ID 221 */ UC_ADDR_0_LI(gai_11_221_p6_water_in_oil), // pump_6_water_in_oil
/* ID 222 */ UC_ADDR_0_LI(gai_11_222_p6_motor_temp), // pump_6_temperature
/* ID 223 */ NA,
/* ID 224 */ UC_ADDR_0_LI(gai_11_224_p6_cosine_phi), // 
/* ID 225 */ UC_ADDR_0_LI(gai_11_225_p6_freq), // 
/* ID 226 */ UC_ADDR_0_LI(gai_11_226_p6_mode_and_connect), // p6_mode_and_connect
/* ID 227 */ UC_ADDR_0_LI(gai_11_227_p6_alarms1), // p6_alarms1
/* ID 228 */ UC_ADDR_0_LI(gai_11_228_p6_alarms2), // p6_alarms2
/* ID 229 */ UC_ADDR_0_LI(gai_11_229_p6_alarms3), // p6_alarms3
/* ID 230 */ UC_ADDR_0_LI(gai_11_230_p6_warn1), // p6_warn1
/* ID 231 */ UC_ADDR_0_LI(gai_11_231_p6_warn2), // p6_warn2
/* ID 232 */ UC_ADDR_0_LI(gai_11_232_p6_warn3), // p6_warn3
/* ID 233 */ UC_ADDR_0_LI(gai_11_233_p6_voltage), // 
/* ID 234 */ NA,
/* ID 235 */ UC_ADDR_0_LI(gai_11_235_p6_vfd_mode), // 
/* ID 236 */ UC_ADDR_0_LI(gai_11_236_p6_torque), // 
/* ID 237 */ UC_ADDR_0_LI(gai_11_237_p6_i_asym), // 
/* ID 238 */ UC_ADDR_0_LI(gai_11_238_p6_alarms4), // p6_alarms4
/* ID 239 */ UC_ADDR_0_LI(gai_11_239_p6_warn4), // p6_warn4
/* ID 240 */ NA,
/* ID 241 */ NA,
/* ID 242 */ NA,
/* ID 243 */ NA,
/* ID 244 */ NA,
/* ID 245 */ NA,
/* ID 246 */ NA,
/* ID 247 */ NA,
/* ID 248 */ NA,
/* ID 249 */ NA,
/* ID 250 */ NA,
/* ID 251 */ UC_ADDR_0_LI(gai_11_251_class_11_dummy_1), // Dummy par, used for debug
/* ID 252 */ UC_ADDR_0_LI(gai_11_252_class_11_dummy_2), // Dummy par, used for debug
/* ID 253 */ UC_ADDR_0_LI(gai_11_253_class_11_dummy_3) // Dummy par, used for debug
};

/**************************************************************************
 INFO TABLE
**************************************************************************/
const ID_INFO meas16_info_tab[] = 
{
/* ID   0 */ COMMON_INFO + COM_INDEX_EXT_HEAD_DOT01M, // Actual pit level
/* ID   1 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // float_switch_water_level (number)
/* ID   2 */ COMMON_INFO + COM_INDEX_EXT_HEAD_DOT01M, // Pit depth (config)
/* ID   3 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // Flow (TBD)
/* ID   4 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // Flow (TBD)
/* ID   5 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // Flow (TBD)
/* ID   6 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // Flow (TBD)
/* ID   7 */ COMMON_INFO + COM_INDEX_EXT_ENERGY_DOT1KWH, // pit_energy_yesterday
/* ID   8 */ COMMON_INFO + COM_INDEX_EXT_ENERGY_DOT1KWH, // pit_energy_today
/* ID   9 */ COMMON_INFO + COM_INDEX_EXT_EFFICIENCY_1WHM3, // Efficiency
/* ID  10 */ COMMON_INFO + COM_INDEX_EXT_VOLUME_DOT1M3, // pit_pumped_volume_yesterday
/* ID  11 */ COMMON_INFO + COM_INDEX_EXT_VOLUME_DOT1M3, // pit_pumped_volume_today
/* ID  12 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_2_pumps_opr_time_yesterday
/* ID  13 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_3_pumps_opr_time_yesterday
/* ID  14 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_4_pumps_opr_time_yesterday
/* ID  15 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_5_pumps_opr_time_yesterday
/* ID  16 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_6_pumps_opr_time_yesterday
/* ID  17 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_2_pumps_opr_time_today
/* ID  18 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_3_pumps_opr_time_today
/* ID  19 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_4_pumps_opr_time_today
/* ID  20 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_5_pumps_opr_time_today
/* ID  21 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_6_pumps_opr_time_today
/* ID  22 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // mixer_starts_pr_hour
/* ID  23 */ COMMON_INFO+  COM_INDEX_EXT_OVER_VOLUME_DOT1M3, // overflow volume
/* ID  24 */ COMMON_INFO + COM_INDEX_EXT_VOLUME_DOT1M3, // pit_overflow_volume_yesterday
/* ID  25 */ COMMON_INFO + COM_INDEX_EXT_VOLUME_DOT1M3, // pit_overflow_volume_today
/* ID  26 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // overflow time
/* ID  27 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_overflow_time_yesterday
/* ID  28 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_overflow_time_today
/* ID  29 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // overflow_count
/* ID  30 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // pit_overflow_cnt_yesterday
/* ID  31 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // pit_overflow_cnt_today
/* ID  32 */ BITVAR_255, // pit_pump_mode
/* ID  33 */ BITVAR_255, // pit_pump_fault
/* ID  34 */ BITVAR_255, // pit_pump_mon_fault
/* ID  35 */ BITVAR_255, // pit_pump_conn_type
/* ID  36 */ BITVAR_255, // pit_pump_ctr_source
/* ID  37 */ BITVAR_255, // pit_alarms1
/* ID  38 */ BITVAR_255, // pit_alarms2
/* ID  39 */ BITVAR_255, // pit_alarms3
/* ID  40 */ BITVAR_255, // pit_warn1
/* ID  41 */ BITVAR_255, // pit_warn2
/* ID  42 */ BITVAR_255, // pit_warn3
/* ID  43 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // event_log_latest_id
/* ID  44 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // 
/* ID  45 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // user_ana_in_1
/* ID  46 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // user_ana_in_2
/* ID  47 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // user_ana_in_3
/* ID  48 */ COMMON_INFO + COM_INDEX_EXT_HEAD_DOT01M, // 
/* ID  49 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_0_pumps_opr_time_yesterday
/* ID  50 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_1_pumps_opr_time_yesterday
/* ID  51 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_0_pumps_opr_time_today
/* ID  52 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_1_pumps_opr_time_today
/* ID  53 */ COMMON_INFO + COM_INDEX_EXT_PRESSURE_1MBAR, // Discharge pressure
/* ID  54 */ NI,
/* ID  55 */ BITVAR_255, // 
/* ID  56 */ BITVAR_255, // 
/* ID  57 */ NI,
/* ID  58 */ NI,
/* ID  59 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // power_on_counter (not in profile)
/* ID  60 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p1_opr_time_yesterday
/* ID  61 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p1_opr_time_today
/* ID  62 */ COMMON_INFO + COM_INDEX_EXT_TIME_1SEC, // pump_1_latest_runtime
/* ID  63 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p1_start_cnt_yesterday
/* ID  64 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p1_start_cnt_today
/* ID  65 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // pump_1_starts_pr_hour
/* ID  66 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // pump_1_calculated_flow_filtered
/* ID  67 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // pump_1_calculated_flow_raw
/* ID  68 */ COMMON_INFO + COM_INDEX_EXT_CURRENT_DOT1A, // 
/* ID  69 */ COMMON_INFO + COM_INDEX_EXT_CURRENT_DOT1A, // p1_latest_current
/* ID  70 */ COMMON_INFO + COM_INDEX_EXT_RESISTANCE_10KOHM, // 
/* ID  71 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // pump_1_water_in_oil
/* ID  72 */ COMMON_INFO + COM_INDEX_EXT_TEMPERATURE_1C, // pump_1_temperature
/* ID  73 */ NI,
/* ID  74 */ COMMON_INFO + COM_INDEX_EXT_GAIN_DOT01, // 
/* ID  75 */ COMMON_INFO + COM_INDEX_EXT_FREQUENCY_001HZ, // 
/* ID  76 */ BITVAR_255, // p1_mode_and_connect
/* ID  77 */ BITVAR_255, // p1_alarms1
/* ID  78 */ BITVAR_255, // p1_alarms2
/* ID  79 */ BITVAR_255, // p1_alarms3
/* ID  80 */ BITVAR_255, // p1_warn1
/* ID  81 */ BITVAR_255, // p1_warn2
/* ID  82 */ BITVAR_255, // p1_warn3
/* ID  83 */ COMMON_INFO + COM_INDEX_EXT_VOLTAGE_DOT1V, // 
/* ID  84 */ NI,
/* ID  85 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // 
/* ID  86 */ COMMON_INFO + COM_INDEX_EXT_TORQUE_DOT1NM, // 
/* ID  87 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // 
/* ID  88 */ BITVAR_255, // p1_alarms4
/* ID  89 */ BITVAR_255, // p1_warn4
/* ID  90 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p2_opr_time_yesterday
/* ID  91 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p2_opr_time_today
/* ID  92 */ COMMON_INFO + COM_INDEX_EXT_TIME_1SEC, // pump_2_latest_runtime
/* ID  93 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p2_start_cnt_yesterday
/* ID  94 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p2_start_cnt_today
/* ID  95 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // pump_2_starts_pr_hour
/* ID  96 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // pump_2_calculated_flow_filtered
/* ID  97 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // pump_2_calculated_flow_raw
/* ID  98 */ COMMON_INFO + COM_INDEX_EXT_CURRENT_DOT1A, // 
/* ID  99 */ COMMON_INFO + COM_INDEX_EXT_CURRENT_DOT1A, // p2_latest_current
/* ID 100 */ COMMON_INFO + COM_INDEX_EXT_RESISTANCE_10KOHM, // 
/* ID 101 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // pump_2_water_in_oil
/* ID 102 */ COMMON_INFO + COM_INDEX_EXT_TEMPERATURE_1C, // pump_2_temperature
/* ID 103 */ NI,
/* ID 104 */ COMMON_INFO + COM_INDEX_EXT_GAIN_DOT01, // 
/* ID 105 */ COMMON_INFO + COM_INDEX_EXT_FREQUENCY_001HZ, // 
/* ID 106 */ BITVAR_255, // p2_mode_and_connect
/* ID 107 */ BITVAR_255, // p2_alarms1
/* ID 108 */ BITVAR_255, // p2_alarms2
/* ID 109 */ BITVAR_255, // p2_alarms3
/* ID 110 */ BITVAR_255, // p2_warn1
/* ID 111 */ BITVAR_255, // p2_warn2
/* ID 112 */ BITVAR_255, // p2_warn3
/* ID 113 */ COMMON_INFO + COM_INDEX_EXT_VOLTAGE_DOT1V, // 
/* ID 114 */ NI,
/* ID 115 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // 
/* ID 116 */ COMMON_INFO + COM_INDEX_EXT_TORQUE_DOT1NM, // 
/* ID 117 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // 
/* ID 118 */ BITVAR_255, // p2_alarms4
/* ID 119 */ BITVAR_255, // p2_warn4
/* ID 120 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p3_opr_time_yesterday
/* ID 121 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p3_opr_time_today
/* ID 122 */ COMMON_INFO + COM_INDEX_EXT_TIME_1SEC, // pump_3_latest_runtime
/* ID 123 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p3_start_cnt_yesterday
/* ID 124 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p3_start_cnt_today
/* ID 125 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // pump_3_starts_pr_hour
/* ID 126 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // pump_3_calculated_flow_filtered
/* ID 127 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // pump_3_calculated_flow_raw
/* ID 128 */ COMMON_INFO + COM_INDEX_EXT_CURRENT_DOT1A, // 
/* ID 129 */ COMMON_INFO + COM_INDEX_EXT_CURRENT_DOT1A, // p3_latest_current
/* ID 130 */ COMMON_INFO + COM_INDEX_EXT_RESISTANCE_10KOHM, // 
/* ID 131 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // pump_3_water_in_oil
/* ID 132 */ COMMON_INFO + COM_INDEX_EXT_TEMPERATURE_1C, // pump_3_temperature
/* ID 133 */ NI,
/* ID 134 */ COMMON_INFO + COM_INDEX_EXT_GAIN_DOT01, // 
/* ID 135 */ COMMON_INFO + COM_INDEX_EXT_FREQUENCY_001HZ, // 
/* ID 136 */ BITVAR_255, // p3_mode_and_connect
/* ID 137 */ BITVAR_255, // p3_alarms1
/* ID 138 */ BITVAR_255, // p3_alarms2
/* ID 139 */ BITVAR_255, // p3_alarms3
/* ID 140 */ BITVAR_255, // p3_warn1
/* ID 141 */ BITVAR_255, // p3_warn2
/* ID 142 */ BITVAR_255, // p3_warn3
/* ID 143 */ COMMON_INFO + COM_INDEX_EXT_VOLTAGE_DOT1V, // 
/* ID 144 */ NI,
/* ID 145 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // 
/* ID 146 */ COMMON_INFO + COM_INDEX_EXT_TORQUE_DOT1NM, // 
/* ID 147 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // 
/* ID 148 */ BITVAR_255, // p3_alarms4
/* ID 149 */ BITVAR_255, // p3_warn4
/* ID 150 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p4_opr_time_yesterday
/* ID 151 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p4_opr_time_today
/* ID 152 */ COMMON_INFO + COM_INDEX_EXT_TIME_1SEC, // pump_4_latest_runtime
/* ID 153 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p4_start_cnt_yesterday
/* ID 154 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p4_start_cnt_today
/* ID 155 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // pump_4_starts_pr_hour
/* ID 156 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // pump_4_calculated_flow_filtered
/* ID 157 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // pump_4_calculated_flow_raw
/* ID 158 */ COMMON_INFO + COM_INDEX_EXT_CURRENT_DOT1A, // 
/* ID 159 */ COMMON_INFO + COM_INDEX_EXT_CURRENT_DOT1A, // p4_latest_current
/* ID 160 */ COMMON_INFO + COM_INDEX_EXT_RESISTANCE_10KOHM, // 
/* ID 161 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // pump_4_water_in_oil
/* ID 162 */ COMMON_INFO + COM_INDEX_EXT_TEMPERATURE_1C, // pump_4_temperature
/* ID 163 */ NI,
/* ID 164 */ COMMON_INFO + COM_INDEX_EXT_GAIN_DOT01, // 
/* ID 165 */ COMMON_INFO + COM_INDEX_EXT_FREQUENCY_001HZ, // 
/* ID 166 */ BITVAR_255, // p4_mode_and_connect
/* ID 167 */ BITVAR_255, // p4_alarms1
/* ID 168 */ BITVAR_255, // p4_alarms2
/* ID 169 */ BITVAR_255, // p4_alarms3
/* ID 170 */ BITVAR_255, // p4_warn1
/* ID 171 */ BITVAR_255, // p4_warn2
/* ID 172 */ BITVAR_255, // p4_warn3
/* ID 173 */ COMMON_INFO + COM_INDEX_EXT_VOLTAGE_DOT1V, // 
/* ID 174 */ NI,
/* ID 175 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // 
/* ID 176 */ COMMON_INFO + COM_INDEX_EXT_TORQUE_DOT1NM, // 
/* ID 177 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // 
/* ID 178 */ BITVAR_255, // p4_alarms4
/* ID 179 */ BITVAR_255, // p4_warn4
/* ID 180 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p5_opr_time_yesterday
/* ID 181 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p5_opr_time_today
/* ID 182 */ COMMON_INFO + COM_INDEX_EXT_TIME_1SEC, // pump_5_latest_runtime
/* ID 183 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p5_start_cnt_yesterday
/* ID 184 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p5_start_cnt_today
/* ID 185 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // pump_5_starts_pr_hour
/* ID 186 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // pump_5_calculated_flow_filtered
/* ID 187 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // pump_5_calculated_flow_raw
/* ID 188 */ COMMON_INFO + COM_INDEX_EXT_CURRENT_DOT1A, // 
/* ID 189 */ COMMON_INFO + COM_INDEX_EXT_CURRENT_DOT1A, // p5_latest_current
/* ID 190 */ COMMON_INFO + COM_INDEX_EXT_RESISTANCE_10KOHM, // 
/* ID 191 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // pump_5_water_in_oil
/* ID 192 */ COMMON_INFO + COM_INDEX_EXT_TEMPERATURE_1C, // pump_5_temperature
/* ID 193 */ NI,
/* ID 194 */ COMMON_INFO + COM_INDEX_EXT_GAIN_DOT01, // 
/* ID 195 */ COMMON_INFO + COM_INDEX_EXT_FREQUENCY_001HZ, // 
/* ID 196 */ BITVAR_255, // p5_mode_and_connect
/* ID 197 */ BITVAR_255, // p5_alarms1
/* ID 198 */ BITVAR_255, // p5_alarms2
/* ID 199 */ BITVAR_255, // p5_alarms3
/* ID 200 */ BITVAR_255, // p5_warn1
/* ID 201 */ BITVAR_255, // p5_warn2
/* ID 202 */ BITVAR_255, // p5_warn3
/* ID 203 */ COMMON_INFO + COM_INDEX_EXT_VOLTAGE_DOT1V, // 
/* ID 204 */ NI,
/* ID 205 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // 
/* ID 206 */ COMMON_INFO + COM_INDEX_EXT_TORQUE_DOT1NM, // 
/* ID 207 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // 
/* ID 208 */ BITVAR_255, // p5_alarms4
/* ID 209 */ BITVAR_255, // p5_warn4
/* ID 210 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p6_opr_time_yesterday
/* ID 211 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p6_opr_time_today
/* ID 212 */ COMMON_INFO + COM_INDEX_EXT_TIME_1SEC, // pump_6_latest_runtime
/* ID 213 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p6_start_cnt_yesterday
/* ID 214 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p6_start_cnt_today
/* ID 215 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // pump_6_starts_pr_hour
/* ID 216 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // pump_6_calculated_flow_filtered
/* ID 217 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LS, // pump_6_calculated_flow_raw
/* ID 218 */ COMMON_INFO + COM_INDEX_EXT_CURRENT_DOT1A, // 
/* ID 219 */ COMMON_INFO + COM_INDEX_EXT_CURRENT_DOT1A, // p6_latest_current
/* ID 220 */ COMMON_INFO + COM_INDEX_EXT_RESISTANCE_10KOHM, // 
/* ID 221 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // pump_6_water_in_oil
/* ID 222 */ COMMON_INFO + COM_INDEX_EXT_TEMPERATURE_1C, // pump_6_temperature
/* ID 223 */ NI,
/* ID 224 */ COMMON_INFO + COM_INDEX_EXT_GAIN_DOT01, // 
/* ID 225 */ COMMON_INFO + COM_INDEX_EXT_FREQUENCY_001HZ, // 
/* ID 226 */ BITVAR_255, // p6_mode_and_connect
/* ID 227 */ BITVAR_255, // p6_alarms1
/* ID 228 */ BITVAR_255, // p6_alarms2
/* ID 229 */ BITVAR_255, // p6_alarms3
/* ID 230 */ BITVAR_255, // p6_warn1
/* ID 231 */ BITVAR_255, // p6_warn2
/* ID 232 */ BITVAR_255, // p6_warn3
/* ID 233 */ COMMON_INFO + COM_INDEX_EXT_VOLTAGE_DOT1V, // 
/* ID 234 */ NI,
/* ID 235 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // 
/* ID 236 */ COMMON_INFO + COM_INDEX_EXT_TORQUE_DOT1NM, // 
/* ID 237 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // 
/* ID 238 */ BITVAR_255, // p6_alarms4
/* ID 239 */ BITVAR_255, // p6_warn4
/* ID 240 */ NI,
/* ID 241 */ NI,
/* ID 242 */ NI,
/* ID 243 */ NI,
/* ID 244 */ NI,
/* ID 245 */ NI,
/* ID 246 */ NI,
/* ID 247 */ NI,
/* ID 248 */ NI,
/* ID 249 */ NI,
/* ID 250 */ NI,
/* ID 251 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // Dummy par, used for debug
/* ID 252 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // Dummy par, used for debug
/* ID 253 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255 // Dummy par, used for debug
};
