/**************************************************************************
 This file is auto-generated by FactoryGenerator, do not modify it manually
**************************************************************************/

/**************************************************************************
 INCLUDES
**************************************************************************/
#include <common.h>
#include <InfoDef.h>
#include <GeniAppIfData.h>

/**************************************************************************
 DEFINES
**************************************************************************/
#define UC_ADDR_0_LI(X) ((UCHAR*)&X)

/**************************************************************************
 TABLE
**************************************************************************/
const ID_PTR conf_tab[] = 
{
/* ID   0 */ UC_ADDR_0_LI(gai_4_0_production_code_1), // production_type_code
/* ID   1 */ UC_ADDR_0_LI(gai_4_1_production_code_2), // production_type_code
/* ID   2 */ UC_ADDR_0_LI(gai_4_2_production_code_3), // production_type_code
/* ID   3 */ UC_ADDR_0_LI(gai_4_3_production_code_4), // production_type_code
/* ID   4 */ UC_ADDR_0_LI(gai_4_4_production_code_5), // production_rev_date_code
/* ID   5 */ UC_ADDR_0_LI(gai_4_5_production_code_6), // production_rev_date_code
/* ID   6 */ UC_ADDR_0_LI(gai_4_6_production_code_7), // production_rev_date_code
/* ID   7 */ UC_ADDR_0_LI(gai_4_7_production_code_8), // production_serial_no
/* ID   8 */ UC_ADDR_0_LI(gai_4_8_production_code_9), // production_serial_no
/* ID   9 */ UC_ADDR_0_LI(gai_4_9_production_code_10), // production_serial_no
/* ID  10 */ NA,
/* ID  11 */ NA,
/* ID  12 */ NA,
/* ID  13 */ NA,
/* ID  14 */ NA,
/* ID  15 */ NA,
/* ID  16 */ NA,
/* ID  17 */ NA,
/* ID  18 */ NA,
/* ID  19 */ NA,
/* ID  20 */ NA,
/* ID  21 */ UC_ADDR_0_LI(gai_4_21_mac_addr_0), // MAC address byte 0 - least significant
/* ID  22 */ UC_ADDR_0_LI(gai_4_22_mac_addr_1), // MAC address byte 1
/* ID  23 */ UC_ADDR_0_LI(gai_4_23_mac_addr_2), // MAC address byte 2
/* ID  24 */ UC_ADDR_0_LI(gai_4_24_mac_addr_3), // MAC address byte 3
/* ID  25 */ UC_ADDR_0_LI(gai_4_25_mac_addr_4), // MAC address byte 4
/* ID  26 */ UC_ADDR_0_LI(gai_4_26_mac_addr_5), // MAC address byte 5 - most significant
/* ID  27 */ NA,
/* ID  28 */ NA,
/* ID  29 */ NA,
/* ID  30 */ NA,
/* ID  31 */ NA,
/* ID  32 */ NA,
/* ID  33 */ NA,
/* ID  34 */ NA,
/* ID  35 */ NA,
/* ID  36 */ NA,
/* ID  37 */ NA,
/* ID  38 */ NA,
/* ID  39 */ NA,
/* ID  40 */ NA,
/* ID  41 */ NA,
/* ID  42 */ NA,
/* ID  43 */ NA,
/* ID  44 */ NA,
/* ID  45 */ NA,
/* ID  46 */ UC_ADDR_0_LI(gai_4_46_slave_unit_address), // slave_unit_address
/* ID  47 */ UC_ADDR_0_LI(gai_4_47_slave_group_address), // slave_group_address
/* ID  48 */ NA,
/* ID  49 */ NA,
/* ID  50 */ NA,
/* ID  51 */ NA,
/* ID  52 */ NA,
/* ID  53 */ NA,
/* ID  54 */ NA,
/* ID  55 */ NA,
/* ID  56 */ NA,
/* ID  57 */ NA,
/* ID  58 */ NA,
/* ID  59 */ NA,
/* ID  60 */ NA,
/* ID  61 */ NA,
/* ID  62 */ NA,
/* ID  63 */ NA,
/* ID  64 */ NA,
/* ID  65 */ NA,
/* ID  66 */ NA,
/* ID  67 */ NA,
/* ID  68 */ NA,
/* ID  69 */ NA,
/* ID  70 */ NA,
/* ID  71 */ NA,
/* ID  72 */ NA,
/* ID  73 */ NA,
/* ID  74 */ NA,
/* ID  75 */ NA,
/* ID  76 */ NA,
/* ID  77 */ NA,
/* ID  78 */ NA,
/* ID  79 */ UC_ADDR_0_LI(gai_4_79_baud_rate_default), // baud_rate_default
/* ID  80 */ UC_ADDR_0_LI(gai_4_80_min_reply_delay_default), // min_reply_delay_default
/* ID  81 */ UC_ADDR_0_LI(gai_4_81_geni_setup), // 
/* ID  82 */ NA,
/* ID  83 */ NA,
/* ID  84 */ NA,
/* ID  85 */ UC_ADDR_0_LI(gai_4_85_demo_suitcase_mode_enabled), // demo_suitcase_mode_enabled
/* ID  86 */ UC_ADDR_0_LI(gai_4_86_display_wizard_enable), // Wizard is active if true
/* ID  87 */ UC_ADDR_0_LI(gai_4_87_pit_level_sim_enabled), // pit_level_sim_enabled
/* ID  88 */ NA,
/* ID  89 */ NA,
/* ID  90 */ NA,
/* ID  91 */ NA,
/* ID  92 */ NA,
/* ID  93 */ NA,
/* ID  94 */ NA,
/* ID  95 */ NA,
/* ID  96 */ NA,
/* ID  97 */ NA,
/* ID  98 */ NA,
/* ID  99 */ NA,
/* ID 100 */ NA,
/* ID 101 */ NA,
/* ID 102 */ NA,
/* ID 103 */ NA,
/* ID 104 */ NA,
/* ID 105 */ NA,
/* ID 106 */ NA,
/* ID 107 */ NA,
/* ID 108 */ NA,
/* ID 109 */ NA,
/* ID 110 */ UC_ADDR_0_LI(gai_4_110_ana_out_1_conf_func), // Analog output 1 config
/* ID 111 */ UC_ADDR_0_LI(gai_4_111_ana_out_2_conf_func), // Analog output 2 config
/* ID 112 */ UC_ADDR_0_LI(gai_4_112_ana_out_3_conf_func), // Analog output 3 config
/* ID 113 */ UC_ADDR_0_LI(gai_4_113_ana_out_4_conf_func), // Analog output 4 config
/* ID 114 */ UC_ADDR_0_LI(gai_4_114_ana_out_5_conf_func), // Analog output 5 config
/* ID 115 */ UC_ADDR_0_LI(gai_4_115_ana_out_6_conf_func), // Analog output 6 config
/* ID 116 */ NA,
/* ID 117 */ NA,
/* ID 118 */ NA,
/* ID 119 */ NA,
/* ID 120 */ NA,
/* ID 121 */ NA,
/* ID 122 */ UC_ADDR_0_LI(gai_4_122_control_mode_pump1), // pump1 control mode
/* ID 123 */ UC_ADDR_0_LI(gai_4_123_control_mode_pump2), // pump2 control mode
/* ID 124 */ UC_ADDR_0_LI(gai_4_124_control_mode_pump3), // pump3 control mode
/* ID 125 */ UC_ADDR_0_LI(gai_4_125_control_mode_pump4), // pump4 control mode
/* ID 126 */ UC_ADDR_0_LI(gai_4_126_control_mode_pump5), // pump5 control mode
/* ID 127 */ UC_ADDR_0_LI(gai_4_127_control_mode_pump6), // pump6 control mode
/* ID 128 */ UC_ADDR_0_LI(gai_4_128_pid_feedback_pump1), // pump1 pid feedback signal
/* ID 129 */ UC_ADDR_0_LI(gai_4_129_pid_feedback_pump2), // pump2 pid feedback signal
/* ID 130 */ UC_ADDR_0_LI(gai_4_130_pid_feedback_pump3), // pump3 pidfeedback signal
/* ID 131 */ UC_ADDR_0_LI(gai_4_131_pid_feedback_pump4), // pump4 pidfeedback signal
/* ID 132 */ UC_ADDR_0_LI(gai_4_132_pid_feedback_pump5), // pump5 pidfeedback signal
/* ID 133 */ UC_ADDR_0_LI(gai_4_133_pid_feedback_pump6), // pump6 pidfeedback signal
/* ID 134 */ UC_ADDR_0_LI(gai_4_134_set_point_type_pump1), // pump1 setpoint type
/* ID 135 */ UC_ADDR_0_LI(gai_4_135_set_point_type_pump2), // pump2 setpoint type
/* ID 136 */ UC_ADDR_0_LI(gai_4_136_set_point_type_pump3), // pump3 setpoint type
/* ID 137 */ UC_ADDR_0_LI(gai_4_137_set_point_type_pump4), // pump4 setpoint type
/* ID 138 */ UC_ADDR_0_LI(gai_4_138_set_point_type_pump5), // pump5 setpoint type
/* ID 139 */ UC_ADDR_0_LI(gai_4_139_set_point_type_pump6), // pump6 setpoint type
/* ID 140 */ UC_ADDR_0_LI(gai_4_140_ai_setpoint_pump1), // pump1 setpoint(ai)
/* ID 141 */ UC_ADDR_0_LI(gai_4_141_ai_setpoint_pump2), // pump2 setpoint(ai)
/* ID 142 */ UC_ADDR_0_LI(gai_4_142_ai_setpoint_pump3), // pump3 setpoint(ai)
/* ID 143 */ UC_ADDR_0_LI(gai_4_143_ai_setpoint_pump4), // pump4 setpoint(ai)
/* ID 144 */ UC_ADDR_0_LI(gai_4_144_ai_setpoint_pump5), // pump5 setpoint(ai)
/* ID 145 */ UC_ADDR_0_LI(gai_4_145_ai_setpoint_pump6), // pump6 setpoint(ai)
/* ID 146 */ UC_ADDR_0_LI(gai_4_146_fixed_setpoint_pump1), // pump1 setpoint(fixed)
/* ID 147 */ UC_ADDR_0_LI(gai_4_147_fixed_setpoint_pump2), // pump2 setpoint(fixed)
/* ID 148 */ UC_ADDR_0_LI(gai_4_148_fixed_setpoint_pump3), // pump3 setpoint(fixed)
/* ID 149 */ UC_ADDR_0_LI(gai_4_149_fixed_setpoint_pump4), // pump4 setpoint(fixed)
/* ID 150 */ UC_ADDR_0_LI(gai_4_150_fixed_setpoint_pump5), // pump5 setpoint(fixed)
/* ID 151 */ UC_ADDR_0_LI(gai_4_151_fixed_setpoint_pump6) // pump6 setpoint(fixed)
};

/**************************************************************************
 INFO TABLE
**************************************************************************/
const ID_INFO conf_info_tab[] = 
{
/* ID   0 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // production_type_code
/* ID   1 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // production_type_code
/* ID   2 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // production_type_code
/* ID   3 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // production_type_code
/* ID   4 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // production_rev_date_code
/* ID   5 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // production_rev_date_code
/* ID   6 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // production_rev_date_code
/* ID   7 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // production_serial_no
/* ID   8 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // production_serial_no
/* ID   9 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // production_serial_no
/* ID  10 */ NI,
/* ID  11 */ NI,
/* ID  12 */ NI,
/* ID  13 */ NI,
/* ID  14 */ NI,
/* ID  15 */ NI,
/* ID  16 */ NI,
/* ID  17 */ NI,
/* ID  18 */ NI,
/* ID  19 */ NI,
/* ID  20 */ NI,
/* ID  21 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // MAC address byte 0 - least significant
/* ID  22 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // MAC address byte 1
/* ID  23 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // MAC address byte 2
/* ID  24 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // MAC address byte 3
/* ID  25 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // MAC address byte 4
/* ID  26 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // MAC address byte 5 - most significant
/* ID  27 */ NI,
/* ID  28 */ NI,
/* ID  29 */ NI,
/* ID  30 */ NI,
/* ID  31 */ NI,
/* ID  32 */ NI,
/* ID  33 */ NI,
/* ID  34 */ NI,
/* ID  35 */ NI,
/* ID  36 */ NI,
/* ID  37 */ NI,
/* ID  38 */ NI,
/* ID  39 */ NI,
/* ID  40 */ NI,
/* ID  41 */ NI,
/* ID  42 */ NI,
/* ID  43 */ NI,
/* ID  44 */ NI,
/* ID  45 */ NI,
/* ID  46 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // slave_unit_address
/* ID  47 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // slave_group_address
/* ID  48 */ NI,
/* ID  49 */ NI,
/* ID  50 */ NI,
/* ID  51 */ NI,
/* ID  52 */ NI,
/* ID  53 */ NI,
/* ID  54 */ NI,
/* ID  55 */ NI,
/* ID  56 */ NI,
/* ID  57 */ NI,
/* ID  58 */ NI,
/* ID  59 */ NI,
/* ID  60 */ NI,
/* ID  61 */ NI,
/* ID  62 */ NI,
/* ID  63 */ NI,
/* ID  64 */ NI,
/* ID  65 */ NI,
/* ID  66 */ NI,
/* ID  67 */ NI,
/* ID  68 */ NI,
/* ID  69 */ NI,
/* ID  70 */ NI,
/* ID  71 */ NI,
/* ID  72 */ NI,
/* ID  73 */ NI,
/* ID  74 */ NI,
/* ID  75 */ NI,
/* ID  76 */ NI,
/* ID  77 */ NI,
/* ID  78 */ NI,
/* ID  79 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // baud_rate_default
/* ID  80 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // min_reply_delay_default
/* ID  81 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // 
/* ID  82 */ NI,
/* ID  83 */ NI,
/* ID  84 */ NI,
/* ID  85 */ BITVAR_254, // demo_suitcase_mode_enabled
/* ID  86 */ BITVAR_254, // Wizard is active if true
/* ID  87 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // pit_level_sim_enabled
/* ID  88 */ NI,
/* ID  89 */ NI,
/* ID  90 */ NI,
/* ID  91 */ NI,
/* ID  92 */ NI,
/* ID  93 */ NI,
/* ID  94 */ NI,
/* ID  95 */ NI,
/* ID  96 */ NI,
/* ID  97 */ NI,
/* ID  98 */ NI,
/* ID  99 */ NI,
/* ID 100 */ NI,
/* ID 101 */ NI,
/* ID 102 */ NI,
/* ID 103 */ NI,
/* ID 104 */ NI,
/* ID 105 */ NI,
/* ID 106 */ NI,
/* ID 107 */ NI,
/* ID 108 */ NI,
/* ID 109 */ NI,
/* ID 110 */ BITVAR_254, // Analog output 1 config
/* ID 111 */ BITVAR_254, // Analog output 2 config
/* ID 112 */ BITVAR_254, // Analog output 3 config
/* ID 113 */ BITVAR_254, // Analog output 4 config
/* ID 114 */ BITVAR_254, // Analog output 5 config
/* ID 115 */ BITVAR_254, // Analog output 6 config
/* ID 116 */ NI,
/* ID 117 */ NI,
/* ID 118 */ NI,
/* ID 119 */ NI,
/* ID 120 */ NI,
/* ID 121 */ NI,
/* ID 122 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump1 control mode
/* ID 123 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump2 control mode
/* ID 124 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump3 control mode
/* ID 125 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump4 control mode
/* ID 126 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump5 control mode
/* ID 127 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump6 control mode
/* ID 128 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump1 pid feedback signal
/* ID 129 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump2 pid feedback signal
/* ID 130 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump3 pidfeedback signal
/* ID 131 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump4 pidfeedback signal
/* ID 132 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump5 pidfeedback signal
/* ID 133 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump6 pidfeedback signal
/* ID 134 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump1 setpoint type
/* ID 135 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump2 setpoint type
/* ID 136 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump3 setpoint type
/* ID 137 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump4 setpoint type
/* ID 138 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump5 setpoint type
/* ID 139 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump6 setpoint type
/* ID 140 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump1 setpoint(ai)
/* ID 141 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump2 setpoint(ai)
/* ID 142 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump3 setpoint(ai)
/* ID 143 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump4 setpoint(ai)
/* ID 144 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump5 setpoint(ai)
/* ID 145 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // pump6 setpoint(ai)
/* ID 146 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_1PCT, // pump1 setpoint(fixed)
/* ID 147 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_1PCT, // pump2 setpoint(fixed)
/* ID 148 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_1PCT, // pump3 setpoint(fixed)
/* ID 149 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_1PCT, // pump4 setpoint(fixed)
/* ID 150 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_1PCT, // pump5 setpoint(fixed)
/* ID 151 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_1PCT // pump6 setpoint(fixed)
};
