/**************************************************************************
 This file is auto-generated by FactoryGenerator, do not modify it manually
**************************************************************************/

/**************************************************************************
 INCLUDES
**************************************************************************/
#include <common.h>
#include <InfoDef.h>
#include <GeniAppIfData.h>

/**************************************************************************
 DEFINES
**************************************************************************/
#define UC_ADDR_0_LI(X) ((UCHAR*)&X)

/**************************************************************************
 TABLE
**************************************************************************/
const ID_PTR ref16_tab[] = 
{
/* ID   0 */ UC_ADDR_0_LI(gai_13_0_event_log_clear_id), // event_log_clear_id
/* ID   1 */ UC_ADDR_0_LI(gai_13_1_ana_out_user_1), // 
/* ID   2 */ UC_ADDR_0_LI(gai_13_2_ana_out_user_2), // 
/* ID   3 */ UC_ADDR_0_LI(gai_13_3_ana_out_user_3), // 
/* ID   4 */ NA,
/* ID   5 */ NA,
/* ID   6 */ NA,
/* ID   7 */ NA,
/* ID   8 */ NA,
/* ID   9 */ NA,
/* ID  10 */ UC_ADDR_0_LI(gai_13_10_dosing_feed_tank_level), // 
/* ID  11 */ UC_ADDR_0_LI(gai_13_11_chemical_total_dosed) // 
};

/**************************************************************************
 INFO TABLE
**************************************************************************/
const ID_INFO ref16_info_tab[] = 
{
/* ID   0 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // event_log_clear_id
/* ID   1 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // 
/* ID   2 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // 
/* ID   3 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_DOT1PCT, // 
/* ID   4 */ NI,
/* ID   5 */ NI,
/* ID   6 */ NI,
/* ID   7 */ NI,
/* ID   8 */ NI,
/* ID   9 */ NI,
/* ID  10 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // 
/* ID  11 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254 // 
};
