/**************************************************************************
 This file is auto-generated by FactoryGenerator, do not modify it manually
**************************************************************************/

/**************************************************************************
 INCLUDES
**************************************************************************/
#include <common.h>
#include <InfoDef.h>
#include <GeniAppIfData.h>

/**************************************************************************
 DEFINES
**************************************************************************/
#define UC_ADDR_0_LI(X) ((UCHAR*)&X)

/**************************************************************************
 TABLE
**************************************************************************/
const ID_PTR meas32_tab[] = 
{
/* ID   0 */ UC_ADDR_0_LI(gai_14_0_pit_power), // pit_power
/* ID   1 */ UC_ADDR_0_LI(gai_14_1_pit_energy), // pit_energy
/* ID   2 */ UC_ADDR_0_LI(gai_14_2_pit_pumped_volume), // pit_pumped_volume
/* ID   3 */ UC_ADDR_0_LI(gai_14_3_pit_opr_time), // pit_operation_time
/* ID   4 */ UC_ADDR_0_LI(gai_14_4_pit_2_pumps_opr_time), // parallel_operation_time
/* ID   5 */ UC_ADDR_0_LI(gai_14_5_pit_3_pumps_opr_time), // Total simultaneous 3 pump operating time
/* ID   6 */ UC_ADDR_0_LI(gai_14_6_pit_4_pumps_opr_time), // Total simultaneous 4 pump operating time
/* ID   7 */ UC_ADDR_0_LI(gai_14_7_pit_5_pumps_opr_time), // Total simultaneous 5 pump operating time
/* ID   8 */ UC_ADDR_0_LI(gai_14_8_pit_6_pumps_opr_time), // Total simultaneous 6 pump operating time
/* ID   9 */ UC_ADDR_0_LI(gai_14_9_pit_0_pumps_opr_time), // Total simultaneous 0 pump operating time
/* ID  10 */ UC_ADDR_0_LI(gai_14_10_pit_1_pumps_opr_time), // Total simultaneous 1 pump operating time
/* ID  11 */ NA,
/* ID  12 */ NA,
/* ID  13 */ NA,
/* ID  14 */ NA,
/* ID  15 */ NA,
/* ID  16 */ NA,
/* ID  17 */ NA,
/* ID  18 */ NA,
/* ID  19 */ NA,
/* ID  20 */ NA,
/* ID  21 */ NA,
/* ID  22 */ NA,
/* ID  23 */ NA,
/* ID  24 */ NA,
/* ID  25 */ NA,
/* ID  26 */ NA,
/* ID  27 */ NA,
/* ID  28 */ NA,
/* ID  29 */ NA,
/* ID  30 */ UC_ADDR_0_LI(gai_14_30_pit_mixer_opr_time), // 
/* ID  31 */ UC_ADDR_0_LI(gai_14_31_pit_mixer_start_cnt), // 
/* ID  32 */ NA,
/* ID  33 */ NA,
/* ID  34 */ NA,
/* ID  35 */ NA,
/* ID  36 */ NA,
/* ID  37 */ NA,
/* ID  38 */ NA,
/* ID  39 */ NA,
/* ID  40 */ UC_ADDR_0_LI(gai_14_40_p1_opr_time), // p1_opr_time
/* ID  41 */ UC_ADDR_0_LI(gai_14_41_p1_time_to_service), // p1_time_to_service
/* ID  42 */ UC_ADDR_0_LI(gai_14_42_p1_start_cnt), // p1_start_cnt
/* ID  43 */ UC_ADDR_0_LI(gai_14_43_p1_power), // 
/* ID  44 */ UC_ADDR_0_LI(gai_14_44_p1_energy), // 
/* ID  45 */ UC_ADDR_0_LI(gai_14_45_p1_anti_blocking_cnt), // anti-blocking count for pump1
/* ID  46 */ NA,
/* ID  47 */ NA,
/* ID  48 */ NA,
/* ID  49 */ NA,
/* ID  50 */ NA,
/* ID  51 */ NA,
/* ID  52 */ NA,
/* ID  53 */ NA,
/* ID  54 */ NA,
/* ID  55 */ NA,
/* ID  56 */ NA,
/* ID  57 */ NA,
/* ID  58 */ NA,
/* ID  59 */ NA,
/* ID  60 */ UC_ADDR_0_LI(gai_14_60_p2_opr_time), // p2_opr_time
/* ID  61 */ UC_ADDR_0_LI(gai_14_61_p2_time_to_service), // p2_time_to_service
/* ID  62 */ UC_ADDR_0_LI(gai_14_62_p2_start_cnt), // p2_start_cnt
/* ID  63 */ UC_ADDR_0_LI(gai_14_63_p2_power), // 
/* ID  64 */ UC_ADDR_0_LI(gai_14_64_p2_energy), // 
/* ID  65 */ UC_ADDR_0_LI(gai_14_65_p2_anti_blocking_cnt), // anti-blocking count for pump2
/* ID  66 */ NA,
/* ID  67 */ NA,
/* ID  68 */ NA,
/* ID  69 */ NA,
/* ID  70 */ NA,
/* ID  71 */ NA,
/* ID  72 */ NA,
/* ID  73 */ NA,
/* ID  74 */ NA,
/* ID  75 */ NA,
/* ID  76 */ NA,
/* ID  77 */ NA,
/* ID  78 */ NA,
/* ID  79 */ NA,
/* ID  80 */ UC_ADDR_0_LI(gai_14_80_p3_opr_time), // p3_opr_time
/* ID  81 */ UC_ADDR_0_LI(gai_14_81_p3_time_to_service), // p3_time_to_service
/* ID  82 */ UC_ADDR_0_LI(gai_14_82_p3_start_cnt), // p3_start_cnt
/* ID  83 */ UC_ADDR_0_LI(gai_14_83_p3_power), // p3 power
/* ID  84 */ UC_ADDR_0_LI(gai_14_84_p3_energy), // 
/* ID  85 */ UC_ADDR_0_LI(gai_14_85_p3_anti_blocking_cnt), // anti-blocking count for pump3
/* ID  86 */ NA,
/* ID  87 */ NA,
/* ID  88 */ NA,
/* ID  89 */ NA,
/* ID  90 */ NA,
/* ID  91 */ NA,
/* ID  92 */ NA,
/* ID  93 */ NA,
/* ID  94 */ NA,
/* ID  95 */ NA,
/* ID  96 */ NA,
/* ID  97 */ NA,
/* ID  98 */ NA,
/* ID  99 */ NA,
/* ID 100 */ UC_ADDR_0_LI(gai_14_100_p4_opr_time), // p4_opr_time
/* ID 101 */ UC_ADDR_0_LI(gai_14_101_p4_time_to_service), // p4_time_to_service
/* ID 102 */ UC_ADDR_0_LI(gai_14_102_p4_start_cnt), // p4_start_cnt
/* ID 103 */ UC_ADDR_0_LI(gai_14_103_p4_power), // p4 power
/* ID 104 */ UC_ADDR_0_LI(gai_14_104_p4_energy), // 
/* ID 105 */ UC_ADDR_0_LI(gai_14_105_p4_anti_blocking_cnt), // anti-blocking count for pump4
/* ID 106 */ NA,
/* ID 107 */ NA,
/* ID 108 */ NA,
/* ID 109 */ NA,
/* ID 110 */ NA,
/* ID 111 */ NA,
/* ID 112 */ NA,
/* ID 113 */ NA,
/* ID 114 */ NA,
/* ID 115 */ NA,
/* ID 116 */ NA,
/* ID 117 */ NA,
/* ID 118 */ NA,
/* ID 119 */ NA,
/* ID 120 */ UC_ADDR_0_LI(gai_14_120_p5_opr_time), // p5_opr_time
/* ID 121 */ UC_ADDR_0_LI(gai_14_121_p5_time_to_service), // p5_time_to_service
/* ID 122 */ UC_ADDR_0_LI(gai_14_122_p5_start_cnt), // p5_start_cnt
/* ID 123 */ UC_ADDR_0_LI(gai_14_123_p5_power), // p5 power
/* ID 124 */ UC_ADDR_0_LI(gai_14_124_p5_energy), // 
/* ID 125 */ UC_ADDR_0_LI(gai_14_125_p5_anti_blocking_cnt), // anti-blocking count for pump5
/* ID 126 */ NA,
/* ID 127 */ NA,
/* ID 128 */ NA,
/* ID 129 */ NA,
/* ID 130 */ NA,
/* ID 131 */ NA,
/* ID 132 */ NA,
/* ID 133 */ NA,
/* ID 134 */ NA,
/* ID 135 */ NA,
/* ID 136 */ NA,
/* ID 137 */ NA,
/* ID 138 */ NA,
/* ID 139 */ NA,
/* ID 140 */ UC_ADDR_0_LI(gai_14_140_p6_opr_time), // p6_opr_time
/* ID 141 */ UC_ADDR_0_LI(gai_14_141_p6_time_to_service), // p6_time_to_service
/* ID 142 */ UC_ADDR_0_LI(gai_14_142_p6_start_cnt), // p6_start_cnt
/* ID 143 */ UC_ADDR_0_LI(gai_14_143_p6_power), // p6 power
/* ID 144 */ UC_ADDR_0_LI(gai_14_144_p6_energy), // 
/* ID 145 */ UC_ADDR_0_LI(gai_14_145_p6_anti_blocking_cnt), // anti-blocking count for pump6
/* ID 146 */ NA,
/* ID 147 */ NA,
/* ID 148 */ NA,
/* ID 149 */ NA,
/* ID 150 */ NA,
/* ID 151 */ NA,
/* ID 152 */ NA,
/* ID 153 */ NA,
/* ID 154 */ NA,
/* ID 155 */ NA,
/* ID 156 */ NA,
/* ID 157 */ NA,
/* ID 158 */ NA,
/* ID 159 */ NA,
/* ID 160 */ UC_ADDR_0_LI(gai_14_160_real_time_clock), // real_time_clock
/* ID 161 */ UC_ADDR_0_LI(gai_14_161_ip_address), // IP address of GPRS connection
/* ID 162 */ NA,
/* ID 163 */ NA,
/* ID 164 */ NA,
/* ID 165 */ NA,
/* ID 166 */ NA,
/* ID 167 */ NA,
/* ID 168 */ NA,
/* ID 169 */ NA,
/* ID 170 */ UC_ADDR_0_LI(gai_14_170_user_defined_cnt_1), // user defined counter 1
/* ID 171 */ UC_ADDR_0_LI(gai_14_171_user_defined_cnt_2), // user defined counter 2
/* ID 172 */ UC_ADDR_0_LI(gai_14_172_user_defined_cnt_3), // user defined counter 3
/* ID 173 */ UC_ADDR_0_LI(gai_14_173_today_udc_counter1), // 
/* ID 174 */ UC_ADDR_0_LI(gai_14_174_today_udc_counter2), // 
/* ID 175 */ UC_ADDR_0_LI(gai_14_175_today_udc_counter3), // 
/* ID 176 */ UC_ADDR_0_LI(gai_14_176_yesterday_udc_counter1), // 
/* ID 177 */ UC_ADDR_0_LI(gai_14_177_yesterday_udc_counter2), // 
/* ID 178 */ UC_ADDR_0_LI(gai_14_178_yesterday_udc_counter3), // 
/* ID 179 */ UC_ADDR_0_LI(gai_14_179_overflow_volume), // overflow volume
/* ID 180 */ UC_ADDR_0_LI(gai_14_180_overflow_time), // overflow time
/* ID 181 */ NA,
/* ID 182 */ NA,
/* ID 183 */ NA,
/* ID 184 */ NA,
/* ID 185 */ NA,
/* ID 186 */ NA,
/* ID 187 */ NA,
/* ID 188 */ NA,
/* ID 189 */ NA,
/* ID 190 */ UC_ADDR_0_LI(gai_14_190_h2s_level_act), // 
/* ID 191 */ UC_ADDR_0_LI(gai_14_191_h2s_level_today_log), // 
/* ID 192 */ UC_ADDR_0_LI(gai_14_192_h2s_level_yesterday_log), // 
/* ID 193 */ UC_ADDR_0_LI(gai_14_193_dosing_feed_tank_level), // 
/* ID 194 */ UC_ADDR_0_LI(gai_14_194_dosing_volume_total_log), // 
/* ID 195 */ UC_ADDR_0_LI(gai_14_195_dosing_volume_today_log), // 
/* ID 196 */ UC_ADDR_0_LI(gai_14_196_dosing_volume_yesterday_log), // 
/* ID 197 */ UC_ADDR_0_LI(gai_14_197_dosing_ref_act) // 
};

/**************************************************************************
 INFO TABLE
**************************************************************************/
const ID_INFO meas32_info_tab[] = 
{
/* ID   0 */ COMMON_INFO + COM_INDEX_EXT_POWER_1W, // pit_power
/* ID   1 */ COMMON_INFO + COM_INDEX_EXT_ENERGY_DOT1KWH, // pit_energy
/* ID   2 */ COMMON_INFO+  COM_INDEX_EXT_TOTAL_VOLUME_DOT1M3, // pit_pumped_volume
/* ID   3 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // pit_operation_time
/* ID   4 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // parallel_operation_time
/* ID   5 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // Total simultaneous 3 pump operating time
/* ID   6 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // Total simultaneous 4 pump operating time
/* ID   7 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // Total simultaneous 5 pump operating time
/* ID   8 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // Total simultaneous 6 pump operating time
/* ID   9 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // Total simultaneous 0 pump operating time
/* ID  10 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // Total simultaneous 1 pump operating time
/* ID  11 */ NI,
/* ID  12 */ NI,
/* ID  13 */ NI,
/* ID  14 */ NI,
/* ID  15 */ NI,
/* ID  16 */ NI,
/* ID  17 */ NI,
/* ID  18 */ NI,
/* ID  19 */ NI,
/* ID  20 */ NI,
/* ID  21 */ NI,
/* ID  22 */ NI,
/* ID  23 */ NI,
/* ID  24 */ NI,
/* ID  25 */ NI,
/* ID  26 */ NI,
/* ID  27 */ NI,
/* ID  28 */ NI,
/* ID  29 */ NI,
/* ID  30 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // 
/* ID  31 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // 
/* ID  32 */ NI,
/* ID  33 */ NI,
/* ID  34 */ NI,
/* ID  35 */ NI,
/* ID  36 */ NI,
/* ID  37 */ NI,
/* ID  38 */ NI,
/* ID  39 */ NI,
/* ID  40 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p1_opr_time
/* ID  41 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p1_time_to_service
/* ID  42 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p1_start_cnt
/* ID  43 */ COMMON_INFO + COM_INDEX_EXT_POWER_1W, // 
/* ID  44 */ COMMON_INFO + COM_INDEX_EXT_ENERGY_DOT1KWH, // 
/* ID  45 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // anti-blocking count for pump1
/* ID  46 */ NI,
/* ID  47 */ NI,
/* ID  48 */ NI,
/* ID  49 */ NI,
/* ID  50 */ NI,
/* ID  51 */ NI,
/* ID  52 */ NI,
/* ID  53 */ NI,
/* ID  54 */ NI,
/* ID  55 */ NI,
/* ID  56 */ NI,
/* ID  57 */ NI,
/* ID  58 */ NI,
/* ID  59 */ NI,
/* ID  60 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p2_opr_time
/* ID  61 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p2_time_to_service
/* ID  62 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p2_start_cnt
/* ID  63 */ COMMON_INFO + COM_INDEX_EXT_POWER_1W, // 
/* ID  64 */ COMMON_INFO + COM_INDEX_EXT_ENERGY_DOT1KWH, // 
/* ID  65 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // anti-blocking count for pump2
/* ID  66 */ NI,
/* ID  67 */ NI,
/* ID  68 */ NI,
/* ID  69 */ NI,
/* ID  70 */ NI,
/* ID  71 */ NI,
/* ID  72 */ NI,
/* ID  73 */ NI,
/* ID  74 */ NI,
/* ID  75 */ NI,
/* ID  76 */ NI,
/* ID  77 */ NI,
/* ID  78 */ NI,
/* ID  79 */ NI,
/* ID  80 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p3_opr_time
/* ID  81 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p3_time_to_service
/* ID  82 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p3_start_cnt
/* ID  83 */ COMMON_INFO + COM_INDEX_EXT_POWER_1W, // p3 power
/* ID  84 */ COMMON_INFO + COM_INDEX_EXT_ENERGY_DOT1KWH, // 
/* ID  85 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // anti-blocking count for pump3
/* ID  86 */ NI,
/* ID  87 */ NI,
/* ID  88 */ NI,
/* ID  89 */ NI,
/* ID  90 */ NI,
/* ID  91 */ NI,
/* ID  92 */ NI,
/* ID  93 */ NI,
/* ID  94 */ NI,
/* ID  95 */ NI,
/* ID  96 */ NI,
/* ID  97 */ NI,
/* ID  98 */ NI,
/* ID  99 */ NI,
/* ID 100 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p4_opr_time
/* ID 101 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p4_time_to_service
/* ID 102 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p4_start_cnt
/* ID 103 */ COMMON_INFO + COM_INDEX_EXT_POWER_1W, // p4 power
/* ID 104 */ COMMON_INFO + COM_INDEX_EXT_ENERGY_DOT1KWH, // 
/* ID 105 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // anti-blocking count for pump4
/* ID 106 */ NI,
/* ID 107 */ NI,
/* ID 108 */ NI,
/* ID 109 */ NI,
/* ID 110 */ NI,
/* ID 111 */ NI,
/* ID 112 */ NI,
/* ID 113 */ NI,
/* ID 114 */ NI,
/* ID 115 */ NI,
/* ID 116 */ NI,
/* ID 117 */ NI,
/* ID 118 */ NI,
/* ID 119 */ NI,
/* ID 120 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p5_opr_time
/* ID 121 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p5_time_to_service
/* ID 122 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p5_start_cnt
/* ID 123 */ COMMON_INFO + COM_INDEX_EXT_POWER_1W, // p5 power
/* ID 124 */ COMMON_INFO + COM_INDEX_EXT_ENERGY_DOT1KWH, // 
/* ID 125 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // anti-blocking count for pump5
/* ID 126 */ NI,
/* ID 127 */ NI,
/* ID 128 */ NI,
/* ID 129 */ NI,
/* ID 130 */ NI,
/* ID 131 */ NI,
/* ID 132 */ NI,
/* ID 133 */ NI,
/* ID 134 */ NI,
/* ID 135 */ NI,
/* ID 136 */ NI,
/* ID 137 */ NI,
/* ID 138 */ NI,
/* ID 139 */ NI,
/* ID 140 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p6_opr_time
/* ID 141 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // p6_time_to_service
/* ID 142 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // p6_start_cnt
/* ID 143 */ COMMON_INFO + COM_INDEX_EXT_POWER_1W, // p6 power
/* ID 144 */ COMMON_INFO + COM_INDEX_EXT_ENERGY_DOT1KWH, // 
/* ID 145 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // anti-blocking count for pump6
/* ID 146 */ NI,
/* ID 147 */ NI,
/* ID 148 */ NI,
/* ID 149 */ NI,
/* ID 150 */ NI,
/* ID 151 */ NI,
/* ID 152 */ NI,
/* ID 153 */ NI,
/* ID 154 */ NI,
/* ID 155 */ NI,
/* ID 156 */ NI,
/* ID 157 */ NI,
/* ID 158 */ NI,
/* ID 159 */ NI,
/* ID 160 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // real_time_clock
/* ID 161 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // IP address of GPRS connection
/* ID 162 */ NI,
/* ID 163 */ NI,
/* ID 164 */ NI,
/* ID 165 */ NI,
/* ID 166 */ NI,
/* ID 167 */ NI,
/* ID 168 */ NI,
/* ID 169 */ NI,
/* ID 170 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // user defined counter 1
/* ID 171 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // user defined counter 2
/* ID 172 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // user defined counter 3
/* ID 173 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // 
/* ID 174 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // 
/* ID 175 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // 
/* ID 176 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // 
/* ID 177 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // 
/* ID 178 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // 
/* ID 179 */ COMMON_INFO+  COM_INDEX_EXT_OVER_VOLUME_DOT1M3, // overflow volume
/* ID 180 */ COMMON_INFO + COM_INDEX_EXT_TIME_1MIN, // overflow time
/* ID 181 */ NI,
/* ID 182 */ NI,
/* ID 183 */ NI,
/* ID 184 */ NI,
/* ID 185 */ NI,
/* ID 186 */ NI,
/* ID 187 */ NI,
/* ID 188 */ NI,
/* ID 189 */ NI,
/* ID 190 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_1PPM, // 
/* ID 191 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_1PPM, // 
/* ID 192 */ COMMON_INFO + COM_INDEX_EXT_PERCENTAGE_1PPM, // 
/* ID 193 */ COMMON_INFO + COM_INDEX_EXT_HEAD_DOT01M, // 
/* ID 194 */ COMMON_INFO + COM_INDEX_EXT_VOLUME_1ML, // 
/* ID 195 */ COMMON_INFO + COM_INDEX_EXT_VOLUME_1ML, // 
/* ID 196 */ COMMON_INFO + COM_INDEX_EXT_VOLUME_1ML, // 
/* ID 197 */ COMMON_INFO + COM_INDEX_EXT_FLOW_DOT1LH // 
};
