/**************************************************************************
 This file is auto-generated by FactoryGenerator, do not modify it manually
**************************************************************************/

/**************************************************************************
 INCLUDES
**************************************************************************/
#include <common.h>
#include <InfoDef.h>
#include <GeniAppIfData.h>

/**************************************************************************
 DEFINES
**************************************************************************/
#define UC_ADDR_0_LI(X) ((UCHAR*)&X)

/**************************************************************************
 TABLE
**************************************************************************/
const ID_PTR ref_tab[] = 
{
/* ID   0 */ NA,
/* ID   1 */ NA,
/* ID   2 */ NA,
/* ID   3 */ NA,
/* ID   4 */ NA,
/* ID   5 */ NA,
/* ID   6 */ NA,
/* ID   7 */ NA,
/* ID   8 */ NA,
/* ID   9 */ UC_ADDR_0_LI(gai_5_9_custom_relay), // custom_relay
/* ID  10 */ UC_ADDR_0_LI(gai_5_10_rtc_year_set), // Set real time clock the MPC way
/* ID  11 */ UC_ADDR_0_LI(gai_5_11_rtc_month_set), // Set real time clock the MPC way
/* ID  12 */ UC_ADDR_0_LI(gai_5_12_rtc_day_set), // Set real time clock the MPC way
/* ID  13 */ UC_ADDR_0_LI(gai_5_13_rtc_hour_set), // Set real time clock the MPC way
/* ID  14 */ UC_ADDR_0_LI(gai_5_14_rtc_minute_set), // Set real time clock the MPC way
/* ID  15 */ UC_ADDR_0_LI(gai_5_15_rtc_second_set), // Set real time clock the MPC way
/* ID  16 */ NA,
/* ID  17 */ NA,
/* ID  18 */ NA,
/* ID  19 */ NA,
/* ID  20 */ NA,
/* ID  21 */ NA,
/* ID  22 */ NA,
/* ID  23 */ NA,
/* ID  24 */ NA,
/* ID  25 */ NA,
/* ID  26 */ NA,
/* ID  27 */ NA,
/* ID  28 */ NA,
/* ID  29 */ NA,
/* ID  30 */ NA,
/* ID  31 */ NA,
/* ID  32 */ UC_ADDR_0_LI(gai_5_32_event_code_sim), // event_code_sim
/* ID  33 */ UC_ADDR_0_LI(gai_5_33_device_type_code_sim_id), // device_type_code_sim_id
/* ID  34 */ UC_ADDR_0_LI(gai_5_34_device_no_sim_id), // device_no_sim_id
/* ID  35 */ UC_ADDR_0_LI(gai_5_35_event_sim_activate), // event_sim_activate
/* ID  36 */ UC_ADDR_0_LI(gai_5_36_event_source_sim), // event_source_sim
/* ID  37 */ UC_ADDR_0_LI(gai_5_37_event_type_and_cond_sim), // event_type_and_cond_sim
/* ID  38 */ UC_ADDR_0_LI(gai_5_38_set_min_reply_delay), // set_min_reply_delay
/* ID  39 */ UC_ADDR_0_LI(gai_5_39_set_baud_rate), // set_baud_rate
/* ID  40 */ NA,
/* ID  41 */ NA,
/* ID  42 */ NA,
/* ID  43 */ NA,
/* ID  44 */ NA,
/* ID  45 */ UC_ADDR_0_LI(gai_5_45_sms_out_seq_no_ack), // sms_out_seq_no_ack
/* ID  46 */ NA,
/* ID  47 */ NA,
/* ID  48 */ NA,
/* ID  49 */ UC_ADDR_0_LI(gai_5_49_sim_card_status), // sim_card_status
/* ID  50 */ NA,
/* ID  51 */ NA,
/* ID  52 */ NA,
/* ID  53 */ NA,
/* ID  54 */ NA,
/* ID  55 */ UC_ADDR_0_LI(gai_5_55_gsm_state), // gsm_state
/* ID  56 */ UC_ADDR_0_LI(gai_5_56_cim_heartbeat), // Heartbeat from ciu module, telling that communication is ok
/* ID  57 */ UC_ADDR_0_LI(gai_5_57_cim_type) // Type of CIM/CIU connected. A CIM/CIU master writes the value
};

/**************************************************************************
 INFO TABLE
**************************************************************************/
const ID_INFO ref_info_tab[] = 
{
/* ID   0 */ NI,
/* ID   1 */ NI,
/* ID   2 */ NI,
/* ID   3 */ NI,
/* ID   4 */ NI,
/* ID   5 */ NI,
/* ID   6 */ NI,
/* ID   7 */ NI,
/* ID   8 */ NI,
/* ID   9 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // custom_relay
/* ID  10 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // Set real time clock the MPC way
/* ID  11 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // Set real time clock the MPC way
/* ID  12 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // Set real time clock the MPC way
/* ID  13 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // Set real time clock the MPC way
/* ID  14 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // Set real time clock the MPC way
/* ID  15 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // Set real time clock the MPC way
/* ID  16 */ NI,
/* ID  17 */ NI,
/* ID  18 */ NI,
/* ID  19 */ NI,
/* ID  20 */ NI,
/* ID  21 */ NI,
/* ID  22 */ NI,
/* ID  23 */ NI,
/* ID  24 */ NI,
/* ID  25 */ NI,
/* ID  26 */ NI,
/* ID  27 */ NI,
/* ID  28 */ NI,
/* ID  29 */ NI,
/* ID  30 */ NI,
/* ID  31 */ NI,
/* ID  32 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // event_code_sim
/* ID  33 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // device_type_code_sim_id
/* ID  34 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // device_no_sim_id
/* ID  35 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // event_sim_activate
/* ID  36 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // event_source_sim
/* ID  37 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // event_type_and_cond_sim
/* ID  38 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // set_min_reply_delay
/* ID  39 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // set_baud_rate
/* ID  40 */ NI,
/* ID  41 */ NI,
/* ID  42 */ NI,
/* ID  43 */ NI,
/* ID  44 */ NI,
/* ID  45 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // sms_out_seq_no_ack
/* ID  46 */ NI,
/* ID  47 */ NI,
/* ID  48 */ NI,
/* ID  49 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // sim_card_status
/* ID  50 */ NI,
/* ID  51 */ NI,
/* ID  52 */ NI,
/* ID  53 */ NI,
/* ID  54 */ NI,
/* ID  55 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254, // gsm_state
/* ID  56 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_255, // Heartbeat from ciu module, telling that communication is ok
/* ID  57 */ COMMON_INFO + COM_INDEX_EXT_DIMLESS_254 // Type of CIM/CIU connected. A CIM/CIU master writes the value
};
