/**************************************************************************
 This file is auto-generated by FactoryGenerator, do not modify it manually
**************************************************************************/

/**************************************************************************
 INCLUDES
**************************************************************************/
#include <common.h>

/**************************************************************************
 TABLE
**************************************************************************/
const ID_INFO cmd_info_tab[] = 
{
/* ID   0 */ Unexecutable,
/* ID   1 */ Executable, // GAI_CMD_RESET, Reset (reboot)
/* ID   2 */ Executable, // GAI_CMD_ALARM_RESET, alarm_reset
/* ID   3 */ Unexecutable,
/* ID   4 */ Unexecutable,
/* ID   5 */ Executable, // GAI_CMD_INTERLOCK_PIT, interlock_pit (stop all pumping)
/* ID   6 */ Executable, // GAI_CMD_AUTO_PIT, Pit controlled by automation
/* ID   7 */ Unexecutable,
/* ID   8 */ Unexecutable,
/* ID   9 */ Unexecutable,
/* ID  10 */ Unexecutable,
/* ID  11 */ Unexecutable,
/* ID  12 */ Unexecutable,
/* ID  13 */ Unexecutable,
/* ID  14 */ Unexecutable,
/* ID  15 */ Unexecutable,
/* ID  16 */ Unexecutable,
/* ID  17 */ Unexecutable,
/* ID  18 */ Unexecutable,
/* ID  19 */ Executable, // GAI_CMD_DISABLE_TEST_MODE, disable_test_mode
/* ID  20 */ Executable, // GAI_CMD_ENABLE_TEST_MODE, enable_test_mode
/* ID  21 */ Executable, // GAI_CMD_FILL_SIMULATED_LOG_DATA, For test of datalog. Not in profile
/* ID  22 */ Unexecutable,
/* ID  23 */ Unexecutable,
/* ID  24 */ Unexecutable,
/* ID  25 */ Unexecutable,
/* ID  26 */ Unexecutable,
/* ID  27 */ Unexecutable,
/* ID  28 */ Unexecutable,
/* ID  29 */ Unexecutable,
/* ID  30 */ Unexecutable,
/* ID  31 */ Unexecutable,
/* ID  32 */ Unexecutable,
/* ID  33 */ Unexecutable,
/* ID  34 */ Unexecutable,
/* ID  35 */ Unexecutable,
/* ID  36 */ Executable, // GAI_CMD_RESET_HIST, Resetter hele log blokken i Flash
/* ID  37 */ Unexecutable,
/* ID  38 */ Unexecutable,
/* ID  39 */ Unexecutable,
/* ID  40 */ Unexecutable,
/* ID  41 */ Unexecutable,
/* ID  42 */ Unexecutable,
/* ID  43 */ Unexecutable,
/* ID  44 */ Unexecutable,
/* ID  45 */ Unexecutable,
/* ID  46 */ Unexecutable,
/* ID  47 */ Unexecutable,
/* ID  48 */ Unexecutable,
/* ID  49 */ Unexecutable,
/* ID  50 */ Unexecutable,
/* ID  51 */ Executable, // GAI_CMD_RESET_EVENT_LOG, reset_event_log and reset alarm_log
/* ID  52 */ Unexecutable,
/* ID  53 */ Unexecutable,
/* ID  54 */ Unexecutable,
/* ID  55 */ Unexecutable,
/* ID  56 */ Unexecutable,
/* ID  57 */ Unexecutable,
/* ID  58 */ Unexecutable,
/* ID  59 */ Unexecutable,
/* ID  60 */ Executable, // GAI_CMD_STOP_P1, STOP_P1
/* ID  61 */ Executable, // GAI_CMD_START_P1, START_P1
/* ID  62 */ Executable, // GAI_CMD_AUTO_P1, AUTO_P1
/* ID  63 */ Executable, // GAI_CMD_STOP_P2, STOP_P2
/* ID  64 */ Executable, // GAI_CMD_START_P2, START_P2
/* ID  65 */ Executable, // GAI_CMD_AUTO_P2, AUTO_P2
/* ID  66 */ Executable, // GAI_CMD_STOP_P3, STOP_P3
/* ID  67 */ Executable, // GAI_CMD_START_P3, START_P3
/* ID  68 */ Executable, // GAI_CMD_AUTO_P3, AUTO_P3
/* ID  69 */ Executable, // GAI_CMD_STOP_P4, STOP_P4
/* ID  70 */ Executable, // GAI_CMD_START_P4, START_P4
/* ID  71 */ Executable, // GAI_CMD_AUTO_P4, AUTO_P4
/* ID  72 */ Executable, // GAI_CMD_STOP_P5, STOP_P5
/* ID  73 */ Executable, // GAI_CMD_START_P5, START_P5
/* ID  74 */ Executable, // GAI_CMD_AUTO_P5, AUTO_P5
/* ID  75 */ Executable, // GAI_CMD_STOP_P6, STOP_P6
/* ID  76 */ Executable, // GAI_CMD_START_P6, START_P6
/* ID  77 */ Executable, // GAI_CMD_AUTO_P6, AUTO_P6
/* ID  78 */ Executable, // GAI_CMD_CUSTOM_RELAY_ON, Activate cutsom relay
/* ID  79 */ Executable, // GAI_CMD_CUSTOM_RELAY_OFF, Deactivate custom relay
/* ID  80 */ Executable, // GAI_CMD_CUSTOM_RELAY_PULSE, Generates a 1s pulse
/* ID  81 */ Executable, // GAI_CMD_RESET_USER_DEF_CNT_1, reset user defined counter 1
/* ID  82 */ Executable, // GAI_CMD_RESET_USER_DEF_CNT_2, reset user defined counter 2
/* ID  83 */ Executable, // GAI_CMD_RESET_USER_DEF_CNT_3, reset user defined counter 3
/* ID  84 */ Unexecutable,
/* ID  85 */ Unexecutable,
/* ID  86 */ Unexecutable,
/* ID  87 */ Unexecutable,
/* ID  88 */ Unexecutable,
/* ID  89 */ Unexecutable,
/* ID  90 */ Unexecutable,
/* ID  91 */ Unexecutable,
/* ID  92 */ Unexecutable,
/* ID  93 */ Unexecutable,
/* ID  94 */ Unexecutable,
/* ID  95 */ Unexecutable,
/* ID  96 */ Unexecutable,
/* ID  97 */ Unexecutable,
/* ID  98 */ Unexecutable,
/* ID  99 */ Unexecutable,
/* ID 100 */ Unexecutable,
/* ID 101 */ Unexecutable,
/* ID 102 */ Executable, // GAI_CMD_RTC_USE_NEW_TIME_EVENT, Set real time clock the MPC way
/* ID 103 */ Unexecutable,
/* ID 104 */ Executable, // GAI_CMD_SCADA_CALL_BACK_ACK, Acknowledge by command
/* ID 105 */ Executable, // GAI_CMD_CALL_BACK_TEST, Scada callback test
/* ID 106 */ Unexecutable,
/* ID 107 */ Unexecutable,
/* ID 108 */ Unexecutable,
/* ID 109 */ Unexecutable,
/* ID 110 */ Unexecutable,
/* ID 111 */ Unexecutable,
/* ID 112 */ Unexecutable,
/* ID 113 */ Unexecutable,
/* ID 114 */ Unexecutable,
/* ID 115 */ Unexecutable,
/* ID 116 */ Unexecutable,
/* ID 117 */ Unexecutable,
/* ID 118 */ Executable, // GAI_CMD_SPECIFIC_ENERGY_TEST_RUN_P1, Start energy test for pump 1
/* ID 119 */ Executable, // GAI_CMD_SPECIFIC_ENERGY_TEST_RUN_P2, Start energy test for pump 2
/* ID 120 */ Executable, // GAI_CMD_SPECIFIC_ENERGY_TEST_RUN_P3, Start energy test for pump 3
/* ID 121 */ Executable, // GAI_CMD_SPECIFIC_ENERGY_TEST_RUN_P4, Start energy test for pump 4
/* ID 122 */ Executable, // GAI_CMD_SPECIFIC_ENERGY_TEST_RUN_P5, Start energy test for pump 5
/* ID 123 */ Executable, // GAI_CMD_SPECIFIC_ENERGY_TEST_RUN_P6, Start energy test for pump 6
/* ID 124 */ Executable, // GAI_CMD_ACTIVATE_ADVANCED_FLOW_CALC_LEARNING, Start advanced flow learning for all pumps
/* ID 125 */ Executable // GAI_CMD_ACTIVATE_ANTIBLOCK_PARAMETER_LEARNING, Start learning of antiblock 'normal parameters'
};

