/**************************************************************************
 This file is auto-generated by FactoryGenerator, do not modify it manually
**************************************************************************/

#ifndef __GENI_CNF_FACTORY_H__
#define __GENI_CNF_FACTORY_H__

/**************************************************************************
 DEFINES
**************************************************************************/
#define FACTORY_HIGH_MEAS_ID 240
#define FACTORY_HIGH_CMD_ID 125
#define FACTORY_HIGH_CONF_ID 151
#define FACTORY_HIGH_REF_ID 57
#define FACTORY_HIGH_ASCII_ID 0
#define FACTORY_HIGH_MEAS16_ID 253
#define FACTORY_HIGH_CONF16_ID 35
#define FACTORY_HIGH_REF16_ID 6
#define FACTORY_HIGH_MEAS32_ID 197
#define FACTORY_HIGH_CONF32_ID 1
#define FACTORY_HIGH_REF32_ID 1

#endif
